### ISSUE TITLE
Out of bounds glitch and glitched out houses in random spots

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#104]
i grabbed a random ledge and i got out of bounds. and there are random houses...

**Comment by sm64js** [comment]
hahaha, the random houses are temporary..  and if you are able to get out of bounds and your game crashes.. would you be able to post a video of that happening? or send the video in the discord?

**Comment by smm2mickeyink** [comment]
> hahaha, the random houses are temporary.. and if you are able to get out of bounds and your game crashes.. would you be able to post a video of that happening? or send the video in the discord?

its in youtube ill give link: https://youtu.be/AEk5BU-BNe0
