### ISSUE TITLE
Switching Levels

### ISSUE THREAD

**Issue by NabbitGamerThe1st** [sm64js/sm64js#106]
I can't switch what level I am in. I am stuck in cool cool mountain. I tried downloading another rom. But I can't put that rom in because there is no way to get rid of the rom you used. So I am stuck in cool cool mountain with no way to access other levels.

**Comment by Kevin-Is-Nice** [comment]
your not allowed to switch levels yet because it hasnt been added as a feature, different roms wont fix it

**Comment by sm64js** [comment]
you can play different levels at vanilla.sm64js.com
