### ISSUE TITLE
Standing in an area where two walls meet breaks the camera

### ISSUE THREAD

**Issue by siddhusathu20** [sm64js/sm64js#11]
Standing in an area where two walls meet makes the camera spin around like crazy

**Comment by Cooliokid956** [comment]
wow new person congrats
same happens everywhere
in holes
walls
yeh probably has to do with lakitu camera not fully implemented

**Comment by sm64js** [comment]
Will add this to camera to do list

**Comment by sm64js** [comment]
does this still happen?

**Comment by siddhusathu20** [comment]
No, I think it's fixed. You can verify by going to Castle Grounds and
standing at the corner of the hole that leads to the Vanish Cap course.
