### ISSUE TITLE
add camera control for keyboard

### ISSUE THREAD

**Issue by FallGuy308** [sm64js/sm64js#114]
i have no good controllers atm this would also help other players without controllers

**Comment by Whoblue579** [comment]
I'll add that to my fork, It will be easy to implement

**Comment by smm2mickeyink** [comment]
> I'll add that to my fork, It will be easy to implement

when you gonna add this??

**Comment by github10omar** [comment]
its addeed

**Comment by Cooliokid956** [comment]
close this
