### ISSUE TITLE
cool cool mountain in tall tall mountain glitch

### ISSUE THREAD

**Issue by sm64jsfan** [sm64js/sm64js#118]
This was a temporary bug, when me and my friend were going to play sm64 js he spawned in cool cool mountain while everyone else spawned in tall tall mountain. we could interact with him and he could interact with us. As i said this was temporary he restarted the game and he was in tall tall mountain just wanted to let you know. also when he stood still his hat colors glitched out. 

Thank you,
   sm64jsfan

**Comment by Vegito69** [comment]
As a fellow fan of this project i find this interesting

**Comment by Whoblue579** [comment]
probably a bad network packet finding its way in
