### ISSUE TITLE
Mario 64 Broken Rom

### ISSUE THREAD

**Issue by BigMemerMan1** [sm64js/sm64js#119]
so pretty much, i joined the game with my ordinary z64 rom file and it was corrupt! The faces on characters/textures were either black lined or just plain black. i tried changing the rom but i dont know how. i asked one of the players ingame and they said to clear my cookies on the site so i did but its staying on that rom. 

INFO 

Map: I was on the level "Tall Tall Mountain".

Ping: i was getting 50 to 100 ping.

Textures: the ui was completely gone! all my stars were just not there and my lives too. When i booted up the rom it just said 64 and when it ended only mario's face appeared without the background or ui and when i pressed enter i had full control of the game and the chat even worked but everything apart from very few textures like marios clothes.

NOTE: THIS IS NOT A JOKE I WILL SUPPLY TEXTURES BELOW

![creepy pic](https://user-images.githubusercontent.com/66966084/98802761-9bd83000-23c8-11eb-8b53-e10461bd2af6.JPG)

![image](https://user-images.githubusercontent.com/66966084/98802814-b27e8700-23c8-11eb-9afc-520d35ae7ea6.png)

![image](https://user-images.githubusercontent.com/66966084/98802840-bb6f5880-23c8-11eb-8a21-666418dafe94.png)

![image](https://user-images.githubusercontent.com/66966084/98802908-dcd04480-23c8-11eb-81b6-3e2357f2b851.png)

**Comment by Whoblue579** [comment]
wow

**Comment by sm64js** [comment]
interesting... did clearing cache and getting a fresh rom fix the issue?

**Comment by Cooliokid956** [comment]
also, there is no ui yet

**Comment by Vegito69** [comment]
suprising how the wrong rom can still load certain things

**Comment by Whoblue579** [comment]
@Vegito69 well, It just takes certain memory addresses and does not care that much if it actually contains data in the format it was expecting
