### ISSUE TITLE
(Suggestion) Add cookies for saving skin number and username

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#12]
so yeah that was fun, but now no one's on, also a chat should be implemented sometime if you want, you dont need to make it all on your own, there is probably some chatbox script out there

**Comment by sm64js** [comment]
yea agreed some kind of chat at somepoint

**Comment by Cooliokid956** [comment]
minnit.chat

**Comment by sm64js** [comment]
done
