### ISSUE TITLE
(Suggestion) "Remove Rom" Button

### ISSUE THREAD

**Issue by SQUISHY6094** [sm64js/sm64js#121]
It would just remove the rom you are using just in case you accidentally load up the wrong one.

**Comment by sm64js** [comment]
That is a good idea

**Comment by Whoblue579** [comment]
Sometimes I play at Walmart, and I don't exactly want people using my rom, this would be nice

**Comment by smm2mickeyink** [comment]
> It would just remove the rom you are using just in case you accidentally load up the wrong one.

oh ya i wanted to test the broken sm64 rom thing if it happens

**Comment by sm64js** [comment]
I will try to add this feature tonight.

I added functionality so if the rom is not supported, it will reject the ROM.... so is uploading incorrect roms still an issue?
