### ISSUE TITLE
Restricted

### ISSUE THREAD

**Issue by Vegito69** [sm64js/sm64js#122]
If possible could you make sm64.js on an unrestricted domain such as sites.google.com? i have gotten past the restriction before, but it doesn't last for long, School is blocking everything that is fun, so i have nothing to do when i have time to do whatever. It says its blocked for being non-managed, maybe just moderators that could manage the website, if that isn't possible try to make it on an unrestricted domain like i said previously. Thank you :)

**Comment by sm64js** [comment]
I am interested in making this work, you are saying that sm64js.com is already blocked by some filters?

**Comment by Vegito69** [comment]
yes, but the filters only say its because its non-managed if you'd like, i will send proof via. screenshot

**Comment by Vegito69** [comment]
![Screenshot 2020-11-12 at 14 38 19](https://user-images.githubusercontent.com/74366490/98994746-e3a8a580-24f5-11eb-8a47-09d4e1881fbc.png)

**Comment by Vegito69** [comment]
its also for vanilla.sm64js.com i think u get the idea

**Comment by Tarnadas** [comment]
It looks like your school uses this filter:
https://www.nebo.edu/webfilter

Unfortunately, sites.google.com can only serve static content, so the best thing we could do is hosting a singleplayer version on a CDN.
If you have another idea where we could deploy a backend, please let us know.

**Comment by Vegito69** [comment]
I mean it says its because its non-managed, maybe you could find a way for mods to have different times on when to manage the page?

**Comment by Whoblue579** [comment]
Its unfortunate, but this is not an issue with sm64js.

**Comment by Vegito69** [comment]
The terms and service thing you added fixed it, Thank you, i shall now close this case as it is no longer an issue

**Comment by Cooliokid956** [comment]
good

**Comment by Vegito69** [comment]
again Thanks a lot

**Comment by Vegito69** [comment]
now i can finally enjoy my favorite game once more

**Comment by Vegito69** [comment]
Nevermind, I guess a mod has to be on in order for me to play since they are technically managing it, But still Yay
