### ISSUE TITLE
Mushroom stems in TTM appearing black or grey

### ISSUE THREAD

**Issue by accrev** [sm64js/sm64js#123]
Not sure if this is my ROM or just the server, look at the screenshots below

![](https://i.gyazo.com/ee4a69c7806112e37770de783a5ee7eb.png)

![](https://i.gyazo.com/924fa2ec5ff1fdddc97b3701c0f2dbc7.png)

**Comment by Vegito69** [comment]
I aint an expert on this but, it should get fixed soon, they just haven't put the texture on for that part of the stem yet

**Comment by Vegito69** [comment]
Or, they couldn't find out what to do with it so they just made it black, I can easily find myself getting used to this is it is only a minor issue

**Comment by Whoblue579** [comment]
It was white for me
