### ISSUE TITLE
Void doesn't exist in vanilla.sm64.js

### ISSUE THREAD

**Issue by accrev** [sm64js/sm64js#124]
If you fall it doesn't teleport you back up, forcing you to reset the game.

[Cool, Cool Mountain](https://i.gyazo.com/dc5ff7531a0a629dacb6a46410527c15.mp4)
[Princess's Secret Slide](https://i.gyazo.com/07f2161451b91b85174cc613387669c3.mp4)
[Tall, Tall Mountain](https://i.gyazo.com/b8f1cb51c5573fe8b428dc8181b6dae8.mp4)

**Comment by luphoria** [comment]
Not a bug. Intentionally not implemented, as it is not a vanilla feature to warp.

**Comment by accrev** [comment]
Alright, thanks for telling me.
