### ISSUE TITLE
Play MMO version?

### ISSUE THREAD

**Issue by Knucklehead-McSpazatron** [sm64js/sm64js#127]
Where/how can I play the MMO version?

**Comment by Whoblue579** [comment]
sm64js.com

**Comment by Knucklehead-McSpazatron** [comment]
Thank you, if I were to install and run a copy of this port would it connect to the same servers?

**Comment by Whoblue579** [comment]
You will have to install docker and clone the source code from the MMO fork, the instructions are on the readme

**Comment by Whoblue579** [comment]
I think you can run on official or custom servers

**Comment by Knucklehead-McSpazatron** [comment]
Do I only clone the main "MMO" branch, because there are 4 others that start with "MMO"?

**Comment by Whoblue579** [comment]
The MMO branch, https://github.com/sm64js/sm64js/tree/MMO

**Comment by Knucklehead-McSpazatron** [comment]
Thanks.
