### ISSUE TITLE
Large Unicode characters can obstruct other text

### ISSUE THREAD

**Issue by Whoblue579** [sm64js/sm64js#128]
ỵ̵̧̡̢̡̧̧̨̢̧̢̧̢̨̧̡̧̨̨̧̡̢̨̢̧̛̛̛̛̛͙̤̖̳͓̳͔̱͎͇̺̬̫͖̪̙͖̖̝̣̲̯̘̺͙̱̖͍̫͕̹͈͈̳͚͈͇̙͎̟̞̯͎͕̫͙̖̜̲̪̥͕̺͉͈̣̘͇͓̖̹͍̤̯̳̫̖̻͇̩̣̗̳̙̬͉̮͍̗͈͙͇͇̺̲̣͇̱̥̱̠̜͉̯̮̬͕̦̖͕̪̜͈͕͓͉͉̙̝͈̲͎͙̹̱̩̩͉̳͇̹̠̪̣̞͕̗̝̝̞͙̩̥͙̖̰̣̭͚͖͚̯̪̻̹͙͉̟̬̤̬̼̤͔̤̠̱̫̩͓̼̬̥̬͎͚͔̰̘̟̟̻̟͈̜̦̘̠̣̙͕͍̭͚͓͚̬͈̰̮̲͎̪̪̬̄͌̀͆̏̑̓͋̒̑̏̈͋̒̇̾̈́̉͆̌͐̏̓̈͊́͌̋͆̿̈́̆͋͒̌̐̄͆̍͋̉́̽̎͆͂̒̈̀̈́̋̈͊́͌́̌̾̂͛̂̒̽̎̓̑̑̃̊̈́̋̈͌́̆̃̊̉͐̑̆͗͐͌͑͊̀͂́͒̀̽̔̍̄͊͗̈́͌̂̿͊͊̇͂̇̅͒̅̍̇͆̎̉̈͐̂̎̓͐͑̿̅͌͌͆̈́̈́̊̉̔͂̅̈̀̍͘̕̚̚̕̕͘͜͜͜͜͝͠͝͝͝͠͝͝͝͝͝͝͝ͅͅͅͅͅǫ̶̡̧̨̡̧̢̡̢̡̧̧̢̛̖͕͙̫̦̞̗̬̟͔̻̮̳̹̠̘̤͎̣̖͔̱̻̲̗̞̞͇̜̝͇̬͈̰͔̟̞̬̣̠̪̥̜͓͕̳͚̥̱̳̠̯͍̫̗̥̖̬͖̪͙̟̰̯͕̞͍̯̟͕̠̹̝̰͔͚̗͔̼̭̬̱͖̭̝͈͉̦̹̯͕̝̜̹͎͍̜̥̭̗͕̣͍̻͉̭͈͚͉̹̻̝̗̻̝̰̭̫̺͉̬͓̞̭̱̺͓̮̜̣̜͓̯͇͍̥͉̝͕̤̭̻̬̔͗͊́͗͐̏͒̊̿̅̽͋̐͛͌͆̅̎͒̆̃͛̾̾̽̓͌̂͒̆́͑̒͗͊́̐͊̔̾̀͊̿̌̀̀͌̋̍̉̌̿̔̓̈́̓̈́̍͌̀͌́͑͒͛̀͘̚̕̕͜͜͠͠͝͝ͅͅͅų̴̨̢̡̢̢̨̡̢̨̧̡̡̡̢̨̨̨̡̧̛̛̛̛̛̛̛̛̛̞̲̠̰̰̣̦̝͚͕̲͎͈̗͕̱̘̜̺͎̩̘̪̯̖͈̞̟̹̻̭̠̖̘̜̭͚̰͈̝̘̹͎̦͉̻̖̪̹̤̥̫̹͍̖̼̰̝̱͙̫̰̯͔͔͖̮͚̭͙̜̮͍͉͎̤̮͎̬͍͖͈̤̻͎͍͖̳̮̙̼̺̱͇̫͙̺̹̰̦͕̬̣̖̦̖͉̪̝͙̝̬̩͓̟̘͖̜̹̩̟̯̳͉̫̣͇̮̳̣͍̘̥͖̻̩̯̙͓̝̇́́́̿͒́̃͛̈̃͗̍̽̃̍͂͑́̍͂̌̈́̈́̓̒̂͊̈̓̅̐̄̈̀̊̉̃̿͂̄̏͆̓͋͛̏͌̽̅̓̈́̑̄͒̓͂͗̿̊̑́͂̎̍͐̿͌̍̏̉̀͊̋̂͐͆̏̓͆͊͋̂̽͆̏̓̈́̌͂̀̾̔͗͋̄͊̓͌́͐͆̃̿̈̏̏̈́̎̅̾́͛̊̄̏́͛̒̌̈͊̏̏̓̽̂͆̈̏̌̈́͂̊̐̓̉̌̏͊̑́͋͆̾̽͛̐̐̒̾̽̿̀̋͊̏̓́̈́͌̎̄̓̆̄͌̃̋̔͋̒̄͌͗̈́̄̈́̆̈́̏̆̇̋̽̂͛̽͑̋̕̕͘̕̚͘͘͘̚̕̕̚̚̕̕͜͝͝͠͝͝͠͝ͅͅͅͅͅ ̵̨̢̨̢̨̛̛̛̛̛̣̺̖̻̮͓̤̫͇̰̫͔̜̗͍̘̳̟͓̬̗͓̙͉͎̺̖̤͚̼͇̰̰̳̘̯͉̞̟̲̥̯͇̯̬̼̝̙̦̫̺͉̰̠̦͖͒͛̄̍̈́́̓̈͒̑̒̂͗͒̌̂̈͗͐͊̔̓͆̑̽̔̀̓̅̒̂̇͆͑̓̏̔̿̽̓̑̇̅̋̈́̈́̀͐͐̾̑͋̈́̈́̅̈́̅̐̔̿̎͌͆̒̓̈́͗̐̇͑͆̽̏͐͌̍́̊͋̇̋́̈́̓̓̎̄͐̑̒͌͌̈́͂̂͋͗̈͌̃͛͒͌̓̌̇͂̌̅̈́̓̇̋̔͗͊̌͌̃͆̽̀̎́̐̾̋̽͆́̏̂͊́̽͆́̎͌̈́̓́͗̎͐͂̇̾̇̎̿͆̾̏̀͂̉̈̓͗̊͊̎̽̈́͊̍̋̅͆͒̑̃͌̌͛̀̓̄̄͊̈́̌̓͐̈̀̒͐̋̈͌̿̉͛̉̇̉́͑͋͐̋̓̎̑̒̀́̉͑͐̃͑̕͘̕͘̕͘̚̚̕̕͘͘̚̚͘̚͝͠͠͝͝͝ͅͅç̸̧̧̧̨̢̛̛̛̛̛̛͚̗͉̯̼̣̪̣̘͕̘͉͚͇͍̞̖̱̗̦̯̣̝̦͙̠̫̞͖͇̫̤̘̥͓̪̪̼̖̻͙̞͔̝̫̰̱͓̖̹̻̗̮̫̻̱̜̜̞̘̺̫̰̖̍͒̓̉̀͗̂͛͋́̈́͊͋̓̂̌͆̓̅͛̆̔͑̇̋͗̐̏͒̾̑̃̊͑͑̈̈̾̀̓̈́̓͛̇̆͌̏͂͒̆̀́͒̈͑͒̋́̈́̒̍͂̽̊̈́̆̈́̈́̍̉͊͗̏̆̋̈́̓̏́̎̋̓͆̈́͆̐̀̂̅̌̓̔́̅̑̆̋͂̓͊͛̽̊͋̌̀̑̎͗̄̀̀̈́̉̅͗̑̌͂͒̅̌͂͊͊̐̆͌̅̈́̊̅̌̃͂̓̏̋̓̔͊̄̐͆̄̾͑̉̑͐͒̿̈̃̈́͗́̊̇̌͒̄̄̊͋̿͊̉͐̈̔͑̂̈̆̅̔̓̃̀͋͐̂̒̓̇̔̄̀̓̈́̿̏̽̃̇̄̑̈́̈́̇̀̿̃̽̊̾̈͑͛̾͑̈́̉͛̏͆̀̓͋̋̈́̅͂̇̐̈̈̽̈̀̽̅͑̓͊̀́̑͒́̄̕̚̚̕͘͘̕͘̕̚̚̚͘̚̚̚̚̚͘̕͜͜͝͝͝͝͝͠͝͝͝͝͝͝͠͝͝͠͝͝͝͝͠͝͠͝͝a̷̡̨̨̢̡̨̧̡̢̡̢̢̢̢̢̧̧̡̨̢̢̧̢̛̲͉͍̫̖̺̼̳͔̻̲͎̼̲̤̖͇̜̪̦͕̥̥͓̰̳̯̳͖̙̪̥̮͙̳̭̥̯͈̣̥͉̮̟̝̼͔̱̦̦̬̱͙͖̝̱̟̼̝͉͈͍͈̮͖̼͎̦̦̼̥͇̮̼̞͔̥̣̱̺̹̭̘͔͓͇̣̲̫͎̰͉͓̥̰̜̼̩͓̮̼̼̮̹͎̗̩̳̙̭̞̳̝̝̥̦̞̲̥͕̣͚̼̭̠̗̟̲͇̬̝̳͈̬͈̠͖̺̰̙̖̺̰̪͍̖̘̥͍̳͓̦̻̦̻̜̮̣͖͈͕͓̪̠͉̤͚̱͇͎̬̬̭͚͉͓̹̫̗͙͔̟͈̜͍̘͕͇̖̙͍͉͎̻̬̗̬̭͇͍̗̥̥̮͈͙͓̣̩̱̹͍̲̪̩̟̤͚̠̲̘̬͍̜͍̯̤̪̞̣̮̥͙͕͇͇̹͙̹̦̬̺̖̘͈̙̯̖̟͎̘͇̠̗͍̗̭̠͗̊͋͂̊̃̃̀̍̏̅͑̿̽̉̋͋̇́̋͂͒̐͋͊̎͊̀̉̓̏͛͌̆̋͛͋̌͑̀̔͗̀̋͂̐͗̾̆̅͘̚̚̕̚̚͜͜͝͠͠͝͝ͅņ̸̨̧̢̢̨̧̧̡̡̢̡̛̝̦͎̝͙̱͚͖̺̳̠̺͓͈̤͓͔͚̙̪̳̗̫̤͉͍̳͖̤̬̙̜͕̠̳̣͙͚̜͔̬͙̠͔̩͚̦̙̞̺̖̟̝̰̯̲͚͕̮̰͓̖͖͕̤͙͈̻͓̺̟̹̲̞̻͓̬̱̜̥̟̬̙̺̗͙͚̳̼̭̹̞̫̰͚͓͇̟̻̻͔̼̥͖̯͕̞͙̯̦̟̼̯̰̰͇̳͕͔̘̖̮̺̟̻̠̪̘̲̰̗̯̠̙͖͔͍͉̪̗͍̘̤͔͉͎̜͇̞̜̫̼̜̞̰͓̬̩̼̜̜̰͇̔͂́̆̐̅̍̂̓͋̈̔̀͒̏̆̓̂̅̾͊̅̈́̌̐̽̀̒̊̀͋͐̀̕͜͝ͅͅͅͅͅ ̵̨̨̧̢̧̧̡̡̧̢̧̡̧̧̧̨̨̡̨̢̛̛̛̛̛̻̭͍̟̤͕̦͕͚̰̩͓͉̰̻̖̦̤̹̗̟̘̖̣̪͔̫̦̙̠̠͔̻͉͉̩̼̜̝̤̗̩̣͎̱͈͉̼̺̤̗͈̘̮͖̘̳͚͉̜̜̝̦͓̳̜͉͇̣̼̞̰̗͎̪͙͔̯̤̦̲͖̪̞͚͉͓̪̝̝̘̥̰̬̖̭̪̫̳͉͈̩̹̣̰̗̳̯̜͕̳̺̟͎̦̙̥̜͓̼̖̞̜̬̻̜̘̟͚͇̲͇͚̣̰͉͇̙̮͇͎̯͕͇̖͖̺̙̞̼̝̤̦̦̹̰̖̥̻͚̳̤̲͖͚̼̻͎̪̖͉̫͖̘̹̹̤͚̱̭̖͍̖͔̼̺͚̙̙̳͍̩̀͆̓̎̓̄̉̎̿̅̑́͋̆͛̀͊̆͂̑̄́̈́̒̾̍͊͐̾̑̊̽͌̇̋͗͐͊̊̓͛̿̆̈́́͗̈̇̑̔͒̓̆͋̌̾͑̄͌̆̇̈́̇̋͑͋̒̏̈́͛̅́̈͑͐͗́̑̔̓͗̒͐̅̽̀̈́̽̾̽̈͛̈́̽̑͛̾́̏̓̉̆̂̒̔̈͛̈̎̇̐̊̅͊͋̄̅̉̾̐̈́͒̄̍́̔͋̃͆̿̇͗̇̈́̚̚͘̕͘̚̕̕̕̚͘͘̕̚͘̚͜͜͜͝͠͠͠͝͝͠͝͠͝͠͠͝͝ͅͅd̵̘̳͕̝̤̼̙̖̉̒̇͗͌͂̆͑̃͌̀̃̿̌͋̀̊͌́̄̎̈́͐̿͊̉́͛̓͛͗͊̅̂̔̿͋́̈́͂͌̈̽̉́̀̂͛̀͐̈́̋͛͘̕̚͝͝͝͠ͅǫ̴̢̡̡̧̧̢̧̢̢̡̡̨̧̢̨̛̛̘̬͎̼̥̻̯̲͈̯̞͎̣̝͎̖͎̜̟̺̯̲͖̥̜̖̱̯̯͚̭͕͕̱̙̘̲̮̘͈̖̮̯̝͖͍̪̪͇̫̖͈̞̖͎̥̹̬̙̱͕̥̠̻̥̹̬̳̞̼̻͍̜̖͉̦̼̪̮̩̯̪̦͕͓͙̪̜̳͕̟̘̟̭̪͇̲̥͔͓̙̙̯̬̦̝̣̠̦̮͚̥̥̯̠̲͔̪̘̺̩̰̯͕̘̥̖̬̰̺̺͕̯͙̼̞͎̝͍̮͔̼̝̮̬̭̪̹̠͈̟̳̤̬͇̬͍͍̞̹̞̺̥̟̦̭̝̫͈̼̙͎̘̩͈͖͋̊̌̀̎̋̔̿̀̈́̅̍̔̓̊̈́͗̅͗́̅̓́̈̈̊̇̉̅̇̇̀͊͊̂̒̇͆̇̌̆̂̉̉̓͑͊̇͊̑́̈́̐̐͘̚͜͜͜͠͝͝͠͝͠͝ͅͅ ̴̡̢̨̧̨̢̨̢̡̡̢̡̢̡̨̡̢̧̡̨̧̢̡̨̧̢̛̛̛̛̛̛̛̱̝̼̰̟͇̥̬͓̹͕͇̻̤͕͉̠̥̬̳̖̗̮͚͚̲͔̟̖̟̬̳̻̭̪͇͚̙͖͔̻̘̥͍̠͎̺̻̤̯̭͙̳̞͈̦̥͈͈̹̟̪͓͍̼̞͉͙̻̲͕̦͇͈͇̳͍̼͔̙͈͎͓̙̼̜͖̩̜̻̣͎͈̰̟̼̗̦̠̮̳̹̳̭̥͖͕̤̪̻̞̩̖̫̭͔͍̳̺̻͇̳͓͕̲̩̭̥̳̜͍͙̫͕͚̠̯̯̖̜̭͈͉͈̥̞̲͖͚̣̖͓̱̞̣̰̭͔͔̹͍͍̦̩͕̲̘̹͖̪̻̫͙̳̣̳̦̼͔͖̗̰̞̲̮̘͍̘͍͎̦̻̥̠͙͙̪̫̺̦̭͕̭̤̱̟̘͇̗̟͉̣̠̗͚͉͓̰͔̟̫̺̬͍̲͚̜̯̟̯̻͚̩̩̹̟͉͇͓̺̺̼̙͈͍̺͈̠̙̞̘̠̩͎̖̞̱̞͓͔̩͋͗̊̏͂̿̑̈́̊̈̆̉͐͂͐͋̏̈́̄̀͒̋̑̄̈̐̽̌̅̀̐̿̊͆͋̊̄̆̊̌̉̌͆͒̾̽̌͊̈́̔̅̑̾̊̋̉͆̈̉̽̒̂̔̽́̃͆̓̓͊̍̎̀͑̅̾́̓̈́̄̑͑̂̂̉̈́̔͗̌̇͌͗̀̉̅̊̐͌̄͛̏̽͒̔͗͗͛̂̽̆́́̅́̋͑̋̎̊̂̈́̏͒̌̾̆͆̉́̃̆̍͋̃̑̀́̔̽̿̒͐̂̈́̒̐̽̽͆̐̋́̃́͌̓̍̌̈́̇̄̂̄͂̆̈́͌̈́̐̊̿͋́̔̈̎̌̄͌͛͛̿̏̊͂̅̆͛̽̉̌͛̈́̋̓̂̿̓̽̉̀̂̒͑̎͛̍̈́̂̒͛̓̔͂͛̏̅̉͘̚̚̕͘̚̚̕̕̚͘̚̚̚̚͜͜͜͜͜͝͝͝͝͝͝͝͠͠͝͝͝͝͝͝͝͝͝ͅͅͅͅt̴̨̨̨̢̨̢̨̨̢̨̢̨̧̢̡̧̢̨̢̢̧̡̡̨̡̡̧̢̨̡̨̡̡̛̛̛̛̝̖̞͓̲̳̤̖̣̙̱̳̲̯̺͚̰̪͙͉̪̳̫͙͍̘̜͔̤̙͍̰̻̻̦̣̞̺̹̝̦̘̣̠̣̫͚͍̮͚͚̙̹͍̫̥͎͉̥̥͔̱͕͚͎͇̜̩͚͕̞̰͕̥͖̲̺̝͖̭͓̹̦̲̫͍̪͎̙͎̱͔̤͚͈͔̝̫̙̜͔̩̥͙͙̬̩̩̟̲̤̤̦̬̩̖̺̙̺̠͙̻̮̮̻͇̥̖̼̼͙̝̟̬̦̰̹̻̥̥͈̘̱̦̠͍̮͍̹͖̤͓̼̰̯̝̩̭̺͙͔̫̣̲̣͙͓̦͓͙̘̳̫͙͖̻̩͔͎̼̹͔̺̮͉̖̮̜̮̙̮͚͕̙̖̗̠͚̰̜̣̬͚̤̝̥͇͍̯̤̫͕̯̩̗͓͕̠͓͖͎͎̤̗͓̬̟͈̩͕͑̈͊͛̌̀̀̈́̃͒̂́̌͋̇̑͗͆̑͋̔͛͑̎̆̉̓͑̎́̅̔̈́͛̏̽̄́͗͆̈́̋̍͛̓͑̓͋̑̽̓͂͗̽̅́̀͐̆̑̔̀̄̾̍̋̉͊͑͑͐̉̂͆̐̈́̿̆̃́̿̌̐́͐́̒̎͋̄͗̌͂̏͗̎̑̾̆͛́̆͐̊̐̀́̓̆͑̃̽̃̍̓̽̇̄̏̒́̓͒̐̇̽͑͋̉̿̅͐̉̍̿͌͑͛̆̀̍̈́͂̋͒̉͂̅͆̀͒̓̅̂͊̍̇́̉̾̌̍̄̿͂͛̃̋́̕͘̕͘̚̕̕̕͜͜͜͜͜͜͜͜͝͠͝͝͠͠͝͝͝͝͝͝͝͝͝ͅͅͅͅͅͅͅͅͅh̷̢̡̢̨̡̡̨̡̧̨̢̡̧̡̛̛̛͖͕̬͓̭̬̼͉̩̥̤̰̞̱̣̝̳̩̜͖̰̰͎͓̗̤̤̙̻̜̣͈̼̲̣̞̝̩͎̱̥̭͖͙̝̝̙̼̭͙͉̱̟͍͈̜̲̤̬͚̦͓̘͈͍̳̫͇̫̥̱͔̖͎̳͔́̈̏̐͑̿̆̾̅͐̄̓͌̇̄͌͂̌́͌̓̔̆̿̐͋͛̅̿̔̑̍͆͗̔̍̾̋͊͋͑̄̈́͊̂̈́͌̅̿̐̋̀̽̅́̄́̽́̍̒̒͊̊́͂̔͋͒̈́̅̑̽͌̂̀̎̀̓̍͛̈́́̊̀́̒͑̔̈́̈́̇͒̀̄̍͆̓̅͒̿̎́͊̾̄̉͆́͂̓̄̃́̾͋̓̃̓́̓̀́̍͑̈̋̓͑̽̀͗̃̆̂̒̐́͋́́̓̔̋̈́̀̌̑̈̐͛̈́͛͂̚͘̚͘͘̕̕̚̚̕͘͘͜͠͠͝͠͠͝͝͝͝͠͝͝͠͝͠͝͝͝͝͠͠͝ͅi̷̢̨̢̨̢̧̧̡̢̡̨̛̛͕̤̠̗̼̭̩̝͓̞̺̲͇̣̜̪͚̫̟̬͚͉͇̰̩̭̣̪͉̻̤̣̘̰̝͈͚̭̯̝̞̯̬̗͍͓̰̺̖̯͇̲̻͔̗̦̳͈̥̥̭̮͚̭͔̼͖̦̠͔̳̤̘̰͈̟̦̝̜̝̭̲͕̺̩͈̲͓͚̙̞͕̯̫̼̟̞̗̗̗̯͖͖̬̰̲̲̖͐̌̄̈̑̓͌̀̽̔̽̐̋̏̾͛̃̽͛̓͐͑̀̆̿͆̍͗͂͌͆̍͊̈́̋̄̆͂̊͂͊̑̎̋͑͆̋͋͒̈́͊̍́̄̈́͒̉͛̃̋͌̋̔̀͌͑́̑̊͗̌̓͗͛͗̒̀̽̈́͆͛̒̃͛͆̀̂̇͛̇͊̓̈́̒̑̀̉̐̚̕̕͘̕̚͘̚͘͘͘̕̕͜͜͜͜͝͝͠͠͝͠͝͝ͅͅͅŝ̵̨̨̛̻̪̫̫̱͓͈͓̱̠̝̣̻̠͙͍͎̦̯̼̪̘̙̹̣͕̫̫̫̥̣͓͓̥̭͚̞̤̖͖̝̘̐̈́̌͑̆̈́̽̋̈̔̽̽́̽̉̉̉̒̐͆̇̋̐͑̀̑̄͐̐̔̑̿͐̔̇̄̃́͊͑͊͂̽̄̿̎͒̈́͑̅̈́̇͑̈́̇͑̀̐̓̿̉̽̃͊͆͋̿̏̍̀̃̀̍͊̄̔̂̈͆̽̈́͊͒̇̀̈̈͒̊̅͆̅̋̾̄̀̓́͆̕͘͘̕̚̚̕͜͠͝͠͝͝͝͠

**Comment by Whoblue579** [comment]
**I should report this issue on GitHub too** I guess

**Comment by Whoblue579** [comment]
also, to clarify, I mean in the chat

**Comment by Cooliokid956** [comment]
its called zalgo text, and yes, it is annoying

**Comment by sm64js** [comment]
Thanks, I think I have a PR for a fix for this.
