### ISSUE TITLE
(Suggestion) Add support for more ROM formats (.n64 and .v64)

### ISSUE THREAD

**Issue by Knucklehead-McSpazatron** [sm64js/sm64js#129]
(See title)

**Comment by sm64js** [comment]
why is this necessary?

**Comment by Knucklehead-McSpazatron** [comment]
Because different people have different ROM formats. It's a little obvious, no offense.

**Comment by GlitchyPSIX** [comment]
Using a tool like Tool64 you can change the format of your ROM.

Not to mention that having a format for SM64 that is different from z64 would imply you got your ROM from a... questionable source.

**Comment by sm64js** [comment]
> Because different people have different ROM formats. It's a little obvious, no offense.

Thanks for the input. I think it's not that big of an ask to to require users to get the correct ROM type.  I will consider adding compatibility for this however.

**Comment by AgentXLP** [comment]
Seems quite redundant and a waste of time to work on honestly. Not even decomp or PC port take in n64 or other foreign ROM files.
