### ISSUE TITLE
(Suggestion) Add the option to censor/uncensor the chat

### ISSUE THREAD

**Issue by accrev** [sm64js/sm64js#130]
Would be useful for people to properly read the chat.

**Comment by sm64js** [comment]
will consider

**Comment by github10omar** [comment]
j

**Comment by github10omar** [comment]
ok i mean thats needed

**Comment by justabluemouse** [comment]
Yeah, I really do hope this becomes an option. Literally saying "grass" comes out as "gr***". Along with other flaws. As much as I appreciate the strict censoring system, it CAN get a little annoying/inconvenient sometimes. Hopefully, that'll be added in the next update. 😀

**Comment by AgentXLP** [comment]
fixed
