### ISSUE TITLE
Color Code from gameshark wont save

### ISSUE THREAD

**Issue by pokycraftgamer9** [sm64js/sm64js#132]

**Comment by sm64js** [comment]
I don't know what you mean? Gameshark?

**Comment by pokycraftgamer9** [comment]
> I don't know what you mean? Gameshark?
The paste color code doesnt save it

**Comment by KLanausse** [comment]
the only cheats That I can see working would maybe be texture ones
sm64js just uses the rom to get the textures

**Comment by sm64js** [comment]
I am not familiar with game shark codes. But think it is same to assume sm64js is not compatible with them.
