### ISSUE TITLE
Two hackers are floating

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#135]
ban these hackers permanently quick!! here's the usernames: Luigistealer and games5 [Modder]

**Comment by Sasytoremember** [comment]
its mods not a hacker >:(

**Comment by KLanausse** [comment]
uh they were just using custom emotes

**Comment by smm2mickeyink** [comment]
> its mods not a hacker >:(

oh

**Comment by Cooliokid956** [comment]
please calm down
there is a specific way to allow people to use mods on the main server, so whoever they were, they knew what to do (they were basically given permission to mod)
