### ISSUE TITLE
Make it so when i open a new tab sm64js wont go offline

### ISSUE THREAD

**Issue by FallGuy308** [sm64js/sm64js#136]
its really stupid and i hate it please fix!

**Comment by Kevin-Is-Nice** [comment]
agreed

**Comment by Tarnadas** [comment]
It's a browser limitation, which will automatically throttle timers, when the tab is no longer active.
It can be circumvented by using Web Workers, but that would mean, that the main loop of the game would no longer run on the main thread.

You can however disable the background throttling yourself by doing this:
https://www.reddit.com/r/incremental_games/comments/jefviz/fyi_how_to_disable_timer_throttling_on_google/

**Comment by sm64js** [comment]
I am sorry I know this is a very annoying issue. There is not an easy fix without negatively affecting the game experience for other online players. Long term however, I'd like to solve this.

**Comment by AgentXLP** [comment]
Just do what Tarnadas said
