### ISSUE TITLE
annoying people

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#138]
![image](https://user-images.githubusercontent.com/74847773/99894532-15f89680-2c9e-11eb-9c1b-71fdf7fefc68.png)
these people are annoying and bad. please do something to block this link

**Comment by luphoria** [comment]
There is currently nothing we can do (but we're working on it). For now just put their name into Block Player Chats

**Comment by github10omar** [comment]
ok

**Comment by github10omar** [comment]
there are so many of them it's impossible to block all so that's why i made this
make an option to block 2 or more ppl simontaniously and server list to see
make it easy

**Comment by github10omar** [comment]
they are still there, currently lagging server. please look at the issue

**Comment by sm64js** [comment]
We are working making moderation tools to handle this.
