### ISSUE TITLE
pervert "metalsmash117" making porn of my oc

### ISSUE THREAD

**Issue by Sasytoremember** [sm64js/sm64js#140]
ban him.

**Comment by Sasytoremember** [comment]
he may rename himself to metalsmash118 or metalsmash119, metalsmash120, metalsmash116, metalsmash115, etc.

**Comment by KLanausse** [comment]
what the fuck

**Comment by GlitchyPSIX** [comment]
This is not an issue that pertains to the game's workings. This is a different issue that should be handled differently and not by us.

**Comment by github10omar** [comment]
Yeah

**Comment by sm64js** [comment]
Moderation tools are being implemented
