### ISSUE TITLE
Slowdown

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#142]
When I use Chrome, the game lags in vanilla and then the MMO one also, but on Edge it runs on 50-60 fps. This is what it said:
![image](https://user-images.githubusercontent.com/74847773/99950039-630b6400-2d95-11eb-97af-9367359106e4.png)
![image](https://user-images.githubusercontent.com/74847773/99950060-6999db80-2d95-11eb-892e-9be59f05969b.png)
![image](https://user-images.githubusercontent.com/74847773/99950082-6f8fbc80-2d95-11eb-843b-749d0f08fe74.png)Not only this, but it can go down to 27 fps, which is suprising that it slows down. I played SRB2 web on 20 fps, and was like normal SRB2. But lord, this lags so much. Vey rarely does Edge also slow down at 16 players. Using a Intel i5 laptop, made by HP.
May just  be my computer.

**Comment by sm64js** [comment]
This is strange, but I'd like to know more.  can you confirm if you play on vanilla on edge and chrome. that fps is better on edge?

**Comment by github10omar** [comment]
FPS is better than Chrome on Vanilla.

**Comment by github10omar** [comment]
Vanilla runs smoother for 50-60 fps and also MMO, experience lag rarely

**Comment by github10omar** [comment]
Tried Vanilla on Chrome, it's fine but on MMO it just lags a lot. Hmmm... Intresting.

**Comment by github10omar** [comment]
[bandicam 2020-11-25 09-00-15-212.zip](https://github.com/sm64js/sm64js/files/5594508/bandicam.2020-11-25.09-00-15-212.zip)
Please look at the following footage.

**Comment by github10omar** [comment]
Oops, left my webcam on. Sorry!

**Comment by github10omar** [comment]
This issue does not happen anymore. Sorry!
