### ISSUE TITLE
Sonic Low Poly (file for charachter changer thingy coming up) (may come)

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#145]
[Sonic The Hedgehog.zip](https://github.com/sm64js/sm64js/files/5600680/Sonic.The.Hedgehog.zip)
this may be low poly, tell me if not
anyways this is one i found after hard work so it can be added as a charachter on the charachter chnger (it's not made till yet)

**Comment by TERRAERROR** [comment]
There's no character changer and I doubt there will be for a while, though once tools are finished for stuff like this I'll look into trying to make one.

If it ever does get made don't count on this model being put in. (Big *if*)

**Comment by github10omar** [comment]
k, thanks!

**Comment by github10omar** [comment]
update: new file which is classic sonic with textures
[Custom Edited - Sonic the Hedgehog Customs - Sonic Classic Low-Poly.zip](https://github.com/sm64js/sm64js/files/5610089/Custom.Edited.-.Sonic.the.Hedgehog.Customs.-.Sonic.Classic.Low-Poly.zip)
got it from modlers resource, not the sonic mania model

**Comment by github10omar** [comment]
first you can do anything, optional to add.

**Comment by Someone567123** [comment]
sonic
