### ISSUE TITLE
slope giltch

### ISSUE THREAD

**Issue by MasterNama2008** [sm64js/sm64js#148]
I found the video here: https://youtu.be/Uwg1A39tyH8

**Comment by sm64js** [comment]
thanks, yea I tried fixing this once, but it didn't figure out why it is happening.
I'll leave this issue open as a reminder to investigate

**Comment by smm2mickeyink** [comment]
> thanks, yea I tried fixing this once, but it didn't figure out why it is happening.
> I'll leave this issue open as a reminder to investigate

in the original game you can use walls to climb up slopes in bom omb battlefield... that part is normal so its a tech
