### ISSUE TITLE
PS4 controller buttons don’t work and no my buttons work fine on my PS4

### ISSUE THREAD

**Issue by bruheme** [sm64js/sm64js#150]

**Comment by github10omar** [comment]
strange, it worked for me. use a usb cable like the one to charge the controller to pc, works.

**Comment by bruheme** [comment]
I play on iPad with keyboard and it has no USB port

**Comment by github10omar** [comment]
oh. put a usb converter cable then, it's for 5 bucks on stores

**Comment by bruheme** [comment]
Thanks for the tip!

**Comment by github10omar** [comment]
Welcome!

**Comment by Meowlithius** [comment]
Hold the share and PS button to turn on pairing mode to your DS4.

**Comment by bruheme** [comment]
I did that
