### ISSUE TITLE
(Suggestion) Crouching/Crawling hides Nametag

### ISSUE THREAD

**Issue by SQUISHY6094** [sm64js/sm64js#151]
Just a little minecraft like feature that allows players to properly play hide and seek without having to try and change their username to an invisible character.

The code could be tied to the Z button input and would hide the users name when the button is pressed.

**Comment by Bloxxel64** [comment]
that could work. I have to see if I can find the rendering code for name tags

**Comment by Someone567123** [comment]
mincecrafdt

**Comment by RepeatGitHub** [comment]
I actually think this could be interesting!

**Comment by g3-geo** [comment]
sm64craftjs
