### ISSUE TITLE
User "Jodeil" is a pedophile 

### ISSUE THREAD

**Issue by SQUISHY6094** [sm64js/sm64js#152]
User "Jodeil" was claimed to be a pedophile by User "gaybowser"

Jodeil Also said:
"I'm going to whip you like your dad did"

Other information about the issue:
Jodeil says that they are 18 years old
gaybowser says that they are 16 years old

**Comment by github10omar** [comment]
ok,they will be fixin' this

**Comment by Cooliokid956** [comment]
Okie dokie then, let them live their life that way, and expect more of this. This is not a game for kids.

**Comment by github10omar** [comment]
kids play it

**Comment by sm64js** [comment]
best place to report violations is at the discord server.  and if you do report something we need to know the exact time when it happened to investigate
