### ISSUE TITLE
Chat problem

### ISSUE THREAD

**Issue by ThePlumberFan** [sm64js/sm64js#155]
I have a problem with the chat. Whenever I hit enter typing something to chat to somebody, nothing happens. Why does this happen? Please respond, Thank you.

**Comment by sm64js** [comment]
is this problem resolved? you must be connected to the game.

I will close this issue unless I hear otherwise

**Comment by ThePlumberFan** [comment]
Oh yes, I think it has been already resolved. Because I tried it and now it works fine like as it was supposed to be normally.

**Comment by luphoria** [comment]
can we close this issue @sm64js
