### ISSUE TITLE
Blj too fast makes you get stuck in nothing while holding down and then the game crashes/freezes

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#159]
i blj'd in the easy blj spot where sm64js castle is at. i blj'd held down like you do in a castle blj for a speedrun or something but i did hold down i got stuck and then the game froze. here is the vid link it's still preparing to be proccessed but wait till its done the vid will not be watchable yet: https://youtu.be/zmW-Kfvapoc

**Comment by AgentXLP** [comment]
Seems like an overflow

**Comment by AgentXLP** [comment]
Could just globally cap it to something high
