### ISSUE TITLE
(Suggestion) Add Chat Button

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#16]
Like many other games, this should have a mappable button for chatting so that people can simply start typing with a button (Preferably T, but as I said, mappable, as in able to change), also, you should make it so that is the player is typing something, the game should stop detecting inputs for movement so that you don't move while typing.
Also, the game's chat should also be on a sidebar so anyone can see something even if it doesn't fit on the screen.

**Comment by sm64js** [comment]
Agreed, will add this feature

**Comment by Cooliokid956** [comment]
was never added lol

**Comment by justabluemouse** [comment]
> was never added lol

and yet, here we are, being able to type "joe mama" into the chat for everyone to see

**Comment by AgentXLP** [comment]
was added lol
