### ISSUE TITLE
Bullies

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#160]
![image](https://user-images.githubusercontent.com/74847773/100535426-3bebe100-3232-11eb-81aa-d43344325a74.png)
please make them stop. i asked them to tell me how they were doing animations which was not there, bullied me :(
fix those ppl

**Comment by github10omar** [comment]
Please

**Comment by sm64js** [comment]
I am sorry you were bullied,  best place to report rule breaking is at discord server under #report-spam channel.

From this text log, here I don't know the exact time this happened, and also I don't see enough in these messages to warrant a ban.

**Comment by github10omar** [comment]
i am too young for discoed so i cannot. i can only use hangouts
