### ISSUE TITLE
Game keeps crashing when i want to open the taunt wheel

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#164]
Help!!

**Comment by sm64js** [comment]
when it crashes do you have an error in the console?

**Comment by smm2mickeyink** [comment]
> when it crashes do you have an error in the console?

well it finally stopped the admin said that the thing for the game or something overloaded somehow

**Comment by luphoria** [comment]
This was because of the server deciding to go a bit crazy with served files when it was overloaded. It crashes when the image doesn't load
