### ISSUE TITLE
I CAN'T GET IN THE FUCKING GAME. AAAAAHHHHHHHHHHHH THIS HAS HAPPENED SINCE THE NEW UPDATE

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#165]
well, at the same time, i think it's my fault because i was "spamming" my instagram account. Spamming isn't allowed and could result in a warning, but I really don't think it's that problem. Let me try to explain this while I shit my pants.

After the update, everyone got kicked out of the server. I don't think anyone is trying to impersonate me. My username is pretty stupid, so yeh. Anyways, I tried to get in the game, i clicked on the submit button, and everything went smoothly, tho I wasn't connected to the server for some reason, despite having my WiFi turned on. I thought that was weird, because I didn't spawn in the new map, I spawned in B-oB. Again, it said i wasn't connected to the server. Not even by starting up the game, let's me know how many players are online nor it shows green text. Choosing my username isn't possible, because clicking the green submit button does not make it jump. Pressing "enter" or the space bar makes it jump and recoil, but the box containing my username is outline with red, and the "Waiting for name" text is now red. Again, this problem has been occurring since the new update launched, and i'm pretty bored honestly. I think I'm missing out on alot and stuff. PLEASe fix this as soon as you can. you probably have never encountered this error before.

I think I may have accidentally been IP banned because it just won't let me in. I tried to explain it the best I could on Discord, but NONE of the suggestions worked.

Contact me for more shit i guess.
Gmail: atb111307@gmail.com

**Comment by Someone567123** [comment]
@snuffysasa help.

**Comment by ObsidianPlague** [comment]
> 
> 
> well, at the same time, i think it's my fault because i was "spamming" my instagram account.

[Aha, here's the problem,](https://www.youtube.com/watch?v=TBWwgBen4uI)

**Comment by luphoria** [comment]
you were banned on purpose

**Comment by Someone567123** [comment]
Epic. It was fun tho. I enjoyed ur project, and it was cool to see what JS
could do with it.

**Comment by luphoria** [comment]
I do think that it is a fair issue to say that banned people aren't given a clear message that they are banned. I could try making one later (if someone else does, I imagine pointing them to vanilla sm64js is a good idea).

**Comment by Someone567123** [comment]
Yeah I really don't want to say that if I got perm banned or if i just got
banned for a specific time, but I think it wasn't fair since I wasn't
notified. I think a fair punishment would be like, a ban for like 3 days,
and after that, a warning.
