### ISSUE TITLE
Problem, Marios invisible

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#166]
![image](https://user-images.githubusercontent.com/74847773/100580004-99e5fa80-32fe-11eb-9e79-bc715baf55db.png)
this is the error

**Comment by github10omar** [comment]
![Uploading image.png…]()

**Comment by github10omar** [comment]
invisible

**Comment by github10omar** [comment]
![image](https://user-images.githubusercontent.com/74847773/100580407-4aec9500-32ff-11eb-9b8b-bcafd2c7227f.png)

**Comment by sm64js** [comment]
in this screenshot.. there could just be a Mario below you.

**Comment by JacksTheGreat** [comment]
Im also having this issue!

**Comment by github10omar** [comment]
happy last year to this
