### ISSUE TITLE
Wiimote doesn't work

### ISSUE THREAD

**Issue by lokj123** [sm64js/sm64js#169]
So I tried connecting my wiimote to my Mac and sm64js recognised it, but I couldn't use any buttons.

**Comment by sm64js** [comment]
this work?
https://gamepad-tester.com/

**Comment by AgentXLP** [comment]
Try connecting a controller adapter, a Wiimote by itself isn't too good for something like sm64js

**Comment by ghost** [comment]
Wiimotes are not HID input devices, or at least, not the type a standard computer would recognize, so you shouldn't expect it to work without some other compatibility layer. It does not make sense to add Wiimote support and I do not think it is possible either, as you need low level Bluetooth access to do that.

**Comment by eros71-dev** [comment]
You most likely will need an special driver for the wiimote @lokj123 . Maybe try this out? https://www.julianloehr.de/educational-work/hid-wiimote/ (Might not work I haven't tried it myself)
