### ISSUE TITLE
Chat censors random words like "cool" and "dont"

### ISSUE THREAD

**Issue by GeekyT69** [sm64js/sm64js#17]
[Screen Recording 2020-09-10 at 3.37.48 PM.zip](https://github.com/sm64js/sm64js/files/5201598/Screen.Recording.2020-09-10.at.3.37.48.PM.zip)

**Comment by GeekyT69** [comment]
![Screenshot 2020-09-10 at 3 41 38 PM](https://user-images.githubusercontent.com/56800674/92729287-c8e17580-f37a-11ea-8791-b65848dad9dd.png)

**Comment by sm64js** [comment]
Thank you, I fixed this glitch, however, after that I decided to remove the filter all together for now.
