### ISSUE TITLE
Stuck under peach's secret slide

### ISSUE THREAD

**Issue by FaterSteve** [sm64js/sm64js#170]
There does not appear to be a death plane underneath the secret slide level. This allows players to be stuck underneath walking  on the void until they reload the rom. This can be replicated by falling or jumping off of the slide.

**Comment by sm64js** [comment]
some people asked me to leave it like this for a while... because they liked it

**Comment by FaterSteve** [comment]
That's fine, but could a way to escape possibly be added? Maybe one of the parachute launch pads?
