### ISSUE TITLE
i have quite a few

### ISSUE THREAD

**Issue by Teo221** [sm64js/sm64js#176]
1- name won't submit
2- cant connect to the server no matter what I do
3- no sounds

**Comment by sm64js** [comment]
For 1 and 2, it sounds like either your IP is blocked either intentionally or by mistake.

Can you check the error you are getting in console?  When you hit start game but before you enter the game. Is there green text below the game that says connected to server? or red text that says can't connect.

And sound has not yet been implemented

**Comment by luphoria** [comment]
> 1- name won't submit
> 2- cant connect to the server no matter what I do
> 3- no sounds

Are you the one that counted up to 30? I accidentally banned you someone that did this thinking they had spammed for no reason, but then unbanned again when someone said they might have been playing a game. However I am not 100% sure I unbanned you correctly.
