### ISSUE TITLE
No teleport barrier on princess secret slide

### ISSUE THREAD

**Issue by sm64onlydude** [sm64js/sm64js#178]
![image](https://user-images.githubusercontent.com/74529728/101234187-4279cd00-36f8-11eb-86cc-6ba5c8b9a525.png)

**Comment by github10omar** [comment]
it has been taken from vanilla.sm64js.com, will not have a barrier

**Comment by github10omar** [comment]
they can

**Comment by smm2mickeyink** [comment]
> they can

its called a death barrier

**Comment by TheBusinessPyro** [comment]
> > they can
> 
> its called a death barrier

at the time i did this, if you got down there in places like this, it was just a teleport barrier.
