### ISSUE TITLE
lol blj (backwords long jumps break out and makes you shoot out crazy 

### ISSUE THREAD

**Issue by 5vixin** [sm64js/sm64js#179]
lol if you go under the castle andpreform a blj you can go so fast that you couldposibly break out de map ((POSSIBLY)

**Comment by luphoria** [comment]
Uh, you're maybe 30 years late to this bug lol...

**Comment by FallGuy308** [comment]
isnt this a glitch in original sm64

**Comment by smm2mickeyink** [comment]
> isnt this a glitch in original sm64

ya it is... i've seen speedruns use the blj to the beat the game with 0 stars
