### ISSUE TITLE
Wont even Let me Submit my name/The server won't connect.

### ISSUE THREAD

**Issue by JamieleBrown** [sm64js/sm64js#180]
No Matter how much I change my name, whenever i submit, nothing happens, and not only that, no matter how much I refresh the page, it just wont connect.

**Comment by luphoria** [comment]
Open the console. Is there an error? If it is 403, you are IP banned. This could be a cause of breaking the rules or using an IP address with a bad score (e.g. public wifi, or a VPN).

**Comment by sm64js** [comment]
reach out to me or a mod on discord for this issue
