### ISSUE TITLE
I went so fast I crashed the game

### ISSUE THREAD

**Issue by RageMage117** [sm64js/sm64js#181]
So I was running around in the cusom map all by myself only a few minutes ago, and I decided to use the speed glitch from the barriers. That requires you to be moving towards the barrier at an angle almost parrallel to the barrier, while facing away fom it with the same requiements. As I did, I starting building speed ridiculously. I was all the way across the map in a matter of miliseconds. Then, I got stuck to the barrier in the sliding pose and I assume I was still building speed because I was facing a different direction every frame. Then I stopped changing direction, pressed A and nothing happened. After that, I left and rejoined and all the flags had reset.

**Comment by sm64js** [comment]
Hmm, yea speed glitching can for sure cause the client to crash... I just want to make sure you didn't crash the server... I'll check server logs
