### ISSUE TITLE
add small karts and custom gliders

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#187]
add small karts. they should have a sm64js logo on it and the colours can be changed, along with adding some custom gliders

**Comment by FallGuy308** [comment]
so you basically want mk8 and sm64js in one package?

**Comment by github10omar** [comment]
ok yeah why not
Nintendo made super Mario Nintendo i beg you don't ban sm64js i have yet to see :(

**Comment by github10omar** [comment]
**do not**

**Comment by github10omar** [comment]
y is there nothing to be seen here

**Comment by sm64js** [comment]
good idea

**Comment by github10omar** [comment]
thnx
