### ISSUE TITLE
Starting Game On Mobile/With Controller

### ISSUE THREAD

**Issue by Iron-Fist351** [sm64js/sm64js#189]
The game can only be started with the start key on the keyboard, it can’t be started using the start button on the gamepad, preventing the game from being started on mobile, since the only possible input on mobile is with the gamepad. The rest of the game works with the gamepad. The issue might be related to the start screen working differently then the rest of the game so it can force you to choose a stage and username.

**Comment by FallGuy308** [comment]
well, they DO recommend you use a PC and not an ipad. Heck, I use a Win7!

**Comment by Iron-Fist351** [comment]
Portability is one of the main reasons they have for making a JS version of SM64. It’s listed on the website. That's why this is an important issue that needs to be fixed.

**Comment by smm2mickeyink** [comment]
> well, they DO recommend you use a PC and not an ipad or other mobile device. Heck, I use a Win7!

you can litterly connect a ps4 controller to your ios or android and the game will work

**Comment by sm64js** [comment]
You can now start the game with start button from controller
