### ISSUE TITLE
My Joy Con is drifting when I use it even though there isn't any drift.

### ISSUE THREAD

**Issue by 69420nic3** [sm64js/sm64js#191]

**Comment by smm2mickeyink** [comment]
then why would you use a joycon if it drifts you can probally just get i pro controller it barley even drifts

**Comment by Agent-11** [comment]
> then why would you use a joycon if it drifts you can probably just get i pro controller it barley even drifts

Incase you didn't read what they said, It only drifts in sm64js, meaning it is probably a stick dead zone issue.

**Comment by Cooliokid956** [comment]
> > then why would you use a joycon if it drifts you can probably just get i pro controller it barley even drifts
> 
> Incase you didn't read what they said, It only drifts in sm64js, meaning it is probably a stick dead zone issue.

yea, they just need to increase the deadzone

**Comment by 69420nic3** [comment]
k i guess

**Comment by Someone567123** [comment]
stupid just increase the deadzone by 0.5 if that works
