### ISSUE TITLE
People are invisible????

### ISSUE THREAD

**Issue by JacksTheGreat** [sm64js/sm64js#193]
So i was playing sm64js as usual and I joined bomb omb battlefield as usual but unlike the usual there was nobody even though I want to them on the minimap and there was a floating flag! I picked up the flag after that and my friend joined and he saw a floating flag too! It's clear I am not the only one effected by this, can someone tell me why this is happening?

**Comment by smm2mickeyink** [comment]
ya... its that dev thing again where they are working on the game??

**Comment by sm64js** [comment]
can anyone confirm whether this issue still exists?

**Comment by luphoria** [comment]
Duplicate #163
