### ISSUE TITLE
Not able to play

### ISSUE THREAD

**Issue by Vegito69** [sm64js/sm64js#195]
It won't let me submit name to play, Idk if i've been banned or not, But I don't remember what I've possibly done wrong. The last thing i remember was making the user Arcade Mario feel better about themselves so they wouldn't commit suicide. My username was [cs]Brayden. If this is only an issue with the website itself, Please fix it.
![Screenshot 2020-12-16 at 09 23 17](https://user-images.githubusercontent.com/74366490/102368371-6357e300-3f80-11eb-886d-7270d531ab8a.png)

**Comment by MinecrasfsftMan** [comment]
Same here.

**Comment by Cooliokid956** [comment]
> It won't let me submit name to play, Idk if i've been banned or not, But I don't remember what I've possibly done wrong. The last thing i remember was making the user Arcade Mario feel better about themselves so they wouldn't commit suicide. My username was [cs]Brayden. If this is only an issue with the website itself, Please fix it.
> ![Screenshot 2020-12-16 at 09 23 17](https://user-images.githubusercontent.com/74366490/102368371-6357e300-3f80-11eb-886d-7270d531ab8a.png)

Are you on a network with an integrated VPN (School Wi-Fi) or are using a VPN? If so, there's your problem. If not, then you were banned. Also, stuff might be a little broken on cellular data.

**Comment by Vegito69** [comment]
My internet doesn't have an integrated VPN, I don't know anything that could've got me banned, as the last thing I remember doing was helping Arcade Mario not kill theirself. So I'm honestly confused on why I'd be banned

**Comment by SHREXYGURL** [comment]
same it hasnt been working for like 2 hours already
![Screenshot 2020-12-04 at 2 45 10 PM](https://user-images.githubusercontent.com/76174275/102514601-4a1f6700-4052-11eb-8d85-01008fb0702d.png)

**Comment by SHREXYGURL** [comment]
i restart it like 100 times but its always the same result (the screenshot)
it says that my name isnt there but it is
and it says not connected to server but i only see that wen it recconects me
when im in a game tho
its obviously not started yet

**Comment by SHREXYGURL** [comment]
and this has been happening for the past few days
i only just reported cuz it really started to get to me

**Comment by SHREXYGURL** [comment]
and do u see in my screenshot how the maps dont say the amount of people?
thats always when the dumb thing happens
and i REALLY like this game but god is this annoying

**Comment by luphoria** [comment]
You were banned days ago for spamming though it was an interesting case -- your IP is the first banned to be dynamic. We can see that it changed just ever so slightly every time you rejoin. This will be fixed by blocking by IP _range_ instead of just IP later.

This was your third IP that was banned![Screenshot_2020-12-15_at_1.38.53_PM.png](https://user-images.githubusercontent.com/60309933/102520865-cb2e2c80-4059-11eb-8297-f79699666282.png)

**Comment by luphoria** [comment]
You can play on https://vanilla.sm64js.com or repeal your ban on the Discord

**Comment by Vegito69** [comment]
Yes well, I don't understand how I could've been banned is it because my friend Shrexy Gurl got banned, since me and her are using a school computer to play on this wondeful project

**Comment by Vegito69** [comment]
And discord is restricted due to our school admins

**Comment by Vegito69** [comment]
I just got notified by my immature friend Who's name is Jacob, He is the reason discord got blocked

**Comment by luphoria** [comment]
> I just got notified by my immature friend Who's name is Jacob, He is the reason discord got blocked
> 
> Edit: I got an update on why he's the reason, which is interesting cause he's usually a slow typer, But, It's because he named himself DickSword, Now I find him even more immature smh

Alright, well I will consider unblocking the IPs because every time you have rejoined you seemed to be clean.. the spamming seemed one-off so if you repeal I can unban you 🙂

**Comment by Vegito69** [comment]
How do I appeal to be exact? I've never appealed for something.

**Comment by SHREXYGURL** [comment]
-_________________________________-

**Comment by Cooliokid956** [comment]
> -_________________________________-

just dont spam again, and you wont be banned

**Comment by SHREXYGURL** [comment]
well just so u know it wasnt just me

**Comment by SHREXYGURL** [comment]
and if i was banned like days ago
how come it didnt start working TODAY?

**Comment by Cooliokid956** [comment]
like luph said, dynamic IPs, basically one of the numbers changes a bit, but sm64js thinks it's an entirely new IP

**Comment by SHREXYGURL** [comment]
ok
i wont
BUT IT WANST JUST ME

**Comment by Cooliokid956** [comment]
so it lets you play

**Comment by SHREXYGURL** [comment]
how would i be able to check it anyway?

**Comment by SHREXYGURL** [comment]
how would i be able to check my IP thingy anyway

**Comment by Cooliokid956** [comment]
> how would i be able to check my IP thingy anyway

https://www.whatismyip.net/

**Comment by Vegito69** [comment]
Idk if it is resolved yet as it is blocked atm, it will be unblocked soon, it always unblocks after a while

**Comment by SHREXYGURL** [comment]
wats blocked

**Comment by Vegito69** [comment]
I guess I'm still somehow banned cause i still have the issue, idk where i can appeal for an unban as discord is restricted, So i guess i'm screwed?

**Comment by SHREXYGURL** [comment]
same here

**Comment by SHREXYGURL** [comment]
wait i still have another account tho
cooliokid is it fine if i play there

**Comment by SHREXYGURL** [comment]
or are u gonna ban that one too?

**Comment by Cooliokid956** [comment]
wdym by account there are only ip bans

**Comment by Cooliokid956** [comment]
just dont spam
if you dont spam we might unban you

**Comment by SHREXYGURL** [comment]
OK
i WONT spam

**Comment by SHREXYGURL** [comment]
i have a diff account with a differnt ip

**Comment by SHREXYGURL** [comment]
but how do i show them i wont spam if i cant get on discord

**Comment by SHREXYGURL** [comment]
i might sound dumb but i have no idea how these types of programs work

**Comment by luphoria** [comment]
> I guess I'm still somehow banned cause i still have the issue, idk where i can appeal for an unban as discord is restricted, So i guess i'm screwed?

Private message me your IP address and I can find the reason for banning

**Comment by SHREXYGURL** [comment]
well they said it was cuz of spaming

**Comment by SHREXYGURL** [comment]
and how do i private chat u something

**Comment by Cooliokid956** [comment]
> and how do i private chat u something

they were talking to vegito69

**Comment by SHREXYGURL** [comment]
o

**Comment by Vegito69** [comment]
How do i private message?

**Comment by Cooliokid956** [comment]
do you have discord on a phone? are you in the server? you can dm luph then

**Comment by Vegito69** [comment]
I have no phone sadly, Is it alright if i post my ip in here though?

**Comment by SHREXYGURL** [comment]
ugh

**Comment by Cooliokid956** [comment]
NO IT IS NOT ALRIGHT

**Comment by Vegito69** [comment]
Ok, don't all caps me

**Comment by Cooliokid956** [comment]
not you them

**Comment by Cooliokid956** [comment]
oh wait
nvm

**Comment by Vegito69** [comment]
...

**Comment by SHREXYGURL** [comment]
who is "them"

**Comment by Cooliokid956** [comment]
just use a proxy like i do, heres the one i use: https://wonderingmars.gq

**Comment by Vegito69** [comment]
Okay?

**Comment by Cooliokid956** [comment]
you should be able to use discord there

**Comment by Vegito69** [comment]
Its restricted at my school lol

**Comment by Cooliokid956** [comment]
only that you need a qr code from a mobile device to access discord

**Comment by Cooliokid956** [comment]
oh off

**Comment by Vegito69** [comment]
Do you know his gmail?

**Comment by Cooliokid956** [comment]
well, do you by any chance have some kind of device other than your school laptop?

**Comment by Vegito69** [comment]
No

**Comment by SHREXYGURL** [comment]
do u even have tv

**Comment by SHREXYGURL** [comment]
sounds like u dont have anything

**Comment by Cooliokid956** [comment]
big oof
i guess you just can't do anything now
no i dont know luph's email

**Comment by Vegito69** [comment]
Dang it

**Comment by SHREXYGURL** [comment]
try to get luph to tell u

**Comment by Vegito69** [comment]
I'd private message luph on here but i don't think thats possible

**Comment by SHREXYGURL** [comment]
or get him to email u

**Comment by Vegito69** [comment]
Cause i have my IP copied right now

**Comment by Vegito69** [comment]
Could you try to get Luph's Gmail?

**Comment by Cooliokid956** [comment]
ok

**Comment by Vegito69** [comment]
thanks

**Comment by Vegito69** [comment]
Nice 
![Screenshot 2020-12-17 at 14 55 42](https://user-images.githubusercontent.com/74366490/102542840-04759500-4078-11eb-8b8d-d1cf979b35d7.png)

**Comment by Cooliokid956** [comment]
ha

**Comment by Vegito69** [comment]
Send his gmail when he gives it to you please and thank you

**Comment by Cooliokid956** [comment]
k

**Comment by Vegito69** [comment]
also, why would it not be fine to send the IP through here?

**Comment by Cooliokid956** [comment]
because your location can be found if you release your ip

**Comment by Vegito69** [comment]
ahok

**Comment by Vegito69** [comment]
I'll be back tomorrow, send his email when you get it, Bye, have a nice day

**Comment by Vegito69** [comment]
I'm guessing you did not recieve his email

**Comment by Someone567123** [comment]
> You can play on https://vanilla.sm64js.com or repeal your ban on the Discord

how to repeal ban do you have to do something?

**Comment by Someone567123** [comment]
> Yes well, I don't understand how I could've been banned is it because my friend Shrexy Gurl got banned, since me and her are using a school computer to play on this wondeful project

when you say "beautiful project" so you bribe them

**Comment by github10omar** [comment]
oof

**Comment by sm64js** [comment]
Contact mods on discord for help accessing the game
