### ISSUE TITLE
Taunt wheel bug

### ISSUE THREAD

**Issue by Kenocrystal** [sm64js/sm64js#197]
When I open the taunt wheel I'm not able to do much besides view the interface, I can't taunt or select the taunt I want. There is no indicator or arrow that allows me to use the taunts, I tried using the arrow keys, wasd, everything.. I even asked an other player.. I did what they did and it still doesn't work..

**Comment by luphoria** [comment]
Press t, hold it. Use the camera keybindings to select. When you have hovered over the one you wish to select let go of T, _then_ the control.

**Comment by Someone567123** [comment]
it's hard to taunt with a bluetooth controller such as a pro controller because the camera controls are binded to the right control stick. also, when you set up the deadzone to any controler, it doesn't save the settings.

**Comment by sm64js** [comment]
> it's hard to taunt with a bluetooth controller such as a pro controller because the camera controls are binded to the right control stick. also, when you set up the deadzone to any controller, it doesn't save the settings.

good to know, thanks

**Comment by sm64js** [comment]
You can also taunt by typing commands into chatbox

```
    "!taunt-wave"
    "!taunt-die"
    "!taunt-star"
    "!taunt-die2"
    "!taunt-shock"
    "!taunt-magic"
```
