### ISSUE TITLE
Ground-Pounding makes you start crouching on slides and other slopes

### ISSUE THREAD

**Issue by ItsMeSleepy** [sm64js/sm64js#198]
here is a video for evidence
https://user-images.githubusercontent.com/76575930/103116569-e1795100-4634-11eb-82a8-921d40d75b40.mp4
ask any questions
I have been able to long-jump and backflip out of them so it's not just visual.

**Comment by sm64js** [comment]
can you confirm this behavior does not happen in vanilla game?

**Comment by ItsMeSleepy** [comment]
yes

**Comment by ItsMeSleepy** [comment]
sorry I should say that it doesn't happen in the base game but it happens in the "vanilla" version of sm64js

**Comment by AgentXLP** [comment]
Odd

**Comment by AgentXLP** [comment]
This has been fixed somewhat

**Comment by AgentXLP** [comment]
I found the reason why this is happening, doing a full proper fix now.
