### ISSUE TITLE
Too sharp

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#2]
This runs like if the super-responsive controls cheat were on
Needs lots of work
Im surprised that you alone are re-rewriting mario 64
wow

**Comment by sm64js** [comment]
Thank you for checking it out and the feedback! 

Ah, I think you are correct, I think I did the super responsive controls as a shortcut, to get movement working then forgot to go back to that.  I'll leave this issue open and close it after I fix that.

and thanks for the support! It's been a ton of work, but really satisfying.

**Comment by Cooliokid956** [comment]
You’re welcome, and i forgot to say this, but the game is actually shaping up and is starting to be a game, and now that i heard that this has intentions of online multiplayer, im even MORE excited about this project
Thank YOU.

**Comment by sm64js** [comment]
This has been fixed. Let me know if the controls feel more like they are supposed to.

**Comment by Cooliokid956** [comment]
Yes they do! Thanks for fixing this. The game ALREADY feels complete. All thats left is more maps, doors, enemies, oh and also, the ground pound is, oh, its fixed too! Seems like the moveset is complete! Well imma close the issue now, goodbye
