### ISSUE TITLE
I've been informed that MetalSmash118 or MetalSlash118 has been banned due to spamming or just saying 0x2480 was a good mod, so he is using mobile hotspot to get on the game

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#201]
not that I'm saying that as a bad thing, but he says he's been banned for at least 3 months. He told me he got banned for saying that 0x2480 was a good mod. He also told me that ip ban was a school ip, so now 5 or more people who played on that public ip can't play. I don't know if IP bans are permanent or you guys find a reasonable time. also to make bans fair, please implement a warning system with 3 strikes.

**Comment by github10omar** [comment]
Hey, how can that happen? I told to people that 0x is a good mod, but I didn't get banned, so how can he get banned? Also trying to avoid an IP ban (if you have done bad) is clearly out of rule. I wonder...what did he say? Anything else other than this? Imform me, please.

**Comment by github10omar** [comment]
Also, I am not MetalSmash 118/MetalSlash118.

**Comment by Someone567123** [comment]
He's online now, so i guess you can ask him for more info. i already did, and he didn't say it was unfair or anything, he told me his last words before his ban were "hey guys!" "what are we talking about?" "0x2480 isn't a bad mod. 0x2480 is s good mod. at least in my opinion." from there, that's all he could remember. I'm pretty sure he might of spammed, but he hasn't said anything about that. Again, he's using a school pc with a public school ip, so he can't access GitHub.

**Comment by github10omar** [comment]
Spamming can lead to a ban, but it's strange to get banned like this for just saying a mod is good. I don't use Discord, however you can mail me at omarrocks09@gmail.com for more or just talk on Hangouts.
