### ISSUE TITLE
extra polygons.

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#203]
this error happens in chrome and edge when i move.

**Comment by sm64js** [comment]
This isn't very much info to go off of

**Comment by github10omar** [comment]
No, the thing loaded like 647 polygons for no reason, the polycount does not work anymore so i cant show. It's real and it lags and my ping is so low....

**Comment by sm64js** [comment]
does the game work okay on vanilla.sm64js.com?

**Comment by github10omar** [comment]
yes

**Comment by matthew-vsi** [comment]
so the game does not slow down and does not lag at vanilla.sm64js.com, but it does at sm64js.com?

I am having trouble understanding what you mean when you talk about extra polygons
