### ISSUE TITLE
cannot join

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#204]
i press submit then nothing happens. help, i checked the console also no ban message

**Comment by github10omar** [comment]
also i visited cheats.sm64js.com

**Comment by github10omar** [comment]
was that a ban for that?

**Comment by Cooliokid956** [comment]
cheats.sm64js.com doesnt exist

**Comment by Someone567123** [comment]
lol

**Comment by Someone567123** [comment]
HEY also i can't join. all of a sudden, everyone left the game and now no one is playing. was it accidental? it happened yesterday too.

**Comment by SHREXYGURL2** [comment]
same

**Comment by SHREXYGURL2** [comment]
no matter how much i restart it wont let me in

**Comment by Cooliokid956** [comment]
apparently this is happening because the filter API is down
this basically prevents anything from running

**Comment by SHREXYGURL2** [comment]
wats an API filter

**Comment by Someone567123** [comment]
yeah

**Comment by Cooliokid956** [comment]
r/explainlikeimfive
the thing that makes the no-nos go bye-bye

**Comment by Someone567123** [comment]
ok

**Comment by SHREXYGURL2** [comment]
o ok

**Comment by Someone567123** [comment]
so yeah, no one can get in

**Comment by Someone567123** [comment]
not pog

**Comment by SHREXYGURL2** [comment]
how long will it last

**Comment by Cooliokid956** [comment]
less technical explanation:
filters the bad words

**Comment by Cooliokid956** [comment]
it will last until the API goes back up

**Comment by SHREXYGURL2** [comment]
o so u dont know

**Comment by Someone567123** [comment]
but like, cursing is cool B)

**Comment by SHREXYGURL2** [comment]
y do u think it went down?

**Comment by Someone567123** [comment]
duh it did. the cursing filter is down

**Comment by SHREXYGURL2** [comment]
i said WHY

**Comment by Cooliokid956** [comment]
idk

**Comment by Someone567123** [comment]
it think it goes down because some people try to bypass it or something. like i think it detects words like the f word and from there it sends reports to the mods

**Comment by SHREXYGURL2** [comment]
makes sense

**Comment by Someone567123** [comment]
the game still won't let me in... :(.

**Comment by sm64js** [comment]
Should be fixed
