### ISSUE TITLE
the game won't start when you press start. then why even make the thingy go boing if it's not the way you insert your name?

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#205]
Ik the API Filter is down, but way before that mess, pressing the enter key doesn't let you submit your name.

**Comment by sm64js** [comment]
good point, I'll see if I can fix this

**Comment by Someone567123** [comment]
omg you actually replied. and ur the real owner... 😳

**Comment by sm64js** [comment]
I fixed this issue

**Comment by Someone567123** [comment]
pog
