### ISSUE TITLE
Page Unresponsive/Frozen/Game Crash when...

### ISSUE THREAD

**Issue by SMGee4** [sm64js/sm64js#208]
When you intentionally do "Mario Star Get" animation from the taunt wheel it can sometimes freeze the website and/or crash the game; you cannot reset the game or reload the website. If you try to reload the page it will say "Page Unresponsive" forcing you to open SM64JS.com in another tab. This is more common if you do the taunt repeatedly without completing it.

 This was proven in Cool, Cool, Mountain.

(https://user-images.githubusercontent.com/77451531/104614397-37e71780-5656-11eb-8696-b9ca9c4df1d1.png)

**Comment by Someone567123** [comment]
ok

**Comment by sm64js** [comment]
hmm, this doesn't happen to me.  I can't reproduce this.

**Comment by Cooliokid956** [comment]
> hmm, this doesn't happen to me. I can't reproduce this.

just spam the star taunt

**Comment by sm64js** [comment]
This issue happened to me, interesting, I'll check it out

**Comment by smm2mickeyink** [comment]
> This issue happened to me, interesting, I'll check it out

its easier if you hold t and spam the star animation

**Comment by AgentXLP** [comment]
There are more important bugs to fix

**Comment by AgentXLP** [comment]
Think I got a fix working locally.
