### ISSUE TITLE
Your walking direction makes others bob their heads to it

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#21]
Walk right, they look right. Walk left, they look left. I don't know why they do that but weird

**Comment by sm64js** [comment]
Yep, the torso tilt property needs to be split to each mario, right now it is a single value.  I am working on a multiplayer rewrite and it will address this

**Comment by sm64js** [comment]
Closing this issue because it is fixed in the new multiplayer version.

**Comment by Cooliokid956** [comment]
cool
