### ISSUE TITLE
Uncaught unimplemented bobomb action

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#211]
In vanilla.sm64js.com, the reason that the bob-omb blast crashes is this error:
Uncaught unimplemented bobomb action - generic_bobomb_free_loop

In cheats.sm64js.com, this does not occur as I think it is implemented but forgotten.

You may need some fixin' on this, devs.

**Comment by github10omar** [comment]
To replicate it, just swoopkick the bob-ombs and check the console. Same error.

**Comment by sm64js** [comment]
fixed

**Comment by github10omar** [comment]
😳
