### ISSUE TITLE
someone just called me a noob and i smeel and i am trash, lol

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#212]
this must be prevented. has bad effects on kids

![image](https://user-images.githubusercontent.com/74847773/104995989-8fafc500-5a40-11eb-95d5-f2ce633a3ac3.png)
![image](https://user-images.githubusercontent.com/74847773/104996003-95a5a600-5a40-11eb-85cf-455fc60cb9d1.png)

**Comment by Someone567123** [comment]
good

**Comment by github10omar** [comment]
good prevention

**Comment by justabluemouse** [comment]
Uhh, just for future reference, while people are toxic on here, that's not really an issue you solve on Github, you solve it in the game by mods banning the toxic players.
