### ISSUE TITLE
emojis won't work ever since the exploration update. (the map update where you choose stages.)

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#213]
https://user-images.githubusercontent.com/75187751/105001147-2e5a0880-59e4-11eb-8403-60e41b6296da.mp4

**Comment by github10omar** [comment]
ok
bruh this happened to us since the text of admins are blue

**Comment by SMGee4** [comment]
Did you try the default dance emote?

**Comment by github10omar** [comment]
bruh not those, like these 😎

those will not work

**Comment by Someone567123** [comment]
yeah
