### ISSUE TITLE
ban relese

### ISSUE THREAD

**Issue by Doomguy3232** [sm64js/sm64js#216]
so uhh i got banned for telling a guy who was being mean to me to shut up then spammed it in chat soooo... yeaaa if u need my ip i can supply it so ya plz do it i wont spam agin no matter how annoying the dude is. ps im not good at spelling sue me.

**Comment by Cooliokid956** [comment]
you were ad-spamming your website, be ashamed
no

**Comment by Doomguy3232** [comment]
YOU YOU WERE THE ONE I WANT JUSTACE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by supermariobros575** [comment]
I will bring this up with devs, I cant guarantee an unban tho

**Comment by Doomguy3232** [comment]
Thank you so much my guy

**Comment by Doomguy3232** [comment]
hey its been 3 days... and i havent been unbanned... so uhhhh... yeaaaaaaaaaaaaa. whats going on?

**Comment by sm64js** [comment]
contact us on discord for unban
