### ISSUE TITLE
i might be banned lol. I don't remember doing anything wrong last night. I was with omar and all we did was go on the phoenix wright thing website

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#218]
I DO remember that i asked SMB575 if he could test ban me to see if he could ban people. I insisted, but he didn't want to. that waas earlier in the day.

**Comment by github10omar** [comment]
oh yeah that thing

how was that a ban

i should had been banned if the phoenix thing was something

**Comment by Someone567123** [comment]
Idk i left my pc on to charge me phone and then bam, i got banned?
