### ISSUE TITLE
so

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#221]
the smoke particles is too much and it lags the game. optimizations?

**Comment by sm64js** [comment]
Thank you for the feedback, there are ways I can optimize it. I didn't realize it was lagging the game.

**Comment by sm64js** [comment]
please use a more descriptive title

**Comment by github10omar** [comment]
ok!

**Comment by sm64js** [comment]
Will make low graphics settings as an option in future for slower devices

**Comment by github10omar** [comment]
OK!
