### ISSUE TITLE
am i banned

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#222]
game not working

bSocket connection to 'wss://server.sm64js.com/websocket/' failed: Error during WebSocket handshake: Unexpected response code: 502
(anonymous) @ main-a02c1091c35013d1806c.js:2
main-a02c1091c35013d1806c.js:2 WebSocket is already in CLOSING or CLOSED state.
Fo @ main-a02c1091c35013d1806c.js:2
main-a02c1091c35013d1806c.js:2 Starting Game!
main-a02c1091c35013d1806c.js:2 WebSocket is already in CLOSING or CLOSED state.
Fo @ main-a02c1091c35013d1806c.js:2
main-a02c1091c35013d1806c.js:2 WebSocket is already in CLOSING or CLOSED state.
Fo @ main-a02c1091c35013d1806c.js:2
main-a02c1091c35013d1806c.js:2 WebSocket is already in CLOSING or CLOSED state.
Fo @ main-a02c1091c35013d1806c.js:2

this came from my console

**Comment by sm64js** [comment]
Should be working now,

For connection issues please wait 24 hours to see if the issue persists before posting.

Also try the help channel on discord

**Comment by github10omar** [comment]
ok! thank u
