### ISSUE TITLE
Needing to log in every time i refresh

### ISSUE THREAD

**Issue by Diamonds4life** [sm64js/sm64js#241]
When I play SM64JS and I want to join a new map, I have to login/authorize discord every single time I refresh the page. Please fix this, it will make it much easier to play.

**Comment by smm2mickeyink** [comment]
yes this is true its annoying

**Comment by 69420nic3** [comment]
same thing with google

**Comment by Tarnadas** [comment]
This is already being worked on.

We will implement basic cookie sessions, which will persist your Discord and Google login.

**Comment by github10omar** [comment]
@Tarnadas I would like to tell you it's added but it says that the token's invalid.

**Comment by Tarnadas** [comment]
It's not added.
When you first log in your browser bar contains a one-time use login token. If you hit f5, it will try to log in with an invalidated token
