### ISSUE TITLE
My controller doesnt support the game i think... 

### ISSUE THREAD

**Issue by LeftyOwO** [sm64js/sm64js#248]
I have an EasySMX controller...
And its not working the buttons not doing anything...
I started this game yet on my mobile tablet and it seems it would work but when i use bluetooth controllers the internet gets very bad... 
Could someone help me?

**Comment by sm64js** [comment]
does your controller work here: https://gamepad-tester.com/

**Comment by AgentXLP** [comment]
No response, issue stale.
