### ISSUE TITLE
Everyone got privacy error somehow...

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#250]
idk i just wanted to play :(

**Comment by Cooliokid956** [comment]
same

**Comment by Cooliokid956** [comment]
the problem seems to be that the website's security certificate expired, although vanilla still works though, use that rn until snuffy renews it

**Comment by Cooliokid956** [comment]
Snuffy's on it! The website will be back up in a while.

**Comment by Cooliokid956** [comment]
It's back up! Keep playing, everyone!

**Comment by smm2mickeyink** [comment]
> It's back up! Keep playing, everyone!

yay also i saw the message on the discord server also i did find myself about the certificate expiring.

**Comment by sm64js** [comment]
fixed
