### ISSUE TITLE
Issues with the games login system

### ISSUE THREAD

**Issue by SHADOWMARlO** [sm64js/sm64js#252]
why dose this game hate brave so much i have to login with google every time i play and rest and now i cant even get in anymore and it also disconects within 2 seconds of not being in that page

**Comment by SHADOWMARlO** [comment]
I havent used google chrome since mid 2020

**Comment by Tarnadas** [comment]
You can resolve the disconnect by setting a specific flag like mentioned here:
https://github.com/sm64js/sm64js/issues/136#issuecomment-731964085
Since Brave is basically Chrome, this should be possible right?

Also the session persisting will be implemented soon ™. See #241

**Comment by SHADOWMARlO** [comment]
the game wont work anymore anyway

**Comment by luphoria** [comment]
fixed
