### ISSUE TITLE
wheres the voice clips and sounds

### ISSUE THREAD

**Issue by SHADOWMARlO** [sm64js/sm64js#253]
were are they is it copyright to hard to code or you just dont want to i can do mario voices if it is copyright

**Comment by Cooliokid956** [comment]
no lol, he just hasn't figured out how to make sounds, well, sound.

**Comment by SHADOWMARlO** [comment]
oooooooooooooooooooooooo

**Comment by sm64js** [comment]
yea, Audio will be a big task, and just other big tasks have always took priority

**Comment by smm2mickeyink** [comment]
> yea, Audio will be a big task, and just other big tasks have always took priority

i know this has nothing to do with this issue, but the health in vanilla got added :D that kinda got me hyped for the next update.
