### ISSUE TITLE
SM64JS MMO Acting like Vanilla Help :(

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#256]
Help :( o.o nater is having same problem

**Comment by SHADOWMARlO** [comment]
Maybe Use A wayback machine Guys Maybe That Will Help

**Comment by smm2mickeyink** [comment]
> Maybe Use A way

**Comment by smm2mickeyink** [comment]
> Maybe Use A wayback machine Guys Maybe That Will Help

NO i'd rather not... cause most players are having same problem tooo!

**Comment by Cooliokid956** [comment]
> Maybe Use A wayback machine Guys Maybe That Will Help

lol using the wayback machine won't work because it's an online game
