### ISSUE TITLE
pro controller

### ISSUE THREAD

**Issue by ryanhdtvyt10** [sm64js/sm64js#259]
when i try to use my nintendo switch pro controller on sm64js it bugs and it always moves up right. idk wht it does that but fix pls?

**Comment by ryanhdtvyt10** [comment]
UPDATE: it only moves the camera now

**Comment by smm2mickeyink** [comment]
just change the controls for the switch pro controller it wasn't a problem for me

**Comment by sm64js** [comment]
Pro controller works well for me and others.   try resetting the controls and massing around with them for a bit

**Comment by ryanhdtvyt10** [comment]
messing*

**Comment by ryanhdtvyt10** [comment]
i use joystick to move
