### ISSUE TITLE
(Suggestion) More anti-bully mesaures, no wait cross that

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#26]
Original post:
Vote-kicking, statistics, like, how many times they've done stuff like the crouch stationary attack that they use to keep people where they are, to determine if they are eligible for the title of "Bully", oh yeah and do cookie saving or some other type of saving data. When rooms exist, there should be bully-free rooms for each game that there will be.
Now, imma say to add ids to avoid impostorage

**Comment by sm64js** [comment]
all of the attacks and pvp stuff is temporary and will be replaced
all each additional game mode would likely have their own rules and actions for attacks and pvp
