### ISSUE TITLE
jumping causes a crash

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#260]
![image](https://user-images.githubusercontent.com/74847773/107905883-35375500-6f69-11eb-8011-5e348756bf7a.png)
i was jumping off in ccm but game crashed off this so called error

**Comment by smm2mickeyink** [comment]
ya weird how jumping does constant errors in console..

**Comment by sm64js** [comment]
thanks... hmm can you give ma  little more context? jumping in ccm in general is working... so what happened here?  maybe you can make a video of this happening?

**Comment by ghost** [comment]
player: *literally jumps*
server: GYUEPJWVCJGKWLHYKU@ILHO:JFDG@JIOIFTUGYIHPOP@EFCJHGKUILE@YTFDJGUIJO@DUYGELIU:OLFDG@EJKUI"{)GKYIP"(YGUFTKGYLHIO@UGFTUGYIDP{)(G@PU)GIO@HUGKHJODIEHLJODIHGDYIUOEGIGOPHU{DFOG(PH@*GCFOGPHU{"I@O:HJ(MN*UM@U()NQTY*)N@#&B*N@B(79l2IUY#@TYUPojelwk;jqBNJOHUOF*@#R^&#*()+#_(@*27*Y&#UOHJDOJYI$FIUOJM'NocjmklpJHCOREIPO{K{E
l{elplPJEPO[kpOIHPJKC}PJCEIP"KC:KNJOPEOK{E)POJO{EHCIPHEIPJNK:E[ochbueijpclej
