### ISSUE TITLE
Add :mariosus:

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#262]
This was available in the sm64js discord server now we need it in the sm64js game

**Comment by Someone567123** [comment]
we neeed to add go are hell

**Comment by ghost** [comment]
is this the go are hell thing
![go are hell](https://user-images.githubusercontent.com/69992708/108005830-0ba51a80-6fb7-11eb-9341-97db356249a1.gif)

**Comment by Someone567123** [comment]
yes lol

**Comment by sm64js** [comment]
will consider adding these discord emojis

**Comment by Cooliokid956** [comment]
> will consider adding these discord emojis

if you actually are, i already have them in the pr #249
