### ISSUE TITLE
plz kick maeo

### ISSUE THREAD

**Issue by Flamingofan02** [sm64js/sm64js#264]

**Comment by Cooliokid956** [comment]
hell no

**Comment by ghost** [comment]
i think the only reason sm64js players have github accounts is for this (this is from 404 from sm64js)

**Comment by Cooliokid956** [comment]
> i think the only reason sm64js players have github accounts is for this (this is from 404 from sm64js)

yea, just look at their account creation dates

**Comment by sm64js** [comment]
this is not the place to report spam, 

report spam on discord... we'll add an ingame option soon
