### ISSUE TITLE
Nerf attacks

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#27]
Instead of limiting how fast you can attack, you can make it so that there are invisibility frames where attacks don't affect you. This can help with LOTS of problems

**Comment by sm64js** [comment]
There is invisibility frames btw

all of the attacks and pvp stuff is temporary and will be replaced

all each additional game mode would likely have their own rules and actions for attacks and pvp

**Comment by Cooliokid956** [comment]
oh good
