### ISSUE TITLE
typing grass grass causes a weird glitch

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#271]
![Screen Shot 2021-02-27 at 1 04 54 PM](https://user-images.githubusercontent.com/69992708/109398869-a0cfd980-78fc-11eb-9d89-ff9066b35312.png)
https://user-images.githubusercontent.com/69992708/109398923-e2608480-78fc-11eb-96a3-a9632920c96a.mov

i don't know how it works but this should be fixed or something

**Comment by ghost** [comment]
it also does that with:
japan japan
shaggy shaggy

and maybe more that i dont know about

**Comment by github10omar** [comment]
woah

**Comment by ghost** [comment]
yes woah indeed

**Comment by luphoria** [comment]
Can anyone verify this still exists?

**Comment by AgentXLP** [comment]
> Can anyone verify this still exists?

![image](https://user-images.githubusercontent.com/44549182/121092552-bb4a0680-c7b9-11eb-85ee-8bfe20fb8ee2.png)
it is just a censoring issue for me

**Comment by AgentXLP** [comment]
bad crop ._.

**Comment by eeveeboi** [comment]
this happen when i tried to go in mmo 
![Screenshot 2021-10-20 7 30 41 PM](https://user-images.githubusercontent.com/92833823/138195773-9fa87224-d67e-4486-819d-53fdaa63933b.png)

**Comment by eeveeboi** [comment]
lol

**Comment by ImaginaryNeon** [comment]
have you tried "un un un"?

**Comment by eeveeboi** [comment]
oh okay lol

**Comment by ImaginaryNeon** [comment]
something similar happens to me when I log in with Google.

![Screenshot 2021-10-22 1 15 20 PM](https://user-images.githubusercontent.com/92883596/138504357-c91d5d9c-b87e-4087-94ef-67faf2a6215d.png)



> this happen when i tried to go in mmo ![Screenshot 2021-10-20 7 30 41 PM](https://user-images.githubusercontent.com/92833823/138195773-9fa87224-d67e-4486-819d-53fdaa63933b.png)
