### ISSUE TITLE
No Wall bonk, speed gain

### ISSUE THREAD

**Issue by lol94039** [sm64js/sm64js#273]
https://user-images.githubusercontent.com/79794463/109419946-43a55800-79d0-11eb-9e25-d5a5e8e63601.mp4

**Comment by github10omar** [comment]
that happens to me in sm64js, also og sm64 too

**Comment by smm2mickeyink** [comment]
that's already been found ._.

**Comment by MasterNama17083** [comment]
I have bob omb battlefield slope bug.

**Comment by smm2mickeyink** [comment]
> I have bob omb battlefield slope bug.

old glitch :morphoff: someone already discovered that in october

**Comment by AgentXLP** [comment]
Fixed in https://agent-11.github.io/projects/sm64js
