### ISSUE TITLE
Bob omb crashing Game 

### ISSUE THREAD

**Issue by lol94039** [sm64js/sm64js#274]
I think it only works when it rotates of the platform somehow?

https://user-images.githubusercontent.com/79794463/109420591-a3513280-79d3-11eb-8aa0-1a27013aadba.mp4

**Comment by smm2mickeyink** [comment]
it wasn't the bom omb it was the moving platform cause it pushed you in the ground.

**Comment by PSIPowerhouse** [comment]
@smm2mickeyink is right. cuz i did a blj on that platform and i crashed

**Comment by AgentXLP** [comment]
Fairly certain this is fixed in my most up to date version of sm64js vanilla. https://agent-11.github.io/projects/sm64js
