### ISSUE TITLE
Discord/Google auth is broken

### ISSUE THREAD

**Issue by ItzLoonie** [sm64js/sm64js#277]
Logging in with Discord or Google works normal, but once you start, it kicks you out and gives an auth error, **EVERY** time.
btw, I'm on chrome and it worked just fine earlier today

**Comment by 69420nic3** [comment]
You have to start the game before submitting the map and name

**Comment by AgentXLP** [comment]
luphoria said this was going to be fixed very soon

**Comment by justabluemouse** [comment]
Uh oh. He's right, this time I literally can't login, whether I start the game or not.

**Comment by justabluemouse** [comment]
Please fix, it just stopped working for me today, and I love sm64js.com. Any tips to fix this? I don't wanna be stuck playing vanilla.

**Comment by Tarnadas** [comment]
fixed with next deployment

**Comment by justabluemouse** [comment]
Wait, how do I do next deployment?

**Comment by Tarnadas** [comment]
you don't do it. We'll have to wait until @snuffysasa is avaiable

**Comment by justabluemouse** [comment]
Oh, I see. Thanks for clarifying.

**Comment by uuphoria2** [comment]
> you don't do it. We'll have to wait until @snuffysasa is avaiable

I know this is like 3 years old tho how did snuffysasa do deployments? (During the rust server time) Like what service Did he use the built in namecheap cpanel? Or did he use the rust server (Which is basically the docker image) and if he did Did he use nginx to basically use localhost:3060 to be deployed on sm64js? Or did he only use the rust server to deploy it (Production website)
