### ISSUE TITLE
(Suggestion) Add Jolly Roger Bay

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#283]
I think since we have swimming we can have a water level like Jolly Roger Bay. Plz add the level!!!

**Comment by luphoria** [comment]
Tried my hand at this a while ago, this was the result. Will debug more later
https://user-images.githubusercontent.com/60309933/111079578-969b0700-84c8-11eb-813a-b8c7fe778c96.mp4

**Comment by smm2mickeyink** [comment]
> Tried my hand at this a while ago, this was the result. Will debug more later
> https://user-images.githubusercontent.com/60309933/111079578-969b0700-84c8-11eb-813a-b8c7fe778c96.mp4

Can i try it? if i know how to get it work

**Comment by smm2mickeyink** [comment]
> Tried my hand at this a while ago, this was the result. Will debug more later
> https://user-images.githubusercontent.com/60309933/111079578-969b0700-84c8-11eb-813a-b8c7fe778c96.mp4

It still looks fine it probably still will work, right?

**Comment by luphoria** [comment]
> It still looks fine it probably still will work, right?

Its definitely not main repo ready. Idk whats causing the rendering issues, but if i had to guess it would be that the movtext is only half implemented. Which is another thing that needs finished.

**Comment by justabluemouse** [comment]
Yeah, JRB sounds like a great addition to the already wide variety of maps in this game!

**Comment by AgentXLP** [comment]
I'll add it MMO once one of the devs or myself implements the new level commands structure and bhv structure as well, this new structure is much more accurate to the original C decomp and would be nice to have since it works in conjuction with the brand new data converter from sm64 decomp to sm64js

**Comment by AgentXLP** [comment]
guess who ported the new level and bhv commands structure

**Comment by AgentXLP** [comment]
I added JRB to Vanilla on my ver at least, about adding it to MMO, I'll consider it. 👍
