### ISSUE TITLE
Suggestion: Add wall sliding

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#287]
I was trying to escape dory but i kept bonking plz add a toggle or something to make wall jumps a little easier.

**Comment by BeanMKW** [comment]
useless

**Comment by Agent-11** [comment]
This is a suggestion not an issue.

**Comment by justabluemouse** [comment]
No, not an issue, but would be a cool feature(though I've already learned to time my a-presses like a god).

**Comment by AgentXLP** [comment]
> useless

not very, would be nice to add

**Comment by PSIPowerhouse** [comment]
> useless

it is actually very usefull

**Comment by ItsMeSleepy** [comment]
I would hate this as a skilled player

**Comment by AgentXLP** [comment]
I see.
I will most likely add a togglable option for wall sliding.
