### ISSUE TITLE
There's no reverse switch? (Kart Mode)

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#293]
Help, I can't press this backward switch.
How I back my kart?.
![image](https://user-images.githubusercontent.com/80534869/112118118-0f454600-8be2-11eb-81f2-117ec0de6196.png)

**Comment by 69420nic3** [comment]
u hold z and press a to go backwards. im shocked you dont know this

**Comment by Cooliokid956** [comment]
same
