### ISSUE TITLE
(Suggestion) Additional Settings For Custom Game

### ISSUE THREAD

**Issue by Squishy6094** [sm64js/sm64js#294]
The following are some settings that could be added to make Custom Game more Customizable:

Health: Toggle

Glider/Karts: Toggle

Show Usernames In Game: Toggle
(Would hide all players usernames when toggled off for games of Hide and Seek)

Minimap: Toggle
(Would prevent players from using the minimap if toggled off for games of Hide and Seek)

Knockback: Selection
(Chose from Low, Medium, or High)

Ground-Pound Jump/Dive: Toggle

Gameshark Codes: Toggle

PvP Default: Toggle
(This changes the default PvP toggle, Making More Peaceful/Chaotic Custom Games, User can still toggle it on/off)

Custom Usernames: Toggle
(This would make using Custom Usernames instead of your Discord/Gmail unavailable/available)

Profanity Filter: Toggle

Join/Leave Chat Notification: Toggle
(Would send a message in chat if a user has Joined/Left)

Public Room: Toggle
(Maybe a Public room list could be added in the future, each user could only make one room each to prevent room spam, If Toggled off it would give you a link like normal)

Public Room Name: Text Box
(Requires Public Room Toggle to be active)

Public Room Password: Toggle + Text box
(Requires Public Room Toggle and Password Toggle to be active to use text box, Would show a lock next to the room and the room creator would give out a password to use to enter the room)

**Other things that could be added to custom games:**

Announcement Text box
(Would be under the chat box for only the room creator, would act like public game announcements from moderators)

Kicking
(If the room creator uses "/kick [user]", the user will be kicked and will be unable to join again for another 10 minutes and would not tell them to wait or show a timer in order prevent them from joining again, /ban could also be added)

Seeker
(If the room creator uses "/seek [user]" the user would become 1.5 times bigger, deal 8 damage on all hits, and become a bright red. They would also not be able to see usernames in game or use the minimap no matter what the username/minimap settings are set to.)

**Comment by MasterNama17083** [comment]
I agree. Developers will add features soon in this game.

**Comment by Cooliokid956** [comment]
Cool ideas!

**Comment by justabluemouse** [comment]
Woah! Those are some really sweet ideas! Might take a ton of time for developing, but still, I would love to see all this in sm64js.com!

**Comment by PSIPowerhouse** [comment]
Nice ideas!

**Comment by AgentXLP** [comment]
Custom games are depreciated for now.
