### ISSUE TITLE
[Mostly Suggestions] Flag being buggy + smoother kart transition + drown crash + sign-in process

### ISSUE THREAD

**Issue by justabluemouse** [sm64js/sm64js#295]
So basically, dropping and picking up flags in sm64js.com is kinda buggy. I attack someone, I touch the flag like six times, and yet the other player retrieves the flag. Granted, this might be just because i tilted and nearly smashed my keyboard because of this(and ragequit), but you please make the flag hitbox to cover the entire flag instead of just the center? Second, I kinda wish you could pull out the kart/glider with the V key a lot faster, because you have to come to almost a complete stop and lose a lot of momentum to make the switch from foot to tire. Third, I've tried this one out before, if you drown in the game, sm64js.com crashes on your end(thankfully it doesn't crash the server), and you have to reload and do the joining process all over again. Finally, Why do you always have to sign-in via Discord/Google account? I just find it a little inconvienent to have to do it over and over again, instead of just once. Otherwise, those are just nitpicks, and the game is fantastic! Keep up the good work, guys!

**Comment by AgentXLP** [comment]
All have been fixed for a while
