### ISSUE TITLE
[Suggestion] Combining Maps + Adding Proper Level features + More Parkour 

### ISSUE THREAD

**Issue by justabluemouse** [sm64js/sm64js#296]
While the original setup for maps works just fine, I do have a suggestion, that I think could make things easier. Instead of having "Castle Grounds", "Castle First Level" and "Castle Second Level", I do feel like it would make things a lot better if the three maps were all combined into one map, or at the very least combining the first and second level.  My second suggestion is about adding level features. What do I mean by that? I mean, in CCM(Cool Cool Mountain), I feel like it would feel a lot more like CCM if you added being able to enter the house at the top and do the slide to the bottom of CCM, and other stuff in levels. Third, I love the idea of super mario 64 but MMO(along with epic features that make the already awesome experience even more awesome), but sometimes, it can be a little boring if no one else is there. So, what I want, are maps specifically created for epic sm64js.com parkour, and not just jumping from mushroom to mushroom. I mean, HARD sections like having to do a ground-pound jump then wall jump then ground-pound dive cancel then glide to reach the areas you need to. Then...maybe being able to wear a special badge next to your username for completing a hard parkour course? I mean, I think it would be cool, because it would prove my pro gamer skills(lol), so yeah, that's what I would like to see in the future. Final Note: I'm glad that the creators of sm64js.com actually listen to the fanbase about possible new features and actually implement them into the game! For once, I feel satasfied that I what I think would be cool is in the game(unlike a SPECIFIC game company that starts with an N, but I'm not naming names).

**Comment by Cooliokid956** [comment]
neen10doh

**Comment by justabluemouse** [comment]
Nentendough

**Comment by smm2mickeyink** [comment]
> Nentendough

yes

**Comment by AgentXLP** [comment]
Warping has already been implemented into the vanilla version of the game and needs small tweaks for multiplayer and it would work as far as I can tell, still a complicated system none the less but map merging can be held off for now if it takes does not take a prolonged time to implement to MMO, the programmer behind warping in vanilla has no interest in working on MMO at all so it would need to be ported by a different dev, like me for example.

**Comment by AgentXLP** [comment]
I cracked the case, I will try to add warping either this month later on or next month.

**Comment by AgentXLP** [comment]
I'm also adding objects to levels now including the chain chomp in bob so I think this issue can be closed now.

**Comment by AgentXLP** [comment]
Don't get me wrong though these are some good suggestions.
Level warping will most likely be in by April and I'm adding more objects and environment things to levels now.
