### ISSUE TITLE
Is sm64js.com temporarily take down if what happened to?!

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#297]
I won't load this site [sm64js](sm64js.com).
![image](https://user-images.githubusercontent.com/80534869/112719674-0d4fef80-8f20-11eb-8618-401378380949.png)

**Comment by MasterNama17083** [comment]
Solved go here: [sm64js (rust mode)](rust.sm64js.com)

**Comment by Cooliokid956** [comment]
[rust.sm64js.com](sm64js rust)

**Comment by Cooliokid956** [comment]
rust.sm64js.com

**Comment by Tarnadas** [comment]
Certificate error has been fixed
