### ISSUE TITLE
Pasting color code and press v keyboard shortcut causes game crashes in rust.sm64js.com

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#298]
Here is the video. I pasted my backup color code in console mode. I pressed for `v` (Gilden/Kart) Mode causes a level to disappear and the game to crash.
https://user-images.githubusercontent.com/80534869/112720147-9f58f780-8f22-11eb-92f6-fa5f09f088cb.mp4

**Comment by luphoria** [comment]
It seems you havent adjusted the code for the parachute color options. Heres a template example (you sent this yourself a while ago)

`window.myMario.skinData = {"overalls":[28,75,192,57,151,255],"hat":[38,98,61,76,197,123],"shirt":[0,64,28,0,129,57],"gloves":[101,79,255,203,255,255],"boots":[74,19,38,148,38,76],"skin":[127,90,59,254,175,118],"hair":[35,3,0,71,6,0],"parachute":[0,104,45,0,208,90],"customCapState":0}`

Simply add the `parachute` parameter.

**Comment by luphoria** [comment]
one week, and this worked when i reproduced the issue. closing
