### ISSUE TITLE
Oh no, Can't login to MMO sm64js

### ISSUE THREAD

**Issue by justabluemouse** [sm64js/sm64js#299]
Uh oh, everytime I've used google verfication/authorization, It always sends this message: 
![oh no](https://user-images.githubusercontent.com/81450807/112725121-fba12480-8eec-11eb-91df-40e6956aa716.PNG) What happened? It worked up until today(which happened to be the day I was gonna brag on the server about me reading the entire sm64js wiki lore page lol).

**Comment by justabluemouse** [comment]
I've tried pressing the start button before verfiying, and it still didn't work...

**Comment by justabluemouse** [comment]
Help, anyone? Please?

**Comment by justabluemouse** [comment]
Day 420: I have not been able to open the game for more than a year someone please respond

**Comment by Tarnadas** [comment]
We’re working on fixing Google login. Until then you will have to use Discord

**Comment by justabluemouse** [comment]
Uh oh. Don't have a Discord, and I can't get one. Looks like I'm not playing until the bug gets fixed :( But still, thank you for at least notifying me with what's going on.
