### ISSUE TITLE
Gamepad Support 

### ISSUE THREAD

**Issue by dirtblockyt** [sm64js/sm64js#308]
I first used my Xbox One controller to play, moves around pretty good but, i can't use my A, B, X, Y or any buttons besides the analog sticks. Same issue when i use my ps4 controller

**Comment by blueknight64** [comment]
map the controllers first, if it does not work, tell us

**Comment by github10omar** [comment]
> I first used my Xbox One controller to play, moves around pretty good but, i can't use my A, B, X, Y or any buttons besides the analog sticks. Same issue when i use my ps4 controller

I sued mine, it works fine. Use USB cables then...

**Comment by luphoria** [comment]
Check https://gamepad-tester.com/ -- you have to map the movements to seemingly random numbers, this tool provides that info
