### ISSUE TITLE
[BUG] Google Chrome throws a privacy error on both 60fps.sm64js.com and vanilla.sm64js.com

### ISSUE THREAD

**Issue by BlueStaggo** [sm64js/sm64js#310]
#### How to reproduce:
Go to either 60fps.sm64js.com or vanilla.sm64js.com.

#### What happens?
Google Chrome will throw you this error message:

![image](https://user-images.githubusercontent.com/71090710/113559870-0436e080-95fa-11eb-91eb-33dd837e2f96.png)

#### Version:
Chrome: 89.0.4389.114 (Official Build) (64-bit)
Windows: Windows 10 Home 1909 x64

#### Extensions:
* No extensions are causing it.

**Comment by github10omar** [comment]
Try using Edge, nothing seems wrong there.

**Comment by AgentXLP** [comment]
its fixed now
