### ISSUE TITLE
me

### ISSUE THREAD

**Issue by sme64** [sm64js/sm64js#314]
get rid of the mute feature

**Comment by luphoria** [comment]
no

**Comment by sme64** [comment]
getting rid of it and if you say no to me again toast I will eat you

**Comment by sme64** [comment]
luphoria shut up

**Comment by sme64** [comment]
I'm not being mean it's just that feature is really annoying and who cares about spam because I will eat you cos you are toast

**Comment by sme64** [comment]
I am not being mean

**Comment by sme64** [comment]
I just don't like that feature

**Comment by luphoria** [comment]
![816127570067587123.png](https://user-images.githubusercontent.com/60309933/113946374-e7eb9d00-97cd-11eb-9076-6b801a037bcb.png)

**Comment by AgentXLP** [comment]
this kid got me dying 😂

**Comment by AgentXLP** [comment]
@luphoria haha funny bread!1!1

**Comment by AgentXLP** [comment]
> get rid of the mute feature

Too bad, you were spamming your scratch
