### ISSUE TITLE
get rid of the mute feature

### ISSUE THREAD

**Issue by sme64** [sm64js/sm64js#315]

**Comment by luphoria** [comment]
Nah ill pass

**Comment by AgentXLP** [comment]
Nah ill pass

**Comment by sme64** [comment]
good creators will get rid of the feature

**Comment by sme64** [comment]
are you still here

**Comment by luphoria** [comment]
guess im a bad creator ![827528407154950175.gif](https://user-images.githubusercontent.com/60309933/113946485-2d0fcf00-97ce-11eb-95c4-6ef85123d8ea.gif)
