### ISSUE TITLE
speak with me

### ISSUE THREAD

**Issue by sme64** [sm64js/sm64js#317]

**Comment by luphoria** [comment]
![771519720720564224.png](https://user-images.githubusercontent.com/60309933/113946549-4ca6f780-97ce-11eb-9143-5a8906640c9d.png)

**Comment by AgentXLP** [comment]
my face when issue spam 😒

**Comment by sme64** [comment]
weird face like he's going eeeeeeeeeeeeeeeeee

**Comment by sme64** [comment]
talking about that face that tost made

**Comment by luphoria** [comment]
![813119273408790529.gif](https://user-images.githubusercontent.com/60309933/113947108-89bfb980-97cf-11eb-8b4b-9b3ed0fc1c7b.gif)
