### ISSUE TITLE
i clicked enter and it didnt work

### ISSUE THREAD

**Issue by faty2848** [sm64js/sm64js#324]
i had no other inputs exept for mouse and i did click on the running game on the start select screen and the key input was set to enter = start so yae it kinda brokin pls maybe fix or maybe mouse did it but idk

**Comment by luphoria** [comment]
Maybe clear your cache? You may need to re submit your ROM

**Comment by AgentXLP** [comment]
Yes, do what @luphoria said, if that doesn't work check if it is connected to the server in the first place.

**Comment by smm2mickeyink** [comment]
> Maybe clear your cache? You may need to re submit your ROM

no if u just go to a new tab and type the sm64js website link again it will get fixed without needing to clear your cache. also if he scrolled down he would have noticed he actually disconnected :trollface:

**Comment by luphoria** [comment]
closing inactive issue
