### ISSUE TITLE
Pressing any button on my DS4 controller instantly freezes the game.

### ISSUE THREAD

**Issue by RetroGEO** [sm64js/sm64js#325]
Using Input Mapper with my Dualshock 4 controller. Already been through binding the controls based on the button numbers given by windows, but if I hit any buttons the game instantly freezes permanently. Works fine with keyboard and mouse.

**Comment by AgentXLP** [comment]
sm64js doesn't need any special drivers for controller input on Windows, I use a Dualshock 4 controller myself and I don't have DS4Windows.

**Comment by eros71-dev** [comment]
Same here, using the DS4 as it is should work just fine
