### ISSUE TITLE
Won't show .z64 files on chromebook

### ISSUE THREAD

**Issue by Dark-Tails53** [sm64js/sm64js#327]

**Comment by luphoria** [comment]
???

**Comment by AgentXLP** [comment]
Another seemingly useless userside issue report

**Comment by justabluemouse** [comment]
That's not really the developers fault, that's just a problem with your laptop. try opening the .z64 file on a different platform.

**Comment by luphoria** [comment]
Still confused, can you elaborate? What do you mean?

**Comment by luphoria** [comment]
No response weeks later. Closing
