### ISSUE TITLE
Drowning

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#336]
Whenever I drown the game crashes instantly

**Comment by justabluemouse** [comment]
Yeah, it's true. Was this fixed in the update?

**Comment by luphoria** [comment]
On vanilla or MMO??

**Comment by luphoria** [comment]
Confirmed to still exist in mmo

**Comment by justabluemouse** [comment]
Aw. Hopefully, that'll get fixed in a future update.

**Comment by luphoria** [comment]
is this issue still around? as Luigi i was able to drown

**Comment by justabluemouse** [comment]
Nope, it's fixed now
