### ISSUE TITLE
[Not an issue, I know but] Can we revive XP? or is that planned in a future update?

### ISSUE THREAD

**Issue by justabluemouse** [sm64js/sm64js#338]
Hello SM64JS Devs. 

Basically, I was wondering if the experience points & leveling system was going to come back? And if it was, can we have an estimated date? I know you guys are already coding a lot, but I'd love to see it come back eventually. You don't know how torturous it is to constantly see "Lvl #1" hanging over my head.

**Comment by blueknight64** [comment]
probs gonna get re-added, but they are gonna work on the basic problems like shaping the core of the game first before going back to things like these

**Comment by luphoria** [comment]
> probs gonna get re-added, but they are gonna work on the basic problems like shaping the core of the game first before going back to things like these

Not necessarily, thats the work being done on vanilla.

**Comment by justabluemouse** [comment]
Ah, ok, that makes sense, thanks for the clarification
