### ISSUE TITLE
Weeks, and the flags still have no collision

### ISSUE THREAD

**Issue by justabluemouse** [sm64js/sm64js#344]
You guys are probably already working on this, but when will the flag collision be implemented into the game again? At one point, it just stopped, and now, as an example, the red flag is still stuck in the air around the middle of the map of BoB. Hopefully, this will get patched in the next update.

**Comment by PSIPowerhouse** [comment]
There is something I have to say about the flags too.
In said BoB, I can't see the flag where it says its located on the map, instead it's further over where the bubbles usually are instead of on top of the bush near the spawn

**Comment by AgentXLP** [comment]
It works locally. Strange that it doesn't work on the website.

**Comment by PSIPowerhouse** [comment]
it worked once on CTF Race map, but now i you cant get the flags any more
