### ISSUE TITLE
Paste Color Code Doesn't Save After Reload

### ISSUE THREAD

**Issue by vierdivi** [sm64js/sm64js#350]
I created my color code in m64mm3 so i paste my color code into the paste color code box of sm64js, but when i do that, it doesn't save it when i reload to go to a new map or something like that so i have to keep pasting it. Check the GIF below to see what i mean.
![a](https://user-images.githubusercontent.com/78662497/118505574-c5607400-b6e9-11eb-906a-17dbcd4b66c5.gif)

**Comment by AgentXLP** [comment]
Most likely the color code doesn't get saved unlike the manual sm64js one

**Comment by luphoria** [comment]
Temporary fix, but to fix this just move an ambient slider back and forth in the on-site customizer, this will refresh the save.
Good report though.

**Comment by vierdivi** [comment]
that is what i sometimes do but will this be fixed?

**Comment by luphoria** [comment]
Yes, at some point i will fix this. Just do that for now.
