### ISSUE TITLE
Camera resets collision detection

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#351]
I was playing on Hazy Maze Cave earlier and I fell through a certain platform. I was concerned as to why this was so I tried to stand on the platform again. I stood for like 3 seconds then when my camera clipped into the wall I fell again. That's when it hit me. The collision was getting reset when the camera will clip into the wall. (See the gif below)
![floor](https://user-images.githubusercontent.com/75381767/118702900-1ef49b80-b7db-11eb-914c-bf159f29bc5c.gif)

**Comment by AgentXLP** [comment]
The camera normally shouldn't clip out that wall, it unloads collision due to the rooms system.
