### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#353]
Add better kart physics (they are kinda very bouncy, and sadly no drift boost...)

**Comment by PSIPowerhouse** [comment]
I agree. When jumping on a slippery slope in the kart, you bounce all the way down the slope.

**Comment by Someone567123** [comment]
Yes, and it's even worse when you fall from great heights tbh

**Comment by AgentXLP** [comment]
@Someone567123 ok

:trollface:

**Comment by Someone567123** [comment]
thank you agent x

**Comment by AgentXLP** [comment]
> thank you agent x

actually no :trollface:

**Comment by Someone567123** [comment]
ok

**Comment by AgentXLP** [comment]
actually yes

**Comment by Someone567123** [comment]
kart physics updated, nice
