### ISSUE TITLE
[Another Suggestion]

### ISSUE THREAD

**Issue by Someone567123** [sm64js/sm64js#354]
Fix the token problem!

I am aware that the tokens we had like a couple of months ago don't work, but i think you should rework google login to work with it exclusively. I know the "new" admin panel checks for the In-Game Admin role for discord login, but why not do it another way for google accounts? 

Same way to login as before, /signin [Insert Secret Admin Token], BUT, it detects who uses it. My idea was that if you used the token for the first time, it registers to the google account, and after 5 uses/logins, it "locks" the token to your account, meaning only you can use it. By "locks", i mean that it is registered and now only you can sign in, to avoid stolen tokens. If someone else uses the token that has already been registered to an account, it _should_ give them an error screen.

Again, just a suggestion, and you don't really have to do this. (and no, this isn't me trying to do an SMB575 thing, this could be useful.)

**Comment by luphoria** [comment]
Most of the reason we redid the whole api was for discord integration specifically. So no.

**Comment by Someone567123** [comment]
mhm ok
