### ISSUE TITLE
sm64js account help

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#364]
Hi. I am contacting to appeal a ban. I know it is possible on Discord but after the way I was pounded on I would rather keep that name clean. I was falsely accused of "smb575" and was banned shortly after. I told them they had the wrong person and I got banned anyway. Thank you in advance for reading this. Please take your time as I'm not in a rush and have a great day!

**Comment by luphoria** [comment]
decision is final. many _private_ factors were taken into account for the ban, on top of the very very hard to dismiss evidence of a shared ISP+JD+behaviour.

your ban will not be lifted

**Comment by ghost** [comment]
I just love this game and wanted to play. I had no idea anything I was doing was bad. Im not the guy you say I am.

**Comment by AgentXLP** [comment]
Pretty much everything lines up and ties perfectly towards you being SMB575, the _956_ in your name makes it more suspicious, we have taken grammar, vocab, actions and more into consideration and this ban was for that reason.

**Comment by luphoria** [comment]
Hello,

Your account was disabled for violating our Rules or Community Guidelines. We’ve reviewed and have confirmed this violation, and we will not be reinstating your account.

**Comment by ghost** [comment]
Am I still able to host the game myself and play vanilla? I don't want to be banned from those options too just because you think I'm someone else.

**Comment by Cooliokid956** [comment]
You are only banned from the MMO, you are still able to access everything else that isn't online.

**Comment by ghost** [comment]
Well im glad to hear the admins arent _that_ corrupt. Thank you Cooliokid

**Comment by luphoria** [comment]
IIRC, custom rooms are currently broken; however, no, you will not be prevented from accessing off-main-server games.

**Comment by AgentXLP** [comment]
> Well im glad to hear the admins arent _that_ corrupt. Thank you Cooliokid

Go play vanilla SpookyMarioBroth575

**Comment by ghost** [comment]
Please...im not him!

**Comment by ghost** [comment]
I just wanna play

**Comment by Cooliokid956** [comment]
LMAO HE'S BACK

**Comment by Cooliokid956** [comment]
HI SMB

**Comment by ruffaldabaoth** [comment]
SMB makes new account 😳

**Comment by ghost** [comment]
@NTBeta Indeed I did. Im sorry you had to see me go out this way. But I am sick and tired of this repeated history. I was a person before smb yes. And a person before that account as well. This is the 3rd time this has come upon me. And I'm done with it. I will get revenge and show them and I will not let this ever happen again. Im no longer after the people and _fake_ care everybody gives me. And no, this is no roleplay. This is me ending the timeline. Once I end it, I will finally be at peace. It was all an act, I realize this now. You guys never liked me! No matter what I did you always had to find something wrong with me. It happens every time. You guys were never my friends, you just _acted_ like them. Whether I was kind, entertaining, mean, forgiving- no. You guys never cared. Nobody ever has, nor ever will. So yes I did create a new account. And I wont stop until they understand my pain!

**Comment by luphoria** [comment]
![Screenshot_20210607-175521.jpg](https://user-images.githubusercontent.com/60309933/121154961-004b5880-c80d-11eb-8203-c753af42ef28.jpg)

**Comment by ruffaldabaoth** [comment]
Just DM me about this, there's no need for revenge.

**Comment by Cooliokid956** [comment]
guess he’s no longer a carnival or any of that, probably a shitshow now

**Comment by AgentXLP** [comment]
> Just DM me about this, there's no need for revenge.

mf has no willpower at all, hes like a child, he cannot resist him self to be a carnival and continue to plague sm64js knowing fully he is fucked no matter how hard he tries.

**Comment by justabluemouse** [comment]
> @NTBeta Indeed I did. Im sorry you had to see me go out this way. But I am sick and tired of this repeated history. I was a person before smb yes. And a person before that account as well. This is the 3rd time this has come upon me. And I'm done with it. I will get revenge and show them and I will not let this ever happen again. Im no longer after the people and _fake_ care everybody gives me. And no, this is no roleplay. This is me ending the timeline. Once I end it, I will finally be at peace. It was all an act, I realize this now. You guys never liked me! No matter what I did you always had to find something wrong with me. It happens every time. You guys were never my friends, you just _acted_ like them. Whether I was kind, entertaining, mean, forgiving- no. You guys never cared. Nobody ever has, nor ever will. So yes I did create a new account. And I wont stop until they understand my pain!

edgy 14-year-old moment
