### ISSUE TITLE
Cannot remap c-axis in vanilla sm64js on controller

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [sm64js/sm64js#366]
Whenever I try to change the c-axis for my gamepad, in vanilla sm64js, it doesn't change in the game, even if I click save controls. Remapping all the other buttons works, just not the c-axis.

**Comment by AgentXLP** [comment]
Sticks are bound to the left and right sticks and a way to change them doesn't make sense to me and won't be worked on

**Comment by ego-lay-atman-bay** [comment]
It's just that the controller I use (usb switch controller) uses axis 3 and 6 for the right stick. I haven't tested it in a while, so I don't know if it has already been fixed.
