### ISSUE TITLE
One final(?) message

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#367]
Before you say anything, I come unarmed. No strings attached, no motives, nothing.

I have been thinking about why I am so attached to this community. I have evaluated all my decisions and why I was rejected. For a while, I didn't quite understand where I went wrong. But now I truly realize. I have made so many poor choices, each one slowly pushing me away from you guys. I have cooled down over everything that has happened. I was attached because you guys had treated me better than anyone else did. Both inside and outside of personal life. The damage I have done is far beyond repair. And although it may be too late for forgiveness, it is never too late for apologies. Thank you guys for the way you treated me. Both good and bad. You guys helped knock the sense in me. I am truly sorry for what I did, for real this time. I don't want to be the circus anymore. To do that, I have to leave this community. I will be leaving the game as well so my undercover account will go missing. If there is anything else I can do to make it up to you, please let me know. This account will disappear in 24 hours.

**Comment by luphoria** [comment]
cool bye
