### ISSUE TITLE
What is the branch used in the website

### ISSUE THREAD

**Issue by fox3000foxy** [sm64js/sm64js#376]
I searched and tested somes branch but i dont font which is used in https://sm64js.com/

**Comment by luphoria** [comment]
MMO is the branch used in the main site. The site is currently not updated with the new look

**Comment by AgentXLP** [comment]
> I searched and tested somes branch but i dont font which is used in https://sm64js.com/

The CSS uses multiple fonts, the font in CSS format is -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"

**Comment by fox3000foxy** [comment]
Ok thanks.
Did you know why I cant connect to a server deployed on localhost?
All my connections requests are rejected !

**Comment by fox3000foxy** [comment]
> > I searched and tested somes branch but i dont font which is used in https://sm64js.com/
> 
> The CSS uses multiple fonts, the font in CSS format is -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"

I dont search css

**Comment by fox3000foxy** [comment]
I want just to play in localhost server but I cant bcs all connections are rejected

**Comment by luphoria** [comment]
You need to separately clone and run the server. It is in the sm64js account

**Comment by fox3000foxy** [comment]
I do it but isn't work...
It dont purpose me to login...
