### ISSUE TITLE
First person?

### ISSUE THREAD

**Issue by github10omar** [sm64js/sm64js#378]
I mean, first person might be cool.

**Comment by CyberNutz** [comment]
dev only tool idk if it will become public

**Comment by PSIPowerhouse** [comment]
I'd like it too

**Comment by justabluemouse** [comment]
would be interesting, for sure, but _obviously_ they'd have to add weapons(ex. A-Koopa 47)

**Comment by AgentXLP** [comment]
Might add, might not, probably won't
Idk yet.

**Comment by AgentXLP** [comment]
0x got it working for developers.
