### ISSUE TITLE
Custom Game

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#380]
The custom game has never worked, Why not?

**Comment by luphoria** [comment]
it worked for a very minor amount of time, however when the server's backend was changed to RS, custom games were simply never re-implemented. It's the same story with flags

**Comment by CyberNutz** [comment]
its dieded

**Comment by lolxdtyuir69** [comment]
# GET RID OF MUTE FEATURE!!! 🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕

**Comment by lolxdtyuir69** [comment]
# I SAYD GET RID OF IT 🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎🤬🤬🤬🤬🖕🖕🖕👎👎👎👎

**Comment by GETRIDOFTHEFOKINMUTFETUR** [comment]
# @luphoria @sm64js @everyone yuo suKC ANN ANMAL P$%$Y!!!! F^%KCING N#^SGGERS!!  [I SAYD TO GET RD OF THE FOKCIN MUTT FETAURE!!!!!!!! IDTIOS!!! NT$GGERS!!!!!!!!! B!THC CU-_SMLUt!!!!!!👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠v👎🖕👎🤬😾👎🤬🖕👹👺🤬👎🤢🖕👿👿🤬🖕👹👹🔫🔫🔫😡😡😈😾👎👺👺👿👿😤😤😤😤😤😠😠😠😠](https://www.youtube.com/watch?v=iA8iaum8HOg)

**Comment by ImaginaryNeon** [comment]
can you un-kill them so I can play on the new map?
