### ISSUE TITLE
cant long jump to left and downleft

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#4]
that

**Comment by sm64js** [comment]
hmm, not sure I understand.
are you saying if the camera was fixed facing north. You can't long jump when you are running west and southwest?

**Comment by Cooliokid956** [comment]
yes
exactly

**Comment by sm64js** [comment]
That's odd, that works for me on keyboard and controller.  I can't reproduce the behavior.

**Comment by Cooliokid956** [comment]
huh, then it has to do with me being on a chromebook

**Comment by sm64js** [comment]
Hmmm, maybe, still seems strange. I'll see if I can try on chrome OS sometime.
