### ISSUE TITLE
Crashes when wall jumping off of the elevator wall to the left

### ISSUE THREAD

**Issue by CyberCat30** [sm64js/sm64js#42]
title says it all

**Comment by sm64js** [comment]
the elevator? do you think you could get a screenshot or video?
Thanks

**Comment by CyberCat30** [comment]
Normally, there are elevators to the left of the first bridge. I wall jumped off of the wall they move on up to the chomp area. The game crashed the first 2 times I did this. Never happened afterward. It was during the stress test and since it happened in the same place twice in a row, I thought it was an actual issue. In hindsight, it was probably just a coincidence considering it was during the stress test. I should have closed this myself.

**Comment by CyberCat30** [comment]
> the elevator? do you think you could get a screenshot or video?
> Thanks

Normally, there are elevators to the left of the first bridge. I wall jumped off of the wall they move on up to the chomp area. The game crashed the first 2 times I did this. Never happened afterward. It was during the stress test and since it happened in the same place twice in a row, I thought it was an actual issue. In hindsight, it was probably just a coincidence considering it was during the stress test. I should have closed this myself.
