### ISSUE TITLE
Switching from full window mode to full screen mode messes up aspect ratio

### ISSUE THREAD

**Issue by sicnarfnarf** [sm64js/sm64js#44]
Aspect ratio is messed up when doing the following:

1. Enter full window mode (the game stretches to fit the window instead of 4:3 aspect ratio)
2. Exiting full window mode with esc
3. Enter full screen mode, and the game keeps the same aspect ratio from full window mode instead of 4:3 aspect ratio

Without entering full window mode, full screen mode keeps 4:3 aspect ratio

**Comment by Whoblue579** [comment]
This was already fixed, but I would like to see an option to render in 16:9

**Comment by Whoblue579** [comment]
That wouldn't be hard to implement, (unless the pass the render resolution through 2M functions) I'm gonna try to do it
