### ISSUE TITLE
Textures are missing.

### ISSUE THREAD

**Issue by EmeraldWolfYT** [sm64js/sm64js#46]
Every time I play the game, the terrain appears black, and same with the sky, and players have textures, but their faces are missing, and their hat is blank. 
![image](https://user-images.githubusercontent.com/73445510/97119294-37855300-16dd-11eb-971e-d40ead769710.png)

**Comment by luphoria** [comment]
You need to clear your cache. You submitted the wrong ROM. You need a US z64 rom

**Comment by EmeraldWolfYT** [comment]
okay thanks!

**Comment by luphoria** [comment]
Please close the issue, I cannot myself

**Comment by EmeraldWolfYT** [comment]
i forgot, how do you get a z64 rom again? and yeah i will close it

**Comment by luphoria** [comment]
for legal reasons, i cannot provide information on this. However the ROM file extension needs to end in .z64, you likely have one that ends in .n64

**Comment by EmeraldWolfYT** [comment]
okay also how do i submit another ROM in the site?

**Comment by luphoria** [comment]
type `localStorage.removeItem('sm64jsAssets')` into the JavaScript console

**Comment by EmeraldWolfYT** [comment]
alright
thanks!
