### ISSUE TITLE
Chat not showing

### ISSUE THREAD

**Issue by SJG4** [sm64js/sm64js#47]
Hello, so I've been trying to send a message or trying to see a message but there is nothing there
![image](https://user-images.githubusercontent.com/73476067/97171377-bde47800-1763-11eb-9580-317cb7a69560.png)

**Comment by luphoria** [comment]
Chat is temporarily disabled, it should be more clear however

**Comment by SJG4** [comment]
I see

**Comment by sm64js** [comment]
Chat has been re-enabled, however more improvements coming soon
