### ISSUE TITLE
Ban appeal: unban for reason

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#495]
Hi! im the cool guy devs! you banned me from the sm64js! please unban me! it was only a prank! i pranked him i swear! please unban me! i know i joked dirty but i joked! it was not real! so please unban me! PLEASE!
![20210830_205138](https://user-images.githubusercontent.com/89794467/131364799-07158fd5-c151-41aa-8a2f-ab87a03986d9.png)

**Comment by MasterNama17083** [comment]
I knew. He is alt called "kiver"

**Comment by MasterNama17083** [comment]
![20210830_205058](https://user-images.githubusercontent.com/80534869/131364985-0f3eb0d1-47cb-4eb2-86b8-4996e59ed257.png)
Proof

**Comment by MasterNama17083** [comment]
Hey @yasin1389

**Comment by ghost** [comment]
hey master nama

**Comment by ghost** [comment]
> Hey @yasin1389

hey
