### ISSUE TITLE
SM64JS Main Page Issue: Broken Discord Icon

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#496]
I know. This discord icon was corrupted.
![image](https://user-images.githubusercontent.com/80534869/131454843-b0653db0-5bca-4188-8d89-04add827edaa.png)

**Comment by blueknight64** [comment]
probably your internet

**Comment by github10omar** [comment]
no i have good internet, still happens tho

**Comment by luphoria** [comment]
Issue recognized. Many regular players do not see this because of the icon being cached. 
Discord no longer allows cross-origin requests for that icon. I will fix this later today 🍞🤞

**Comment by blueknight64** [comment]
yeah

**Comment by luphoria** [comment]
was too busy to do things today. By "today" i meant asap. LOL

**Comment by luphoria** [comment]
Never mind -- issue already fixed, just not deployed to sm64js.com
