### ISSUE TITLE
add reset button

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#5]
Many times the game blacks out, and then I have to refresh the page to start again, and re-extracting the assets takes a while, and I have to keep doing it every single time the game blacks out, so I'm asking if you can add a reset button to restart the game without refreshing the page.

**Comment by sm64js** [comment]
Agreed! Reset button is important. It's on my to do list, and I'll do it soon.

I am also planning client side rom cacheing, eventually.

I am curious though, I know there are various things I can do get the game to blackout (mostly hitting blocks of code that aren't implemented yet).  But I am wondering what things you have been doing that have triggered that.  And when that happens see if there is an error being thrown in console.

**Comment by Cooliokid956** [comment]
what usually happens is that I go to the edges of the world, jump on edges of holes like the cannon hole, the vanish cap course entrance and exit, then the game would lag and black out
also, if I understand what you mean by rom caching, as in to keep the extracted assets in cache, then the reset button wouldn't even be needed! though the asset extraction would have to be done when big updates come around

**Comment by sm64js** [comment]
"what usually happens is that I go to the edges of the world, jump on edges of holes like the cannon hole, the vanish cap course entrance and exit, then the game would lag and black out"

Okay yea, I have not dealt with the case where it can't find a "floor" - so just have it throw an error and crash the game.

aha yep, also haven't implemented ceiling collisions either

"also, if I understand what you mean by rom caching, as in to keep the extracted assets in cache, then the reset button wouldn't even be needed! though the asset extraction would have to be done when big updates come around"

yep your understanding is correct, and yea less need for reset button, but I plan to add it anyways.

And you should be able to access the browser console, I am not super sure how to do on a chrome book though

**Comment by Cooliokid956** [comment]
I should, but its a managed chromebook, the button is greyed out

**Comment by sm64js** [comment]
I have added client side asset caching and a reset button!

The reset button just reloads the page with an autostart flag and works because assets are cached.

**Comment by Cooliokid956** [comment]
yay 
happy now
