### ISSUE TITLE
all the entities are replaced with marios

### ISSUE THREAD

**Issue by VexianEmpire** [sm64js/sm64js#50]
maybe the cause of #49 is that there are so many marios

**Comment by sm64js** [comment]
I am not sure what you mean? could you share a picture?

**Comment by smm2mickeyink** [comment]
@sm64js same

**Comment by sm64js** [comment]
can someone explain the issue here? I do not understand @VexianEmpire @smm2mickeyink

**Comment by smm2mickeyink** [comment]
> can someone explain the issue here? I do not understand @VexianEmpire @smm2mickeyink

what im saying is i agree what ur saying about the issue vexianempire is having
