### ISSUE TITLE
The Textures Are Broken

### ISSUE THREAD

**Issue by Contra7ell** [sm64js/sm64js#51]
When i play the game, the Textures are glitched,
The Background in the "Press start" Screen is gliched,
In Bomb Omb Battlefield the Trees and Fences are glitched,
Mario's face, Hat Logo and Bottons are Glitched,
And the Map is Completelly Black.
(Side Note: The Swinging Bridge and The Rotating Platforms Arent there but i think they Arent implemented into Sm64js yet)

**Comment by Contra7ell** [comment]
Heres a Screenshot
![Screenshot_44](https://user-images.githubusercontent.com/73503634/97237592-33813000-17c6-11eb-9afd-17989af6710f.png)

**Comment by sm64js** [comment]
Incorrect wrong rom file, you need to get a z64 rom, then clear your browser cache, then reinsert z64 rom.

**Comment by Contra7ell** [comment]
Thanks

**Comment by Contra7ell** [comment]
wait, how do i change the rom?
