### ISSUE TITLE
Changing skin disconnects from server

### ISSUE THREAD

**Issue by CaptainGame17** [sm64js/sm64js#52]
Every time I go to change my player skin (a premade one or a custom one) the game instantly loses connection.

**Comment by luphoria** [comment]
Is anything logged in the console? check for errors

**Comment by smm2mickeyink** [comment]
for me sometimes it instantly freezes the game

**Comment by sm64js** [comment]
Does this still happen? @CaptainGame17 @smm2mickeyink

**Comment by smm2mickeyink** [comment]
> Does this still happen? @CaptainGame17 @smm2mickeyink

not anymore for me it stopped crashing once there was less players

**Comment by sm64js** [comment]
Well, I also updated some code that may have made it stop crashing.  I want to know if it comes back or not
