### ISSUE TITLE
Other players can be pushed through walls by bouncing on them

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#54]
Some person was idle so i bounced on them and they clipped through a random wall.

**Comment by sm64js** [comment]
This might cause crashes/bugs, so I am interested figuring out how this works. I'll give it a try, but might need more information on how to reproduce.

**Comment by smm2mickeyink** [comment]
> This might cause crashes/bugs, so I am interested figuring out how this works. I'll give it a try, but might need more information on how to reproduce.

ok

**Comment by smm2mickeyink** [comment]
> This might cause crashes/bugs, so I am interested figuring out how this works. I'll give it a try, but might need more information on how to reproduce.

its works if you are disconnected so that no one moves... it makes it easier or while they are still moving the same direction
