### ISSUE TITLE
can we add mods to the game    

### ISSUE THREAD

**Issue by eeveeboi** [sm64js/sm64js#564]
i was trying a mod and it did not work   can you add mods to the sm64js pls

**Comment by eeveeboi** [comment]
pls

**Comment by PSIPowerhouse** [comment]
This would be nice, I like this idea

**Comment by eeveeboi** [comment]
thanks

**Comment by eeveeboi** [comment]
very cool

**Comment by AgentXLP** [comment]
What do you mean by mods?

**Comment by luphoria** [comment]
already closed this issue previously; please do not attempt to make another
