### ISSUE TITLE
Please un-commence the "no u" known as banning me.

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#565]
I can't use discord on my chromebook and my tablet is currently unavailable, however I still can't access the discord server regardless, so I have no other way to appeal my ban. Also I was banned for "joking about suicide" (just saying "I respawned" is boring AND I tried to avoid saying the word suicide (i.e. I would say "I got stuck in the wheel of softlock, so I had to SD to get out.")) and for saying "So long, Gay Bowser" (I would've thought the sm64js community would be the **least** likely to get mad at me for making a reference to sm64 (I know it's actually "So long, King Bowser", but "So long, Gay Bowser" is much more iconic)).
Also, if you are mad at me for making alternate accounts, you are mad at me for wanting to **play the video game** and not just be sitting in class with nothing to do (When, keep in mind, I have ADHD _and_ Autism).
![Screenshot 2021-10-22 11 08 46 AM](https://user-images.githubusercontent.com/92883596/138491730-a4797402-5a20-41ce-b70d-e40dfc4d3995.png)

**Comment by AgentXLP** [comment]
edgy zalgo text moment

My friend was literally having suicidal thoughts and you fucked with him while that was happening
You made an alt to evade a mute
Constantly joking about suicide in-game
Called a level gay insultingly after people were talking about some glitches it had

You aren't being unbanned, too bad.
