### ISSUE TITLE
Starman Fortress's collision is broken.

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#566]
https://user-images.githubusercontent.com/92883596/138325601-9e68b2aa-5ea9-47e7-80d1-79b71f55ae76.mp4

also the wheel thing can cause a softlock that can only really be fixed by respawning. I have a video of it, but it's more than 10 MB or whatever.

**Comment by PSIPowerhouse** [comment]
XDDDDDDDDDD I never had this happen to me

**Comment by AgentXLP** [comment]
Map will most likely be remade in the future. Shame you won't be around to see it

**Comment by ImaginaryNeon** [comment]
![2022_03_22_0ku_Kleki](https://user-images.githubusercontent.com/92883596/159540688-60d26cf8-9919-4be1-8412-0efdf6d164de.png)

Are you, without a doubt, 100% certain that I will, in fact, be absent at the approximate point in time of which Starman Fortress is to be the recipient of a remake? Because,

`if(accuracy != "100%"){
accuracy = "50%";
};`

**Comment by AgentXLP** [comment]
> ![2022_03_22_0ku_Kleki](https://user-images.githubusercontent.com/92883596/159540688-60d26cf8-9919-4be1-8412-0efdf6d164de.png)
> 
> Are you, without a doubt, 100% certain that I will, in fact, be absent at the approximate point in time of which Starman Fortress is to be the recipient of a remake? Because,
> 
> `if(accuracy != 100%){` `accuracy = 50%;` `};`

Your alts are like REALLY easy to spot lol, good luck trying to pull more ban evasion shit :)

**Comment by ImaginaryNeon** [comment]
> Your alts are like REALLY easy to spot lol, good luck trying to pull more ban evasion shit :)

My last alt for the game was Lonk like 5-7 months ago or so. Any ones you think you found after that weren't even mine :lul:.

Also, have you heard of unblockers by any chance?

**Comment by ImaginaryNeon** [comment]
Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.

**Comment by PSIPowerhouse** [comment]
> Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.

Damn

**Comment by PSIPowerhouse** [comment]
> > Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.
> 
> Damn

Honestly you should stop tryna evade the ban. It's not worth it.

**Comment by ImaginaryNeon** [comment]
> > > Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.
> > 
> > 
> > Damn
> 
> Honestly you should stop tryna evade the ban. It's not worth it.

I kinda sorta like playing the video game.

**Comment by AgentXLP** [comment]
> Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.

Also, by then, we will most likely be using a Node JS implementation of the MMO server, which blocks vpns

Checkmate, Bad attempt of a villain.

**Comment by ImaginaryNeon** [comment]
> ### Checkmate, Bad attempt of a villain.

Look, at this point, it's not even an attempt, it's just what you perceive me as. Your perception is nowhere near flawless, but then again, I'm the "horrid" one here according to you. Trying to play a really cool video game while bored is completely different from sitting in an overly pointy chair whilst laughing maniacally.

(Also you greatly underestimate my stubbornness.)
> (And yes, I saw your comment about me in the Maze95js code or whatever, which only further proves my point about your biased perception of me. Also, why are those even there? Are they used as placeholders or do you simply hate me _**that**_ much?)

**Comment by uuphoria2** [comment]
> > Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.
> 
> Also, by then, we will most likely be using a Node JS implementation of the MMO server, which blocks vpns
> 
> Checkmate, Bad attempt of a villain.

imagine you make a fork and actually add a node server implementation tho agent (would be cool)

**Comment by ImaginaryNeon** [comment]
> > > Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.

> (irrelevant)

why did you have to remind me of this

**Comment by uuphoria2** [comment]
> > > > Also, by next school year, I should be able to access a VPN. Checkmate, Agent X.
> 
> > (irrelevant)
> 
> why did you have to remind me of this

Reasons :trollface:
