### ISSUE TITLE
SM64JS Vanilla: Inside Castle (Random Corruption)

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#575]
Ok. I played Vanilla version, Still what happening?!

- I think. I imported SM64 ROM already

**NOTE: This video is real footage here. This is not a joke!**
I choosing for `"Castle"` level select. It still 2 random weird glitches???
https://user-images.githubusercontent.com/80534869/138561976-c739db16-499f-4265-b715-3ac48c3d6a86.mp4

Please fix this.

**Comment by AgentXLP** [comment]
Known

**Comment by Cooliokid956** [comment]
for some reason, the site keeps focus on the level select box, so pressing keys will select the level with the letter you pressed
easiest way to fix this yourself is to click outside of the level select box after choosing a level

**Comment by PSIPowerhouse** [comment]
True, @Cooliokid956.
I've also seen the corrupted princess room but no other glitch
