### ISSUE TITLE
The site literally doesn't work

### ISSUE THREAD

**Issue by Nintendelta** [sm64js/sm64js#578]
I was casually playing when I learned that i could use a Luigi model. Upon switching to Luigi, my game freezes. I could see new chat messages but I couldn't send my own. I refreshed the page went to it in a new tab, restarted the browser... I feel like I've tried everything at this point. I have attached a picture with an inspection tab. Please fix my issue as soon as possible. https://drive.google.com/file/d/1iPghDnOxSMKf_JodkFYoX9WLZhyDJSCl/view?usp=sharing

**Comment by luphoria** [comment]
Try flushing your cache... it looked like that for me originally too

**Comment by Nintendelta** [comment]
> Try flushing your cache... it looked like that for me originally too

How am I supposed to do that?
Edit: I looked it up and it didn't work, do I clear my whole browsing history?

**Comment by AgentXLP** [comment]
```js
Object.keys(window.myMario.skinData).forEach((skinType) => {
        localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
})
```

**Comment by Nintendelta** [comment]
> ```js
> Object.keys(window.myMario.skinData).forEach((skinType) => {
>         localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
> })
> ```

Thank you for the code, but where do I put it?

**Comment by Mario64Lol** [comment]
We have the same things bro.

**Comment by luphoria** [comment]
> > ```js
> > Object.keys(window.myMario.skinData).forEach((skinType) => {
> >         localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
> > })
> > ```
> 
> Thank you for the code, but where do I put it?

Put it in your JavaScript console. you can find it by the keybind ctrl+shift+i and then hit "Console" if it isn't already there
