### ISSUE TITLE
Issue with loading page after google sign in (already identified where it's happening in code)

### ISSUE THREAD

**Issue by fabzter** [sm64js/sm64js#581]
After signing in  and reloading the page, the only thing i get is a blank screen;
![image](https://user-images.githubusercontent.com/135494/139285369-c7a98678-1764-483a-840b-df24c899ffb9.png)

After inspecting the page and pretifyng the generated javascript, I found the error is happening here;
![image](https://user-images.githubusercontent.com/135494/139285589-53e6176c-8067-45f0-8fd8-bae89f566e38.png)

If it's not clear, what is happening is that c value is `"undefined"` as a string, when it should be the actual `undefined `value.
Will make a PR if I have time between jobs.

**Comment by luphoria** [comment]
We have a fix for this already -- it'll be deployed to the site soon. Feel free to PR though

**Comment by AgentXLP** [comment]
```js
Object.keys(window.myMario.skinData).forEach((skinType) => {
        localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
})
```
run this in the console to fix
