### ISSUE TITLE
I see only sm64js background

### ISSUE THREAD

**Issue by Mario64Lol** [sm64js/sm64js#583]
Hello people,so actually my sm64js is not working.Idk how to fix it,btw I use CCleaner.can use 1 time.
![20211029_225625](https://user-images.githubusercontent.com/93389636/139447900-eedfc6d9-73f3-4278-8d4c-3c4812f3e79a.jpg)
Help!Btw Is loaded

**Comment by luphoria** [comment]
This issue is not fixed yet but run this command in the JavaScript console: 
Happens with both Mario and Luigi btw.
```
Object.keys(window.myMario.skinData).forEach((skinType) => {
        localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
}) 
```
Just paste this into the console and your page will load again, sorry for the inconvenience.

**Comment by MasterNama17083** [comment]
> This issue is not fixed yet but run this command in the JavaScript console: Happens with both Mario and Luigi btw.
> 
> Object.keys(window.myMario.skinData).forEach((skinType) => { localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType]) }) 
> 
> Just paste this into the console and your page will load again, sorry for the inconvenience.

Thanks god for helping me

**Comment by MasterNama17083** [comment]
@Mario64Lol Try it now

**Comment by luphoria** [comment]
Feel free to re-open if the issue persists.

**Comment by Mario64Lol** [comment]
> @Mario64Lol Try it now

Where I need to add it?
