### ISSUE TITLE
I wanted to play sm64 js but it won't start. I've tried it on different devices.

### ISSUE THREAD

**Issue by WhiteSonicSuper** [sm64js/sm64js#584]

**Comment by AgentXLP** [comment]
You gotta be more descriptive than that.

**Comment by AgentXLP** [comment]
Also, if the page won't load at all and you just see the background try running
```js
Object.keys(window.myMario.skinData).forEach((skinType) => {
        localStorage[`skinData-${skinType}`] = JSON.stringify(window.myMario.skinData[skinType])
})
```
in the console

**Comment by ImaginaryNeon** [comment]
what about those of us who can't access the console?

**Comment by luphoria** [comment]
> what about those of us who can't access the console?

Not sure why you're asking. Considering you are banned.

**Comment by ImaginaryNeon** [comment]
> > what about those of us who can't access the console?
> 
> Not sure why you're asking. Considering you are banned.

well that keeps EVERYONE using a school computer (or anyone who doesn't know how the console works) from using this, not JUST me.

**Comment by luphoria** [comment]
this person never followed up...
