### ISSUE TITLE
music

### ISSUE THREAD

**Issue by CheeseDoge** [sm64js/sm64js#587]
music doesnt work

**Comment by AgentXLP** [comment]
Gotta be more descriptive than that.

**Comment by ImaginaryNeon** [comment]
the site doesn't work, what makes you think the music will???

**Comment by MasterNama17083** [comment]
I think JS music code seems hardcoded or error?

**Comment by AgentXLP** [comment]
> the site doesn't work, what makes you think the music will???

Not sure why you care at all actually, Considering you are banned.

**Comment by PSIPowerhouse** [comment]
> > the site doesn't work, what makes you think the music will???
> 
> Not sure why you care at all actually, Considering you are banned.

You can get banned?

**Comment by ImaginaryNeon** [comment]
Yes, I did by saying "So long, Gay Bowser" and having had posted this image in the discord at a bad time.

![canvas (10)](https://user-images.githubusercontent.com/92883596/139849816-64efa96c-b7d3-4cdd-b0be-688defd9e8e8.png)

**Comment by luphoria** [comment]
> Yes, I did by saying "So long, Gay Bowser" and having had posted this image in the discord at a bad time.
> 
> ![canvas (10)](https://user-images.githubusercontent.com/92883596/139849816-64efa96c-b7d3-4cdd-b0be-688defd9e8e8.png)
> 

Actually you were banned for repeatedly making suicide jokes and then evading the mutes we gave you

**Comment by luphoria** [comment]
Closing this... reopen if you can describe the issue
