### ISSUE TITLE
Bowser in the dark world is IMPOSSIBLE to progress

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#588]
Now in vanilla, you cant ground pound dive, ground pound jump, or repetitive dive.
Now in Bowser in the dark world you may think the part with the pyramidal platforms is impossible to pass,
![Screenshot 2021-11-01 4 44 48 PM](https://user-images.githubusercontent.com/75381767/139746938-a432105b-fc19-4416-a65a-3b5c6f53850b.png)
as the platforms have no collision,(It would be nice if it can be fixed, But IDC if it's not) but it IS! You can Long-Jump past it, it took me around 7 minutes to figure this out.
![Screenshot 2021-11-01 4 47 21 PM](https://user-images.githubusercontent.com/75381767/139747187-dbb04528-c625-48b1-9a41-e8acea5cac6d.png)
Now this is straight-up RETARDED
It is impossible to progress past this part.
Reason: There are not even STATIONARY platforms, The star on the side has no collision. (Besides there is a 1/100 chance you would actually make it) Long jumping isn't fast or high enough, Triple jumps are almost impossible to pull off, and even if you did pull it off you still don't have enough speed to progress. I suck at BLJ's (Especially on slopes) so I can't test if you can BLJ to get there, besides YOU'RE FACING BACKWARDS AND THE PLATFORM IS ON A HIGHER Y-AXIS(For those who don't know their axises X is to the side and Y is up and down) THAN YOU ON THE CURRENT PLATFORM SO EVEN IF YOU PULL THE BLJ OFF YOU WOULD GO UNDER THE PLATFORM
Thereby ending the reason why bowser in the dark world is improgressible.
Bob-omb battlefield literally is a fully functional level. (The red bob-ombs are at spawn, The black Bob-ombs actually ignite if you get close, there are goombas, the boxes are there, the boulders that roll down from the top of the hill actually damage AND roll, and one of the cannons Actually work) So even if you don't decide to make BITDW a fully functional level at least add the platforms

**Comment by luphoria** [comment]
If you need to get past these spots, a temporary fix is simply to use the coordinate parameters

**Comment by PSIPowerhouse** [comment]
> If you need to get past these spots, a temporary fix is simply to use the coordinate parameters

how do i do that

**Comment by ImaginaryNeon** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. A single lap should be completed each time you hear this sound. Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start. 
1.
2.
3.
4.
5.
6.
7.
8. End of Level 1.
etc.

**Comment by eros71-dev** [comment]
> The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. A single lap should be completed each time you hear this sound. Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start. 1. 2. 3. 4. 5. 6. 7. 8. End of Level 1. etc.

Please don't the issues to post memes, this makes it harder for us to see the other people's comments so we can resolve the issue

**Comment by ImaginaryNeon** [comment]
Ṫ̴͔̋h̷̪̋ͅȇ̴̤͓ ̶̥̎͠F̴̛̹î̶̮͚t̷̛͓ň̴̟͠e̴͚͝s̶̥͂s̵̙͔͐G̶͎̅̿r̶̬̝͌͘a̴̰̠͑m̸͔̽™̸͔̆͘ ̵̯̣͌͝P̵̜͗a̷̝͠ć̶̜e̶̲̘̔͠r̶̲̙̂ ̶̘̈T̷͍̕e̷̥̩̾s̵̼̰͋̄t̸̢͂ ̴̧̻͂̏į̵̂̾ș̵̢̇ ̵̲͈͆ă̷̘͔ ̴̛͖̖m̷͙̆̑u̸̹̒̽l̴̞̾t̸̞́̄ï̶̖s̷̪̺̽ṱ̷̑͘a̴̲͂͝g̸̹̔͝e̷͖͂̈́ ̸͖̟͊a̵͖͗e̶̥̜͝r̵̬̽o̸̬̦͒b̶̺̈́͊ȋ̷̮̪c̴̺̓ ̵͔̉c̶͉̣͒̀ą̷̤̀p̵̜̼̓̾a̷͛͜c̴̢̥̚i̶͉̽̏t̴͙̮̋y̴̹͓͊̽ ̶̭̐t̸̞̞̽̈́ȅ̴͉͙̔ş̵̰͗ṭ̷͑̑ ̸̡̉͝t̶̲̂h̴̺̲̏a̷̎̃ͅť̵͙̭ ̴̱̠́͆p̶̛̼̑ṙ̴̙ơ̶̬̮̿g̶̘̒r̶͙̈́̾e̷̢͛̀s̵̡͔͘s̸̗̈ḭ̶͓͗͘v̸̲͖̑͌ě̸͚͓̈́l̷̰͓̓y̴͈͊͘ ̵̜̀g̴̼͈͘e̷̤̚t̷̡͐̿s̷̰̠̾ ̷̪̭̈m̸̗̼̊͘o̷͙̿̓r̷̟͊͠ȅ̶̯̀ ̸̧̟̈́d̵̗̯̅i̴̹͚̓f̴̡͐f̶͓̋í̷̳͝ć̴̝̞ŭ̸̳́ḷ̶̹̽̚t̷̯̀ ̴̫̇̕a̶͙͓͐s̵̥̣͌ ̵̱̀i̴̪̔t̶̜͇̎̒ ̴̜͋̀c̷̜͒̽ǫ̷̯͝ṅ̷̞̮̈́ț̴̻̾̓ỉ̸̫́n̶̠̞̓ư̵̯͍͌e̵̯͝s̴͙̖̿.̶̝̠̎̒ ̷̮͐͝T̸̘̒͠h̵̜̐e̷͍̰͌ ̵̦̍͋2̷̹̋0̸͙̈̐ ̶̡̈m̸̠̞͆͘e̷͈͒̿ṭ̷̐ë̶̢̞r̴͇̝̈ ̵̮̝̀p̴̰̖͊̍a̴̹͈͋c̵̡͉͂̋e̶̜͑̿r̷̯̮̍̐ ̵̮͐t̵̜͒́ȩ̵̈́͝ͅs̷͙̿t̶̩̳͋ ̴̰̗̉w̶̙̃ḯ̸̭͛l̸͍̝͆l̷̗̤͐ ̴͕̣̅̇b̶̯̅ȩ̷͜͝͝g̵̖͔̓i̷̙̅n̷̢̥̊̎ ̵͙̹͋i̷̛͉̔ṇ̸̀ ̷̳͍̋3̸̣̓̈́0̶͔̺̔̚ ̴̗̈́̋s̴̮̦̎ȩ̷͗c̶͚͋̔o̸͓̿̆n̷͇͗d̶̘͝ŝ̷͚.̸̜̦̀ ̸͙̪̌̃L̵̖̈̂i̸̖͑̕n̴̰̬̈́̀ȅ̵̻̟͘ ̴̜̌̈ų̴͙̂̐p̵͍̝͝ ̵̹̈́͛a̵̡̛͇̓t̸̰́͌ ̸͇̔t̴̼̉̐h̵͇͌̑͜e̷͓̎̄ ̵̙̃̓s̶̆̑ͅt̴͍͈͒̎ã̸̹͝r̸͖̒͂ţ̴̭̂.̷͖̩́ ̴̘̝͝͠Ţ̷̇̚h̶̪͌e̴͔̋͠ ̴̮̠̄r̴̡͂̒ṳ̴͆͂n̴̙͎͆̉n̴͚͂i̴̪͊͜n̶͈̹̾̚g̴̖̞̔ ̷͎͇̓ş̶̦̏̂p̴̭̮͝e̴̗̳̒́e̸̼̩̐ḑ̸͖̋ ̶̛̺̼s̶͉͖͊͝ẗ̶̟̘a̴̱̤͊͠r̸̛͚̺̽t̶̗͔̑s̴̩͎̆ ̵̯͓͒s̷͍͐̈́l̸̠͘ő̷̧͉w̶̘̌͝l̸̼͆͊y̶̪̿,̵͈͛̃ ̴͍̑b̴̭̰́ȗ̴͙̆͜t̵̫̺̍͂ ̵̹̳̋̂g̴̝͇̉́e̵̪͘t̷̖̋͝s̴̺̐ ̷̰̌̄f̸̖̔͂a̴̮̦͌̚s̴̫͙̀̽ţ̵̑ͅe̸͈͍͝r̶̡̳͆͑ ̵̩͚̆ė̵̳̦̉a̶̟͋́ć̶͇̃h̶̗̯͗ ̵̦̽͂m̷̮̟̄ì̴͓n̸͕͆̅u̴̫̓t̷̮̖̀͆ȇ̵̯ ̸̬̱͐̇a̵̠̽́f̶̩̦̎t̸͈́ě̸̗͛r̷̬͆ ̴̧̤͛̇ẏ̶̹͝o̷͉͐u̸̺͖͘͘ ̵̛̪̐h̶̠̪̀͝e̵̻̖̓a̴̺̝̕r̷͕̟̊̓ ̸̩́́t̴̲͝h̸͕͌i̵̻͍̎s̵̬͌͝ ̶̝͔̔s̶̘̗̅͋ȋ̴̜̈́g̵̢̘̚n̶̤̘̈́å̷̭ḻ̸͆.̴̺̈́ ̷͉́͑Ä̸͓́ͅ ̵̖̅s̶̟̈i̸̺̒̽͜ṅ̷̥̄ǵ̸̢̟l̵̻͗e̵̥͔̓ ̵͙͉̀͝l̷̫͋ȧ̶̱̝̊p̶̧͎̔̀ ̶̧̙̽͠s̶̢͑h̵̹͇̆̃o̷̘͘u̶͊̚ͅl̵̙͍͂d̴͓̬͂ ̴̭̾b̶̦̰͂ḙ̸͔̒ ̶̬͇̔͆c̴͔̉͠ö̵̹́͛m̵̯̙̿ṗ̵̖̿l̷̢̋̂ē̷̥̮̒ṫ̷̘è̶̖͂ḓ̶̏ ̸̨̃̈́e̶͕͠ḁ̷̎c̷͚̿͋h̶̲̜͐͗ ̸̹̈́́t̴͍́̌i̶̜͑́m̷̮̄͆͜ê̷͎ ̵̬̋y̴̬̥̌o̵͕̝͂ú̶̺̥̅ ̷͖̰̇͘h̴̬͍͠ẻ̶̻͜a̶̛͙̎r̵̺̀́ ̷̻͗̉ṭ̴́h̶̪̀̇i̶̖̓͆s̷̨̙̈́ ̷̥̥̍̈́s̵͍͒̇ȏ̶͔̪ũ̴̖̹n̷̳̈̾d̷͙̈́.̶̛̭͝ ̶͓̀̇R̷̗̽ê̷̩m̵̛̝̳ḛ̷̟͌̚m̸͙̮̍b̸̛̏͜ͅe̵̺̋̈́͜r̷͎̱͝ ̶̨͖̽͑t̸͓̯͑o̸͓̖͊ ̷͕͝r̶̦͗͘u̸̢̡̅̓n̵͔̍͝ ̸̮͔͐͂i̶̡͇͗n̷̬̏̔ ̵͎̃̈ą̵̩̊ ̴͖̉s̷͈̥͗͑ţ̴̉̆r̵̗̠̊̓ȧ̸̢̛̠i̵͓̟̿g̴̲͙͛ḫ̸̡̐͘ť̷͕̓ ̷̨̧̊l̵̓͝ͅì̸̥͛n̶̲͑ȅ̴̠͇,̸̨͇̒̾ ̸̱̎á̴̗̊n̵̻̾̈́d̶͔̔ ̸̻́ř̴̮̞u̶̗̩̐n̷͖̤̄ ̷̯͉̂a̶̫̔s̶̱̙̈ ̵̹͌l̴̰̐̀ͅỏ̷̟n̶͚͉̋̕g̸̻̼̽͘ ̶̼́̌a̷͚̮̓s̸̤̖͂̓ ̸̙̣̎p̷̻͍͂ơ̸͈͝s̸͚͐̾s̶̼̘̀͝ī̵̧̥͒b̷̭͔̕l̷͍͙̅ȇ̸͙̖.̸̨̛̠ ̴͙͌T̷̲͌͆h̶͙͛ê̸̱̋ ̸̟̈́̏s̷̅͜e̷̩͓̚ć̸̟̳̈ó̵̭̯͐n̷̟͌͂d̸͎̾̎ ̴̯̽t̸̖̔͜͝ȉ̶͕ͅm̵̨̅͘e̸̙͔͂ ̶͇̉̈́ŷ̷̺̼́ỏ̶͚͕ǘ̸̔ͅ ̸̦̓f̷͓̐a̵̢̬̍̔i̸͕̓l̸͔̦̏ ̷̞͋t̸̲̃o̶̻̐̎ ̴̢̇͑c̶̯͂̀o̵͍͝m̷͈̃p̷̗̖̑l̶̬̹̀ę̵̤̒͘t̷͖̋̈́e̸̡͍̍ ̴͓̌á̵̜͉̕ ̷͚͉͆l̵̖̰̈͠å̶͍̮̅p̸̣̝̌ ̶̹̭̇b̷̩̄e̸͎̚f̶̢̙͝ṑ̴͖̘r̶͈̲̃̓e̷̮̠̐̊ ̴̹̻͒t̷̮͉̀̽ȟ̴̢̯̎e̸̮̅ ̵̧̫̿͌s̸̨̈ͅö̶̺̗́ǘ̵͚̙ṅ̵͎̦d̷̮̉̈́ͅ,̶̭̻̌̀ ̴͎̰̌̏y̴̡͇̓o̸͍͛u̷͍̠͆̈r̵̠̬̆̆ ̶̯̍̈ț̴̉e̶̼̽̋ś̷̭͛t̸̰͘ ̵͖̈́̍i̶͉͛͠s̶̖͒ ̵̡̿̍ô̸͇v̶̦͋̈́e̴͚͛̏r̵͙͖̄͛.̶̘̌ ̴̢͋T̴͕͑h̶̞͒e̶̤̾͒ ̷͈̒͜͝ť̸͎̅ẹ̶̄s̷̳̻̓t̸̳̆ ̶̢̗̀͝ẉ̶̮̎̀i̸͙͍͂̈ĺ̸͕͔̌l̸͖̰͒̍ ̶̜̗͂b̴͉̯̈̏e̵̮͌̓ǵ̵̯̙͌ḯ̷͉̅n̵̰͓͒͠ ̸̚͜ȍ̶̭͊n̴͈̄ ̸̬͠t̵̲̥̑̊h̸͎͂̚ȅ̶̜ ̷͔̆͋w̸̞͖̓ǫ̶͖̑̂r̷͔͖̎̈d̵̢̟͂͆ ̸͔͖͋́s̵̟͂ţ̸̇̇a̸̬̔r̵͖̈̎t̸͔͆̄.̸̡̓͌ ̸͓̖̋̍Ǫ̶̇̑n̴͖͌͐ ̸͇̮̅̓y̷͎͆o̶̺͒͜u̵̡͑r̶̬͚̉͌ ̶̫̗̈m̸̹͍͘ạ̷͗̿r̵̪͂̃ḱ̴̪̌,̷̻͑̕ ̴͙̙̍g̸̳̒è̷̘̈́t̶̰͊̉ ̸̛̘̈́ȓ̴͎e̸̞̳͝à̶̯͜d̵̩̃̊y̶̖̪̔,̵̼̻̌͠ ̵̧̛͂ͅs̸͚̑t̷̛̮͕a̸͓̲̽̃r̴̬̓t̷̥͓̾.̷͍̽ ̴̧̖̈'

LINE UP AT THE START

**Comment by luphoria** [comment]
> > If you need to get past these spots, a temporary fix is simply to use the coordinate parameters
> 
> how do i do that

You can see a "Save Position" button under the game window. when you click this, the link changes to have some parameters. From here you can directly change Mario's spawn coordinates.

Take this script to get past the part you are talking about: https://vanilla.sm64js.com/?autostart=1&level=17&pos=69,-2500,-300,3500

The syntax for coordinates is: `yaw`,`x`,`y`,`z`
