### ISSUE TITLE
i cant chat False ban/mute

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#590]
I cant chat in sm64js then,

I was in my email and I found a message that said this

>Yes, I did by saying "So long, Gay Bowser" and having had posted this image in the discord at a bad time.

>[Picture of gun]

>Actually, you were banned for repeatedly making suicide jokes and then evading the mutes we gave you

>—
>You are receiving this because you commented.
>Reply to this email directly, view it on GitHub or unsubscribe.
>Triage notifications on the go with GitHub Mobile for iOS or Android. (It said luphoria sent this to me)

 1. I'm not banned
 2. I never got muted before so I never evaded mute
 3. I never made suicide jokes

Plz unmute me I never did anything wrong
I have to ignore when people ask me questions and it makes me think they think I'm mad at them for whatever reason

**Comment by luphoria** [comment]
This was a conversation on github. You were muted for saying the N word.
