### ISSUE TITLE
SM64JS vanilla new features (Suggestion)

### ISSUE THREAD

**Issue by MasterNama17083** [sm64js/sm64js#593]
Hello. Would you like to new features on vanilla version?

**Includes:**

- **New** Toggle Camera Freeze Button
- **New** Toggle Overlay HUD On/Off Button
- **New** Original Pause Screen (Pressing the Enter/Start mapping key)
- **New** Wing and Metal Cap Special Items
- **New** You can pressing the (B) button to read dialog message (Like Wooden Sign object in _Bob Omb Battlefield_)
- **New** Collecting 1UP Mushroom
- **New** Teleporting something position
#
**Example:**
![](https://i.ibb.co/6NrLcxz/image.png)
**(Like Flowers)**
![](https://i.ibb.co/jZyysRZ/image.png)
**(Like Ground Teleport Hole)**
#
- **New** Overlay Cannon
**Example:**

![](https://i.ibb.co/ZT8MTG7/image.png)
#
That's all. Let's see how happen if new updates?

**Comment by luphoria** [comment]
These are all planned and will come

**Comment by PSIPowerhouse** [comment]
> These are all planned and will come

LET'S GOOOOOO!!!! CANNONS AND CAPS
