### ISSUE TITLE
When signing in, the page looks like the sm64js equivelent of MissingNo.

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#594]
Ik I'm banned, but I'd rather see a ban message than the site having a seizure comparable to :shock:.

![Screenshot 2021-11-12 4 11 14 PM](https://user-images.githubusercontent.com/92883596/141541000-19cc2e7d-9ec7-4361-b485-574c3dfbdb3b.png)

**Comment by luphoria** [comment]
@eros71-dev take a look at this please :)

**Comment by eros71-dev** [comment]
This is the first time I see something like this, looks like the css is not loading properly. I have no clue on how this happened, neither on how to "fix" it. Could you explain what you did to enter the site? Which platform are you using?

**Comment by ImaginaryNeon** [comment]
I am on chromebook and i used the Log in with Google option. It happens with all **7** of my Google accounts. (It's only 7 cuz I litterally can't make any more w/o verifying via phone #, & I don't have a phone.) It happens regardless of if I enter the site via the 1st result on Google, one of the many bookmarks I have, or just entering the URL.

**Comment by blueknight64** [comment]
maybe it happens when you get ip banned and try to get onto another account? i dont know im not an expert

(moral of the story, accept bans)

**Comment by ImaginaryNeon** [comment]
> (moral of the story, accept bans)

moral of the story, unban me.

**Comment by luphoria** [comment]
fixed
