### ISSUE TITLE
bumping is broken

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#6]
When i bump (more like brush) against a wall, like, running beside a wall, jumping, and then suddenly touching it, i start repeatedly getting bumped all the way down, back and forth until something happens and the loop breaks
Does the game simply flip mario's direction relative to the wall it touched? I think that's what happens

**Comment by Cooliokid956** [comment]
actually, long jump at any wall and it will happen

**Comment by sm64js** [comment]
I think this is fixed, let me know.
