### ISSUE TITLE
chat issue and flag issue on BOB

### ISSUE THREAD

**Issue by blueknight64** [sm64js/sm64js#600]
so me and mickeyink managed to play the new sm64js update, but while we were messing around stuff i noticed that the chat messages were going off the chat box;
![image](https://user-images.githubusercontent.com/75827284/143822581-74c755f3-c9ac-4ae2-98fc-e0d18fe5017b.png)
and when we first joined BOB we were surprised to see the moving bridge taking place of the flag, the reason why i think its a flag because when mickeyink ran into where the flag hitbox should be the bridge attached to him:
![image](https://user-images.githubusercontent.com/75827284/143822813-1f6c98bf-ec4a-4969-bc53-cbb604635941.png)
so far those are the only glitches i could find at the moment, gonna try to search for more

**Comment by blueknight64** [comment]
fuck wrong image
![image](https://user-images.githubusercontent.com/75827284/143822949-a9faf057-6833-4872-a7a2-5898fa3003bb.png)
![image](https://user-images.githubusercontent.com/75827284/143822957-6aaa22e6-9dfc-4256-be11-5f385da49842.png)

**Comment by AgentXLP** [comment]
Lol

**Comment by PaperVb64** [comment]
Yeah this happens everywhere. Just stop playing until the next update.

**Comment by PaperVb64** [comment]
[Sry i had to say that, but the game needs some work]

**Comment by CyberNutz** [comment]
im experiencing the chat bug too

**Comment by CyberNutz** [comment]
you legit have to highlight the chat just to see it
![a circle eh thing](https://user-images.githubusercontent.com/88788248/144275349-b06b803a-0d45-4dde-8738-7451874ed9d8.PNG)

**Comment by luphoria** [comment]
Fixed in https://github.com/sm64js/sm64js/commit/f24fa13402bdc68dd2de5821822f9cce0680573d
