### ISSUE TITLE
On top of all the bugs, I found another one.

### ISSUE THREAD

**Issue by CyberNutz** [sm64js/sm64js#605]
Sometimes on the screen which tells you to keep the chat safe, there's a chance it shows the old message but completely white, the entire website is light and more.
![amazing](https://user-images.githubusercontent.com/88788248/144280083-08ca8669-1c8b-4056-84f7-f0c9d4117203.PNG)

**Comment by luphoria** [comment]
This is an issue with stylesheets loading and not the codebasi

**Comment by ImaginaryNeon** [comment]
my eyes are in great pain.
