### ISSUE TITLE
Does the server mute you?

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#608]
A long time ago around October 12th, I was chatting with friends in Dolphin Town. Then like, an hour later, I couldn't talk. The thing is I did nothing to be muted. Does the server mute you, if not, what did i do to be muted

**Comment by luphoria** [comment]
Did it say you got muted?

**Comment by PSIPowerhouse** [comment]
i just know that i was able to chat, then the next day, i tried to chat and it said Server: [you are muted]

**Comment by ImaginaryNeon** [comment]
Did it say a time after the message? (i.e. 6h 24m or something I don't remember) Otherwise, I think you were somehow perma-muted. Also, I think it happens when an admin mutes you. 
Source: My first and only mute; Starman Fortress during 2021

**Comment by luphoria** [comment]
Feel free to keep discussion
