### ISSUE TITLE
sm64js doesn't work with holy unblocker

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#609]
![image](https://user-images.githubusercontent.com/92883596/145641597-7e2944e6-4368-4bd8-984a-73ba7a66db9e.png)

![Uploading image.png…]()

**Comment by BinBashBanana** [comment]
*dies from cringe*

**Comment by PSIPowerhouse** [comment]
They gon just reblock you on this unblocker

**Comment by luphoria** [comment]
this is not an issue with sm64js

**Comment by ImaginaryNeon** [comment]
> They gon just reblock you on this unblocker

Then I, and get this, just go to another unblocker.
