### ISSUE TITLE
SUGGESTION: BAN ANYONE WHO SAYS A SINGLE SWEAR WORD EVEN THOUGH ITS NOT CENSORED

### ISSUE THREAD

**Issue by smm2mickeyink** [sm64js/sm64js#61]
I was gonna record a yt video for fun a.k.a a video request by: fireglitch64 but the swearing got annoying... cause my yt channel is a family friendly mario channel so i really don't like swear words

**Comment by luphoria** [comment]
Wouldn't a better option be a toggleable chat? I feel banning everyone would be quite harsh.. especially considering bans aren't even a thing yet

**Comment by smm2mickeyink** [comment]
> Wouldn't a better option be a toggleable chat? I feel banning everyone would be quite harsh.. especially considering bans aren't even a thing yet

ya :( i just got triggered about this

**Comment by sm64js** [comment]
added a block player option and will work on more ban options in future
