### ISSUE TITLE
Mario is knocked back from wall while sliding when not supposed to.

### ISSUE THREAD

**Issue by ItsMeSleepy** [sm64js/sm64js#613]
I feel like this has something to do with issue #198 .
(note: the video does look like just an image for a few seconds but just wait like 2 seconds and it'll work.)
https://www.youtube.com/watch?v=rx_O_0TjBy4

**Comment by ItsMeSleepy** [comment]
this is in vanilla

**Comment by AgentXLP** [comment]
Weird, I'll look into how wall bonking is triggered and compare it to the base game when I get the chance to.

**Comment by AgentXLP** [comment]
> this is in vanilla

https://agent-11.github.io/projects/sm64js/ this doesn't happen anymore in my updated fork of the game

**Comment by ImaginaryNeon** [comment]
Me, who's not Mario:
![2022_01_16_0sy_Kleki](https://user-images.githubusercontent.com/92883596/149703658-c2d94ed4-1544-417c-81e2-877dc4d045ce.png)
