### ISSUE TITLE
Is it possible to have another site beable to access the sm64js servers?

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#616]
Could one theoretically make another site that is essentially a clone of sm64js.com, and have it use the same servers (as in like being able to play cross-site between sm64js and this theoretical site, with different ban lists per site (i.e. you could be banned from the theoretical site, but not sm64js.com, and vice versa))? Asking for a friend. (I am the friend.)

**Comment by AgentXLP** [comment]
no fuck off

**Comment by blueknight64** [comment]
My man trying eveerything he can to evade his ban lmao

**Comment by ImaginaryNeon** [comment]
> My man trying eveerything he can to evade his ban lmao
At this point, I'm just trying to evade the school's blocking of sm64js. (It loads a white background with the word "reset" on the top-left corner.

**Comment by PSIPowerhouse** [comment]
> > My man trying eveerything he can to evade his ban lmao
> 
> At this point, I'm just trying to evade the school's blocking of sm64js. (It loads a white background with the word "reset" on the top-left corner.

ngl that has happened to me before. they somehow got the code to just say "reset" instead of all the complex stuffs
