### ISSUE TITLE
Some bugs I found.

### ISSUE THREAD

**Issue by CyberNutz** [sm64js/sm64js#625]
The game crashes if you attempt to jump-kick someone, if you're directly over a tree it can TP you back and if you jump from a tree, you get sent to the bottom.

**Comment by AgentXLP** [comment]
Not going to fix these only because you specifically found them. :trollface: :trollface:

**Comment by ImaginaryNeon** [comment]
Game-breaking bugs? More like a little bit of trolling.

**Comment by Agent-11** [comment]
> Game-breaking bugs? More like a little bit of trolling. ![](https://camo.githubusercontent.com/9cfbf5ad02beb639c6347e21cba167ec1052005df66a04de93ae7bdd2b2e4860/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f69636f6e732f656d6f6a692f74726f6c6c666163652e706e67)

Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done
You're banned, game over, move in and quit being such a child

**Comment by Agent-11** [comment]
> Game-breaking bugs? More like a little bit of trolling. ![](https://camo.githubusercontent.com/9cfbf5ad02beb639c6347e21cba167ec1052005df66a04de93ae7bdd2b2e4860/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f69636f6e732f656d6f6a692f74726f6c6c666163652e706e67)

Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done
You're banned, game over, move in and quit being such a child

**Comment by AgentXLP** [comment]
> The game crashes if you attempt to jump-kick someone, if you're directly over a tree it can TP you back and if you jump from a tree, you get sent to the bottom.

Fixed these

**Comment by ImaginaryNeon** [comment]
> Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done You're banned, game over, move in and quit being such a child

You accidentally sent that twice.

**Comment by ImaginaryNeon** [comment]
> > Game-breaking bugs? More like a little bit of trolling. ![](https://camo.githubusercontent.com/9cfbf5ad02beb639c6347e21cba167ec1052005df66a04de93ae7bdd2b2e4860/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f69636f6e732f656d6f6a692f74726f6c6c666163652e706e67)
> 
> Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done You're banned, game over, move in and quit being such a child

You made a typo, I assume you meant move on, but the typo makes it sound like you want me to live with you, which I KNOW is not what you meant.

**Comment by Agent-11** [comment]
> > Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done You're banned, game over, move in and quit being such a child
> 
> You accidentally sent that twice.

GitHub being strange

**Comment by Agent-11** [comment]
> > > Game-breaking bugs? More like a little bit of trolling. ![](https://camo.githubusercontent.com/9cfbf5ad02beb639c6347e21cba167ec1052005df66a04de93ae7bdd2b2e4860/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f69636f6e732f656d6f6a692f74726f6c6c666163652e706e67)
> > 
> > 
> > Fuck off please, you have done nothing but spam the issues tab and evade bans, you have been reported several times by others who have witnessed these acts of shitfuckery you have done You're banned, game over, move in and quit being such a child
> 
> You made a typo, I assume you meant move on, but the typo makes it sound like you want me to live with you, which I KNOW is not what you meant.

You know what I mean, don't give me the "minor spelling mistake I win" energy.
small keyboards are ass, also.

On a main note, cut the shit.

**Comment by ImaginaryNeon** [comment]
I was simply attempting to state the fact that you spelled the word 'in' in a way of which was not correct.

**Comment by Agent-11** [comment]
> ### **[ImaginaryNeon](/ImaginaryNeon) ** commented [9 hours ago](#issuecomment-1028034322)

I see it more like refusal to move tf on, bye bye with your messages
