### ISSUE TITLE
Submit rom button not working

### ISSUE THREAD

**Issue by amongus345** [sm64js/sm64js#633]
When i submit my rom after uploading it just freezes

**Comment by ghost** [comment]
Could you share more information? (e.g. your browser)

**Comment by amongus345** [comment]
um i am on chrome browser and when I upload the rom I cant submit it to be able to actually play

**Comment by ghost** [comment]
If the rom is not correct, it will not submit. The CRC32 hash of the rom should be 3CE60709. Please verify your rom and try again.

**Comment by amongus345** [comment]
My bad dude. I was using a ROM hack I downloaded for something else. sorry
