### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#634]
### Enviroment
- windows 10
- nodejs 16.13.2
- npm 8.1.2
### Notes
Both *./src/engine/LevelCommands.js* and *./src/game/ObjectCollisions.js* throw this error:
`Module parse failed: Unexpected token`
### Log
[sm64js-log0.txt](https://github.com/sm64js/sm64js/files/8009270/sm64js-log0.txt)

**Comment by AgentXLP** [comment]
Fixed
