### ISSUE TITLE
Random Crashes in BOB

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#638]
In vanilla, I sometimes play a long time tryna do some speedrun strats. But sometimes I crash randomly. it's only in the BOB-OMB battlefield cuz when I crash in SSL, it's due to the falling in the quicksand (Which is also another bug I have[And sometimes when I grab a ledge in the part where those blocks would usually be moving at, idk what its called]).

**Comment by PSIPowerhouse** [comment]
Also idk what happened to my old issue,but im stuck on mute, ive been like this for months, yet i did nothing wrong,
I was just playing the game, hosting my manhunt shenanigans, then i left, came back, and i was muted

**Comment by PSIPowerhouse** [comment]
And i think someone (Probably Agent 11) banned me from the discord server, as he said i was "Racist". I cant join the server

**Comment by AgentXLP** [comment]
You said the N word on November 3rd and your account was banned because of that.

**Comment by PSIPowerhouse** [comment]
> You said the N word on November 3rd and your account was banned because of that.

Couldn't you atleast given me a warning first or like a 1d temp-mute? That was the first time i did something bad enough to get perma-muted. You gave no second chances. I feel like thats a tiny bit much for a starter mute. I get that word is bad, but did it have to be that much?

**Comment by AgentXLP** [comment]
> > You said the N word on November 3rd and your account was banned because of that.
> 
> Couldn't you atleast given me a warning first or like a 1d temp-mute? That was the first time i did something bad enough to get perma-muted. You gave no second chances. I feel like thats a tiny bit much for a starter mute. I get that word is bad, but did it have to be that much?

I'll consider unmuting you with the mod team

**Comment by AgentXLP** [comment]
@PSIPowerhouse Alright, we've decided we'll give you a second chance, you're unmuted now.
