### ISSUE TITLE
Camera Moves by its self.

### ISSUE THREAD

**Issue by Samdan9** [sm64js/sm64js#639]
I don't know why this is happening but my camera just likes to go everywhere and using the camera buttons doesn't help at all and it's very disorienting, please fix this! also is there any way to get audio in the game? thanks.

**Comment by eros71-dev** [comment]
What do you mean with "it likes to go everywhere" specifically?
Also, sound and music haven't been implemented yet, until we find a way to extract the samples from the rom, it won't be possible.

**Comment by AgentXLP** [comment]
?

**Comment by AgentXLP** [comment]
Going to close this issue for now, reopen if you can give us more context.

**Comment by ImaginaryNeon** [comment]
> I don't know why this is happening but my camera just likes to go everywhere and using the camera buttons doesn't help at all and it's very disorienting, please fix this! also is there any way to get audio in the game? thanks.

I think it's doing a little thing known as following you. It has to do that so you can see Mario because, believe it or not, the player likes to go everywhere.
