### ISSUE TITLE
Mirror room in Castle interior #2 crashes

### ISSUE THREAD

**Issue by RuralAnemone** [sm64js/sm64js#640]

**Comment by AgentXLP** [comment]
Cannot reproduce this. doesn't crash in either MMO, Vanilla and I even checked 60 FPS. closing for now

**Comment by RuralAnemone** [comment]
okay so this might be because I'm using the effective beta version...? (at https://luphoria.com/sm64js)

[screen recording](https://cdn.ruralanemone.tech/media/screenrec/sm64js.webm)

**Comment by RuralAnemone** [comment]
using "crash" lightly

more akin to hardlock, I guess...?

**Comment by AgentXLP** [comment]
> okay so this might be because I'm using the effective beta version...? (at https://luphoria.com/sm64js)
> 
> [screen recording](https://cdn.ruralanemone.tech/media/screenrec/sm64js.webm)

Dude that versions over a year old lmfao
