### ISSUE TITLE
Game crashes when i approach Bob-omb in Vanilla

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#652]
So I loaded up Vanilla SM64JS and saw a bob-omb. I threw him off the cliff and he blew up. But then i went back down to the start of the mountain and there was the same bob-omb from before. I killed him again and went on with my playthrough. But then a few minutes later, my game crashed. i think it was because of that bob-omb i killed. Something similar happened one time in the mmo sm64js. It crashed everyone's game. But Agent X eventually fixed it in the MMO version but i guess the glitch is also in the vanilla version so please fix the vanilla bob-omb glitch.

**Comment by AgentXLP** [comment]
Hmm

**Comment by ghost** [comment]
yeah so remember that "Evil Bob-Omb" glitch we dealt with before in MMO. I think that glitch spread to the Vanilla version and it might be in the 60fps version to but idk.

**Comment by AgentXLP** [comment]
60 FPS is quite outdated, my most up to date fork of the game shouldn't have that. https://agent-11.github.io/projects/sm64js

**Comment by Someone567123** [comment]
self promote! ew!
