### ISSUE TITLE
Controls Glitch

### ISSUE THREAD

**Issue by EdgydaHedgy** [sm64js/sm64js#66]
So basically, whenever I hold forward, sometimes I can't hold right while I hold forward, but I can hold left while I hold forward, which doesn't make sense.

**Comment by Cooliokid956** [comment]
Oh, this bug dates WAAAAY back to when there wasn't even any multiplayer, i would suggest changing your keyboard controls to WASD and J for z, K for a, and M for b, similar to the pc port control scheme. This one doesn't have these problems.

**Comment by EdgydaHedgy** [comment]
ohh ok thx (btw im 2fast4u on sm64js)
