### ISSUE TITLE
Vanilla bugs

### ISSUE THREAD

**Issue by AgentXLP** [sm64js/sm64js#660]
I'm using an issue here to keep track of the current bugs in the vanilla branch, I have fixed a lot of them so far.
- Camera doesn't have collision
- Goddard fails to initialize twice
- Loaded graph nodes are not cleared when warping
- Due to how Mario's cap flickering code works, the flickering gets more and more inaccurate because the flicker frames are based off a number which is about equal to 4.9191321e+18 which from what I understand JS cannot interpret correctly
- Vanish cap Mario does not have the noise effect, he is simply just transparent.

**Comment by PSIPowerhouse** [comment]
> * When you die in BITDW, the trap doors do not remain open when you return to the castle, causing you to fall back into the level and glitch the power meter out visually and momentarily

I thought you could't die. Every time i try to die, i get stuck at 1 HP left

**Comment by AgentXLP** [comment]
> > * When you die in BITDW, the trap doors do not remain open when you return to the castle, causing you to fall back into the level and glitch the power meter out visually and momentarily
> 
> I thought you could't die. Every time i try to die, i get stuck at 1 HP left

> Updated vanilla

**Comment by AgentXLP** [comment]
![Screenshot 2022-04-01 11 29 00 AM](https://user-images.githubusercontent.com/44549182/161294990-a82b4ee9-ae64-449e-b4fb-326cfaf0c6e3.png)
Hm. It appears the object issue is more models not getting unloaded rather than objects. This is where the penguin spawns and I highly doubt that very spot is also where the piano spawns in BBH.

**Comment by abnormalhare** [comment]
Level progression bugs fixed

**Comment by AgentXLP** [comment]
Think I'll pin this for ease of access

**Comment by mario64dd** [comment]
There is no sound.
