### ISSUE TITLE
Suggestions for sm64js

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#661]
1. Add Waluigi to sm64js. Make a custom Waluigi head model and put it on Luigi's body.
2. First Person Mode. Add a First Person Mode to the Options & Misc section.
3. Basement Level.  Add a Basement level to sm64js.

**Comment by AgentXLP** [comment]
> 1. Add Waluigi to sm64js. Make a custom Waluigi head model and put it on Luigi's body.
> 2. First Person Mode. Add a First Person Mode to the Options & Misc section.
> 3. Basement Level.  Add a Basement level to sm64js.

Could add Waluigi, sounds simple enough.

Hmm first person, I'll look into that.

If everything goes right, Castle Basement should be in the game this month, along with some other neat things you will see most likely tomorrow or the day after tomorrow.

**Comment by ghost** [comment]
also one more suggestion. If someone suggests something like a new stage or character, when you add it to the game, tell them that you added so that they'll know that its in the game.

**Comment by AgentXLP** [comment]
So like a changelog

**Comment by ghost** [comment]
yeah pretty much. Like for example when you add the castle basement level, put in the changelog "Added Castle Basement"

**Comment by Bloxxel64** [comment]
That's what #gh-tracker is for in the discord.

**Comment by ghost** [comment]
What is #gh-tracker?

**Comment by Bloxxel64** [comment]
on the sm64js discord https://discord.com/channels/755122837077098630/757026723471687800

**Comment by Someone567123** [comment]
i still wont join back

**Comment by ghost** [comment]
So X. How's it going with adding Waluigi and Yoshi to sm64js?

**Comment by g3-geo** [comment]
waluigi already exists in sm64js, just do the arceus2401 strat
