### ISSUE TITLE
Turning off sunshine redive disables Triple Jump

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#662]
I was playing with my friend, then i got sick of redive, so i turned it off. Then after a while, my triple jump disabled. Its everytime i try to disable redive. if i keep it on, i can triple jump, but i hate redive. i just wanna play regularly without redive

**Comment by AgentXLP** [comment]
Ahh that explains it

**Comment by AgentXLP** [comment]
Happens with it on or off, not the cause.

**Comment by AgentXLP** [comment]
Fixed
