### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by 8bti** [sm64js/sm64js#67]
I can't see anyone even but they can still hit me and jump on me

**Comment by smm2mickeyink** [comment]
> I can't see anyone even but they can still hit me and jump on me

SAME!!! IT HAPPENS TO ME RANDOMLY

**Comment by sm64js** [comment]
uh oh, I think I know the cause of this, and can fix it.

**Comment by sm64js** [comment]
I think this doesn't happen anymore, but please let me know if it does.
