### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#671]
Add two new taunts to the taunt menu.
1: Add the sleeping animation to the taunts.
2: Add the shrug animation to the taunts.

**Comment by PSIPowerhouse** [comment]
I would actually love the sleeping animation

**Comment by ghost** [comment]
what about the shrug animation? I think that one would be pretty funny.

**Comment by AgentXLP** [comment]
> Add two new taunts to the taunt menu. 1: Add the sleeping animation to the taunts. 2: Add the shrug animation to the taunts.

If I add anymore taunts I'm going to have to rewrite the taunt wheel

**Comment by ghost** [comment]
well do what you need to do with the taunt wheel but i really want at LEAST the shrug animation in sm64js.

**Comment by AgentXLP** [comment]
> well do what you need to do with the taunt wheel but i really want at LEAST the shrug animation in sm64js.

Alright ig

**Comment by AgentXLP** [comment]
Also for future reference, please name your suggestions in the issue title.
"Suggestion" is not helpful and wastes my time while I have to wait for GitHub to load the issue.

**Comment by ghost** [comment]
Ok i can do that :)
