### ISSUE TITLE
How do I end my punishment

### ISSUE THREAD

**Issue by MatthewMario64** [sm64js/sm64js#672]
I sent people a website for SM64, and now I can't chat or log into the game.

**Comment by MatthewMario64** [comment]
I mean, I simply wanted people to know how to play the game on a website, but then it said that i have been muted for 2 days and two days have passed, but i still can't do anything.

**Comment by AgentXLP** [comment]
> I sent people a website for SM64, and now I can't chat or log into the game.

Your username?

**Comment by AgentXLP** [comment]
> 

Unless you tried to evade the mute, it will always end at its presented date.

**Comment by MatthewMario64** [comment]
I use my name as SLG64, but i did use another account.

**Comment by MatthewMario64** [comment]
So, did i break it?

**Comment by MatthewMario64** [comment]
did i break my account from using the website?

**Comment by AgentXLP** [comment]
> I use my name as SLG64, but i did use another account.

Well there you go.

**Comment by MatthewMario64** [comment]
I mean it is a good game. sadly i broke it.

**Comment by Bloxxel64** [comment]
`I sent people a website for SM64, and now I can't chat or log into the game.`

You cannot distribute roms. that's a huge offense.

**Comment by ImaginaryNeon** [comment]
> `I sent people a website for SM64, and now I can't chat or log into the game.`
> 
> You cannot distribute roms. that's a huge offense.

I don't know if that's _exactly_ what they did, but their actions are kind of unclear.

**Comment by ImaginaryNeon** [comment]
> > I use my name as SLG64, but i did use another account.
> 
> Well there you go.

Now there are (probably) 2 options. 
One is getting appealed. 
The other, more tedious of the two is making more alts then eventually getting banned on those alts then making more alts then eventually getting banned on those alts then rinse and repeat for all of eternity. 
I would advise you do the prior. Let's just say I have experience with the latter. *Vietnam-esque flashbacks to my however many bans*

**Comment by MatthewMario64** [comment]
How do I get appealed?

**Comment by MatthewMario64** [comment]
I also didn't read the rules fully...

**Comment by MatthewMario64** [comment]
I'm sorry.

**Comment by AgentXLP** [comment]
I'll look into what you did further and decide with the mod team.

**Comment by MatthewMario64** [comment]
Ok, thank you.

**Comment by MatthewMario64** [comment]
Please let me know when you can.
