### ISSUE TITLE
How many bans have I had again?

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#676]
I lost count at 4.

**Comment by Bloxxel64** [comment]
screw you.

**Comment by ImaginaryNeon** [comment]
> screw you.

Stop being TM06 Toxic.

**Comment by AgentXLP** [comment]
Enough to know you should fuck off.

**Comment by ImaginaryNeon** [comment]
> Enough to know you should fuck off.

NaN

![Screenshot 2022-05-05 4 33 10 PM](https://user-images.githubusercontent.com/92883596/167029173-b81a319e-33b8-410e-80a2-c72fe8af469f.png)
