### ISSUE TITLE
(Suggestion) Add option to reset skin values

### ISSUE THREAD

**Issue by Roshibomb** [sm64js/sm64js#68]
I messed around with the default skin but now I want to go back to regular Mario, however, reloading the page doesn't seem to work and I can't find a button to do this. Now I'd have to go and look up Mario's color values and do them manually, which might take a while... I think it'd be helpful to have a button to do this automatically. If this is already there and I just haven't found it, please tell me and I'll delete this issue.

**Comment by luphoria** [comment]
You can do either localStorage.clear() or just set your skin ID to 0

**Comment by Roshibomb** [comment]
1. I don't know how to do that, sorry
2. The one I altered was ID 0, so switching to that won't help

**Comment by Roshibomb** [comment]
Uh... the game seems to have reset the skins on it's own. Not sure if that's a bug or not? Either way I guess it's fixed...
