### ISSUE TITLE
Unable to accept discord invite

### ISSUE THREAD

**Issue by MatthewMario64** [sm64js/sm64js#681]
I keep trying to join the discord server, but it says I'm unable to accept it.
My discord username is SLG64.

**Comment by Bloxxel64** [comment]
> I keep trying to join the discord server, but it says I'm unable to accept it. My discord username is SLG64.

have you been banned lmao?

**Comment by ghost** [comment]
> I keep trying to join the discord server, but it says I'm unable to accept it. My discord username is SLG64.

You're not the only one who can't get into the sm64js discord. I also can't get in.

**Comment by MatthewMario64** [comment]
I dunno, sometimes google says the connectivity was reset and I can't get into discord. I use the website version because I can't download it on my Chromebook.

**Comment by ImaginaryNeon** [comment]
> I dunno, sometimes google says the connectivity was reset and I can't get into discord. I use the website version because I can't download it on my Chromebook.

Okay, kinda makes sense, Chromebooks do tend to be bad at doing stuff. :kek:

**Comment by AgentXLP** [comment]
Looks like you were falsely banned because of your account being too new thus being considered an alt from what I can see. Unbanned

**Comment by MatthewMario64** [comment]
thanks
