### ISSUE TITLE
[Suggestion] Fix bug where sideburn colors don't change with "Hair" color

### ISSUE THREAD

**Issue by RepeatGitHub** [sm64js/sm64js#687]
Ingame, when changing the color of the hair, I noticed that the hair on the sides of Mario's head doesn't change, and it looks odd when altering hair color. I haven't tested this with Luigi/Wario, but it could be the case for them too.

**Comment by RepeatGitHub** [comment]
![Screenshot 2022-05-09 9 27 01 AM](https://user-images.githubusercontent.com/48736123/167420688-3b279bf0-eb7a-47c5-ad5c-3a5ace85f610.png)

**Comment by ghost** [comment]
Actually, I noticed this too. Thank you for pointing this out.

**Comment by ImaginaryNeon** [comment]
I think this has been around for a while. I don't know why it happens, but maybe the sideburns are considered a separate part of Mario's model by the game?

**Comment by AgentXLP** [comment]
Sideburns are their own textures and aren't changeable even if I tried to set up a grayscale version due to how sm64's light system works
You can replicate this behavior in emu as well, since CCs can't modify the color of a texture that's already on a shaded face
