### ISSUE TITLE
Suggestion: Screen Recording and Camera Options/ More Game Modes and Mods.

### ISSUE THREAD

**Issue by MatthewMario64** [sm64js/sm64js#690]
So, I like to record on SM64JS for fun and I thought that a screen recorder would be cool. Also, I would like more game modes, as I suggested before on the suggestion of new maps and accessories. For the mods, I was thinking about moon jumps, speed, flying, invincibility (in case you don't want anyone to kill you while you're doing something), height changes, which could be added to the character customize option, etc. As for the camera, it would be cool to give us different filters to play with them on. I want to make this easier to understand,I was thinking that we could play while filters are on.

**Comment by AgentXLP** [comment]
Scripting already exists for in-game moderators and I don't think an in-website screen recorder is worth adding as alternatives that will always be better like OBS exist. And for filters they'd be an interesting feature I suppose.

**Comment by ghost** [comment]
I think the invincibility would be a cool feature but then again, you can just turn your pvp off if you don't want anyone to kill you.

**Comment by MatthewMario64** [comment]
> I think the invincibility would be a cool feature but then again, you can just turn your pvp off if you don't want anyone to kill you.

Oh, I didn't know that.

**Comment by MatthewMario64** [comment]
> Scripting already exists for in-game moderators and I don't think an in-website screen recorder is worth adding as alternatives that will always be better like OBS exist. And for filters they'd be an interesting feature I suppose.

I know that some people don't know how to code, so I thought that in game mods would be fun.

**Comment by Bloxxel64** [comment]
maybe vanilla could get mods. but you would still need to code.

> > Scripting already exists for in-game moderators and I don't think an in-website screen recorder is worth adding as alternatives that will always be better like OBS exist. And for filters they'd be an interesting feature I suppose.
> 
> I know that some people don't know how to code, so I thought that in game mods would be fun.

**Comment by MatthewMario64** [comment]
> maybe vanilla could get mods. but you would still need to code.
> 
> > > Scripting already exists for in-game moderators and I don't think an in-website screen recorder is worth adding as alternatives that will always be better like OBS exist. And for filters they'd be an interesting feature I suppose.
> > 
> > 
> > I know that some people don't know how to code, so I thought that in game mods would be fun.

That makes sense, but you already have to download the rom, so why should people have to download the mods to have them?
