### ISSUE TITLE
[Suggestion] Different SM64 Roms for SM64JS

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#694]
So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was. Also another suggestion that I have is so you can put Gameshark cheat codes into sm64js. Imagine if someone put in the BLJ Everywhere code. They would be flying all over the place! Anyway, all I want from sm64js is to be able to uses rom hacks and cheat codes with it.

**Comment by Bloxxel64** [comment]
> So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was. 

not doable because of how js gets the vanilla games assets.


> Also another suggestion that I have is so you can put Gameshark cheat codes into sm64js. Imagine if someone put in the BLJ Everywhere code. They would be flying all over the place! Anyway, all I want from sm64js is to be able to uses rom hacks and cheat codes with it.

even if we could. why?

**Comment by ImaginaryNeon** [comment]
> > So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was.
> 
> not doable because of how js gets the vanilla games assets.

Even if it were possible, at some point people would put in a ROM for Pokémon Stadium or something, and I think that's a _bit_ too far.

**Comment by ghost** [comment]
> > > So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was.
> > 
> > 
> > not doable because of how js gets the vanilla games assets.
> 
> Even if it were possible, at some point people would put in a ROM for Pokémon Stadium or something, and I think that's a _bit_ too far.

I never said we had to do roms from other games. I just said we could do like sm64 rom hacks.

**Comment by MatthewMario64** [comment]
So, there is this group that I'm in, and we all are fascinated on clipping out of bounds, so we called it the sm64js backrooms. Then one of them said that they were wondering if you can play the SM64 Backrooms rom hack on SM64JS. I personally would like to be able to put rom hacks in.

**Comment by AgentXLP** [comment]
Custom levels/characters and such are not possible with ROM extraction.

**Comment by ImaginaryNeon** [comment]
> > > > So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was.
> > > 
> > > 
> > > not doable because of how js gets the vanilla games assets.
> > 
> > 
> > Even if it were possible, at some point people would put in a ROM for Pokémon Stadium or something, and I think that's a _bit_ too far.
> 
> I never said we had to do roms from other games. I just said we could do like sm64 rom hacks.

Yeah, but:

1. I may be wrong, but wouldn't all (or most) N64 games have the same (or similar) file extension things? (i.e. .png/.txt/.webp/etc) If so, how would it be able to tell?
2. If you allow ROM hacks, you're gonna get people using a ROM that manipulates a tiny problem in the server code or something to give them admin sooner rather than later.

To be fair, I wanna use texture packs, but that's moreso an "I can't do that because shool chromebook bad" thing that an "I can't do that because game no let me" thing.

**Comment by Bloxxel64** [comment]
> So, there is this group that I'm in, and we all are fascinated on clipping out of bounds, so we called it the sm64js backrooms. Then one of them said that they were wondering if you can play the SM64 Backrooms rom hack on SM64JS. I personally would like to be able to put rom hacks in.



> > > > So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was.
> > > 
> > > 
> > > not doable because of how js gets the vanilla games assets.
> > 
> > 
> > Even if it were possible, at some point people would put in a ROM for Pokémon Stadium or something, and I think that's a _bit_ too far.
> 
> I never said we had to do roms from other games. I just said we could do like sm64 rom hacks.

we, cant, do, romhacks.

**Comment by ImaginaryNeon** [comment]
> > So, there is this group that I'm in, and we all are fascinated on clipping out of bounds, so we called it the sm64js backrooms. Then one of them said that they were wondering if you can play the SM64 Backrooms rom hack on SM64JS. I personally would like to be able to put rom hacks in.
> 
> > > > > So we know that you need a "totally legal" sm64 rom to play sm64js right? Well, what if we could put different sm64 roms into sm64js? It could be a rom hack or just a new character. This would make sm64js 10X better than it already was.
> > > > 
> > > > 
> > > > not doable because of how js gets the vanilla games assets.
> > > 
> > > 
> > > Even if it were possible, at some point people would put in a ROM for Pokémon Stadium or something, and I think that's a _bit_ too far.
> > 
> > 
> > I never said we had to do roms from other games. I just said we could do like sm64 rom hacks.
> 
> we, cant, do, romhacks.

I think that the most that you _could_ do would be like a texture pack or something. (Imagine a PvP texture pack :kek:)
