### ISSUE TITLE
Suggestion: Customizable Eyes, Mustaches, and Hair Textures.

### ISSUE THREAD

**Issue by MatthewMario64** [sm64js/sm64js#695]
I've been wanting to be able to customize the eye texture for my character.

**Comment by AgentXLP** [comment]
Use a custom ROM and maybe open one big suggestion thread instead of 15 smaller issues

**Comment by ImaginaryNeon** [comment]
> Use a custom ROM and maybe open one big suggestion thread instead of 15 smaller issues

Is this some sort of _computer that can load software user_ joke that I'm too _console and chromebook user_ to understand?

**Comment by MatthewMario64** [comment]
I dunno
