### ISSUE TITLE
Suggestion: Audio Clips of Mario's Voice and Customizable Voice

### ISSUE THREAD

**Issue by MatthewMario64** [sm64js/sm64js#696]
I honestly think that the voice of Mario is what makes me feel more comfortable whan playing alone.

**Comment by AgentXLP** [comment]
Already working on it

**Comment by ImaginaryNeon** [comment]
I assume that (if customizable voices are going to be added) the voices would be preset options. If that is the case, it would be cool if y'all could add the Mii voices from Smash Bros. (If it's feasible.)

**Comment by MatthewMario64** [comment]
Interesting concepts is what I like.
