### ISSUE TITLE
Every time i open sm64js it keeps giving me an error

### ISSUE THREAD

**Issue by KM64bloopers** [sm64js/sm64js#699]
i havent played this since august please help i wanna playt sm64js again.
 url:

externalfile:arc-content/content%253A%252F%252Fcom.rsupport.mobizen.lg.fileprovider%252Fstorage%25252Femulated%252FPictures%252FScreenshots%252FScreenshot_2022-05-19-14-11-11.jpg

**Comment by MatthewMario64** [comment]
If you got baned and tried to change accounts to bypass the ban, then you'll likely get this error. This happened to me when I got baned. Although I don't know if you got baned, its probably just something wrong with your rom or maybe you need to check your region. I'm not an expert, but others can help you out, I think Agent-11 could help you, as he helped me.

**Comment by Bloxxel64** [comment]
> i havent played this since august please help i wanna playt sm64js again. url:
> 
> externalfile:arc-content/content%253A%252F%252Fcom.rsupport.mobizen.lg.fileprovider%252Fstorage%25252Femulated%252FPictures%252FScreenshots%252FScreenshot_2022-05-19-14-11-11.jpg

Have you been banned in the past?

**Comment by KM64bloopers** [comment]
> > i havent played this since august please help i wanna playt sm64js again. url:
> > externalfile:arc-content/content%253A%252F%252Fcom.rsupport.mobizen.lg.fileprovider%252Fstorage%25252Femulated%252FPictures%252FScreenshots%252FScreenshot_2022-05-19-14-11-11.jpg
> 
> Have you been banned in the past?

no i only got one ban and it was made permament.

**Comment by Bloxxel64** [comment]
> > > i havent played this since august please help i wanna playt sm64js again. url:
> > > externalfile:arc-content/content%253A%252F%252Fcom.rsupport.mobizen.lg.fileprovider%252Fstorage%25252Femulated%252FPictures%252FScreenshots%252FScreenshot_2022-05-19-14-11-11.jpg
> > 
> > 
> > Have you been banned in the past?
> 
> no i only got one ban and it was made permament.

so yes. you did.

**Comment by Bloxxel64** [comment]
@Agent-11 you can close this.

**Comment by ImaginaryNeon** [comment]
> > > > i havent played this since august please help i wanna playt sm64js again. url:
> > > > externalfile:arc-content/content%253A%252F%252Fcom.rsupport.mobizen.lg.fileprovider%252Fstorage%25252Femulated%252FPictures%252FScreenshots%252FScreenshot_2022-05-19-14-11-11.jpg
> > > 
> > > 
> > > Have you been banned in the past?
> > 
> > 
> > no i only got one ban and it was made permament.
> 
> so yes. you did.

Trust mii, it requires Herculean efforts to even be able to _dream_ of being unbanned after a certain point. My suggestion: Take the easier way out and just apologize now instead of trying to use alts. Let's just say I have _experience_ with being banned.
