### ISSUE TITLE
Shadow texture not mapped correctly

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#7]
The shadow has a part cut off and put on the other side, texture mapping issue? maybe, I tried re-extracting by clearing the site data but it was still like that

**Comment by sm64js** [comment]
Finally figured this out and fixed this glitch.  Was a rounding issue with texture coordinates. I was only checking out vertices for the triangles, I didn't realize texture coordinates were different.

**Comment by Cooliokid956** [comment]
ok good did the king bobomb incident help?
