### ISSUE TITLE
(Suggestion) Add a wood platform or bridge to get to the island on Bob-om Battlefield until cannons are activated

### ISSUE THREAD

**Issue by HereForLinus** [sm64js/sm64js#70]
It is really hard to get to the island, usually resulting in one play crouching while another play long jumps and hits them so they have enough distance to reach it.

**Comment by Ciarankelly18** [comment]
yeah what a good idea!

**Comment by lolxdhi1** [comment]
you do know you can just long-jump

**Comment by smm2mickeyink** [comment]
you realize that if the wooden or bridge get added this game will get copyrighted by nintendo.

**Comment by Roshibomb** [comment]
> you realize that if the wooden or bridge get added this game will get copyrighted by nintendo.

I don't think you understand how copyright works. If they would get copyrighted by Nintendo it will happen regardless of whether or not they add a bridge...

**Comment by sm64js** [comment]
The bridge can get extracted from the ROM the user provides.  I plan to add the bridge eventually
