### ISSUE TITLE
Switch controls?

### ISSUE THREAD

**Issue by CattyJedders** [sm64js/sm64js#703]
I mostly use my switch pairings for n64 gaming. Could this be possible for this, please? Thanks.

**Comment by AgentXLP** [comment]
What

**Comment by abnormalhare** [comment]
If you're talking about using joycons or a procon, you need to connect them using bluetooth to your computer. If you'r using a plugged in procon, it should work fine (I use one).

**Comment by fatenatecases04152** [comment]
LMAOOOO🤣🤣🤣🤣🤣WHAT HAPPENED HERE INCLUDING ALL THE OTHER ISSUES🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣THEY ALL ARE SPAMMED WITH W
