### ISSUE TITLE
Mod Application

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#705]
Hello, my name is drok27. I would like to apply for mod. I think you'll find that I meet all the requirements for mod.
1. I am very trustworthy. You wouldn't see me abusing my mod powers.
2. I run my own server so I think I know the rules for keeping it under control.
3. I am almost 15 years old. AKA I am very mature.
4. I have played this game for a long time. (Since April 2021)
5. I have only been muted one time. (In 2021)
6. I have never said any bad words or racial slurs ever.
I hope this is enough proof that I am a perfect candidate for mod.

**Comment by AgentXLP** [comment]
You just opened a PR trying to suggest more maps

**Comment by ghost** [comment]
That was only because I didn't know what I was doing.
