### ISSUE TITLE
[News] I am leaving SM64JS (Until August)

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#707]
Hello SM64JS players, I have some bad news. I am leaving the SM64JS community. I know this is going to be very hard on some players but don't worry, I will return in August. The reason I am leaving is because I have a major test tomorrow and I need to turn in my chromebook the same day and the reason I will return in August is because I will get a new chromebook for school but until then, You won't see me online on Discord and SM64JS. Thanks, everyone for being my friends and accepting me as one of you and to the Mods, keep updating the game as you have been and when I return, surprise me with a huge update.

Sincerely, Drok27

**Comment by AgentXLP** [comment]
Cya, normally I would just close the issue but I suppose I'll keep it open for a day or two for others to see

**Comment by ghost** [comment]
I am back!

**Comment by ImaginaryNeon** [comment]
Huh, neat.
