### ISSUE TITLE
Website Reloads Upon Trying to Start Gane

### ISSUE THREAD

**Issue by vanillaDSi** [sm64js/sm64js#710]
For the past couple of days, whenever I try to log on to SM64JS, after submitting my name and desired game level, the website reloads. The only work around I could find for this was to open another SM64JS tab while the previous one was still running, but that doesn't work half of the time. If you and your team could try to find a fix for this bug, that would be great. Check the attachment to see what I'm talking about.

https://user-images.githubusercontent.com/106826670/171884480-8b086c32-ded0-4241-b538-b15e47152352.mp4

**Comment by AgentXLP** [comment]
Found the issue and am currently deploying the fix for it to the site, hang in there.
