### ISSUE TITLE
(Suggestion) Auto-Translate

### ISSUE THREAD

**Issue by Roshibomb** [sm64js/sm64js#74]
Not sure how hard this would be to implement, but I've seen Spanish people playing the game and using chat that I have no way to communicate with (without manually putting every message into Google Translate, but that's a bit cumbersome). I feel like having an auto-translate option (toggleable, and possibly a "revert" button next to messages to check what they originally said?) would mostly fix that issue, as you'd be able to see messages translated in real-time and be able to communicate through language barriers easier.

**Comment by luphoria** [comment]
I don't think this is fit for a project like this

**Comment by Roshibomb** [comment]
> I don't think this is fit for a project like this

How so?

**Comment by sm64js** [comment]
Someone could make a mod for this.
