### ISSUE TITLE
Glitching

### ISSUE THREAD

**Issue by SJG4** [sm64js/sm64js#75]
Unfortunately, my game just started to glitch out, any idea how to fix this? ![image](https://user-images.githubusercontent.com/73476067/97770902-e4ad0080-1b0d-11eb-8c9f-2fb59068c90e.png)

**Comment by Ciarankelly18** [comment]
choose an .z64 or an extended rom the one i chose was an extended rom

**Comment by sm64js** [comment]
delete / clear browser cache, and load in a new rom
