### ISSUE TITLE
Question: What new updates are coming so far?

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#752]
I have a question: Are there any new updates coming this month or next month? If so, what are you adding?

**Comment by AgentXLP** [comment]
We're working on the vanilla branch mainly right now.

**Comment by ghost** [comment]
Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.

**Comment by ImaginaryNeon** [comment]
> Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.

Scream Fortress moment

**Comment by ghost** [comment]
> > Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.
> 
> Scream Fortress moment

Wait, Scream Fortress?! is that a Halloween stage coming?!

**Comment by ImaginaryNeon** [comment]
> > > Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.
> > 
> > 
> > Scream Fortress moment
> 
> Wait, Scream Fortress?! is that a Halloween stage coming?!

No, it's an event in Team Fortress 2 that occurs every October. Although it _would_ be quite funny to see a "Scream Fortress" map.

**Comment by ghost** [comment]
> > > > Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.
> > > 
> > > 
> > > Scream Fortress moment
> > 
> > 
> > Wait, Scream Fortress?! is that a Halloween stage coming?!
> 
> No, it's an event in Team Fortress 2 that occurs every October. Although it _would_ be quite funny to see a "Scream Fortress" map.

Oh. well fr are you gonna do a Halloween update?

**Comment by ImaginaryNeon** [comment]
> > > > > Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.
> > > > 
> > > > 
> > > > Scream Fortress moment
> > > 
> > > 
> > > Wait, Scream Fortress?! is that a Halloween stage coming?!
> > 
> > 
> > No, it's an event in Team Fortress 2 that occurs every October. Although it _would_ be quite funny to see a "Scream Fortress" map.
> 
> Oh. well fr are you gonna do a Halloween update?

**I**'m not going to. I ain't a dev. I'm basically the opposite, being banned. However I don't know at all if there _will_ be a Halloween update,, but if there is, I feel like it'd just be a title screen change or something. However, I definitely _do_ see potential in the Scream Fortress map idea, don't get me wrong.

**Comment by ghost** [comment]
Can you at least tell me what the devs did last year for Halloween?

**Comment by ImaginaryNeon** [comment]
> Can you at least tell me what the devs did last year for Halloween?

I don't know what they did. Fairly certain I was banned by then. Check the sm64js wiki, you may find something there.

**Comment by ImaginaryNeon** [comment]
> > > > > > Are you guys gonna be doing a Halloween update soon like last year? I really hope so because I've been really looking forward to that and I didn't get to experience it last year.
> > > > > 
> > > > > 
> > > > > Scream Fortress moment
> > > > 
> > > > 
> > > > Wait, Scream Fortress?! is that a Halloween stage coming?!
> > > 
> > > 
> > > No, it's an event in Team Fortress 2 that occurs every October. Although it _would_ be quite funny to see a "Scream Fortress" map.
> > 
> > 
> > Oh. well fr are you gonna do a Halloween update?
> 
> **I**'m not going to. I ain't a dev. I'm basically the opposite, being banned. However I don't know at all if there _will_ be a Halloween update,, but if there is, I feel like it'd just be a title screen change or something. However, I definitely _do_ see potential in the Scream Fortress map idea, don't get me wrong.

I'm genuinely considering just trying to make a Scream Fortress map and trying to get it added now...

**Comment by ghost** [comment]
really?!

**Comment by ImaginaryNeon** [comment]
> really?!

I mean I have no idea what I'll be doing ((or what to even use to make the map), but I'll at least try! (When I'm at home!)

**Comment by ghost** [comment]
That's the spirit! Also what do you need to make a map for sm64js?
