### ISSUE TITLE
keeps saying "rom asset extraction success"

### ISSUE THREAD

**Issue by thedogthatsaywemensob** [sm64js/sm64js#755]
whenever I load the website it just says rom asset extraction success how to fix

**Comment by AgentXLP** [comment]
It's supposed to succeed

**Comment by thedogthatsaywemensob** [comment]
I WANTED A DIFFERENT ROM

**Comment by ImaginaryNeon** [comment]
If you would like to change ROMs, click the button that says something along the lines of 'Delete ROM'. Then, after it reloads, you can put the correct ROM in.
