### ISSUE TITLE
I'm begging you guys! Please add Mario and Luigi voice clips!

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#759]
I know you guys have gotten issues like this one. But i'm begging you, PLEASE PLEASE add voice clips for the characters as a last update! I've been wanting this since I started playing. Plus I've seen the files in the commits that you guys do, so I know you guys have them. So pretty please add them in!

**Comment by Bloxxel64** [comment]
we have not gotten the sound system functioning and don't plan to until vanilla is finished.

**Comment by drok28** [comment]
Ok, that makes sense actually. Bc you're trying to get everything from vanilla into MMO, right?
