### ISSUE TITLE
NS (nintendo switch) pro controller 

### ISSUE THREAD

**Issue by Ousadanken** [sm64js/sm64js#760]
the joystick odesn't work on sm64 idk why but im guessing its an unknown controller?

**Comment by Nonethousand** [comment]
odd. my pro controller works. try changing the settings

**Comment by Ousadanken** [comment]
wierd?

**Comment by Ousadanken** [comment]
also wdym the settings

**Comment by Ousadanken** [comment]
i have ps4 controller but i hate it

**Comment by Nonethousand** [comment]
> also wdym the settings

the controller settings

**Comment by AgentXLP** [comment]
https://github.com/Davidobot/BetterJoy
