### ISSUE TITLE
Suggestion: SMO Mario

### ISSUE THREAD

**Issue by PSIPowerhouse** [sm64js/sm64js#765]
Can SMO Mario get added? I feel like this game would be a lot of fun with an SMO Moveset. 

Rolling: For the rolls pls add all activators, as in Long Jump, Ground Pound(Already in the game), Crouching, and Diving. To accelerate the roll, just press Z repeatedly and fast. Roll Cancelling can be the same way as it is now.

Spin Jump: Spin jumping can just be an extra button (X/Y preferably). What it does is if you activate it on the ground it spins you and gives you a floatier jump. Whenever this is activated in the air, it gives you a small boost about 1.5x the height of a DR(Dive Rollout).

Cap jumps: Just make a X/Y button and map them to Throw Cappy. To Do an Aerial Cap Jump, you must jump, press the Cappy Throw button whilst holding in the direction you want to throw cappy in, and then GP dive in the direction of Cappy and jump once you touch cappy. Touching Cappy resets all aerial moves, so you can use them again.

Wall Sliding, and anything else i missed. Hopefully this isn't too much to ask.

**Comment by SonicPlaysSM64JS** [comment]
That sounds pretty interesting, it would be pretty fun to play with the SMO Moveset!

**Comment by PSIPowerhouse** [comment]
Actually fuck it

All these mods fuckin suck and whoever the hell hired them can go suck a dick
