### ISSUE TITLE
Chat filter has the Scunthorpe problem

### ISSUE THREAD

**Issue by lolxdhi1** [sm64js/sm64js#77]
(if you dont know what im talking about, here is an article: https://en.wikipedia.org/wiki/Scunthorpe_problem)

Whenever I try to type Scunthorpe in the chat, it comes up as S****thorpe. Please could you fix this

**Comment by sm64js** [comment]
I am aware of this problem... I don't think there is an easy fix.  I don't think it's too important to type Scunthorpe .... but if there are other words let me know.

**Comment by luphoria** [comment]
There are a number of these types of issues. For example "don't i think" will censor to "don'*****hink", that is one I've seen more than once.
