### ISSUE TITLE
Ban Appeal Attempt

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#779]
![ezgif-1-29f67d65e6](https://user-images.githubusercontent.com/92883596/230954840-eb59844e-7fe0-4438-a21e-7a64249a2d1a.gif)
And yes, I am appealing with a Portal reference.

**Comment by ImaginaryNeon** [comment]
In case you don't want to read it from the image:

```
It's been a while.
Just gonna say this here:
Got regrets.
It's hard to overstate
how long it has been.
64js
I've tried but I just
won't get unbanned.

To: The mods of all this stuff.
(Except the ones who have left.)

Well there's no sense crying
over every mistake.
So I kept on trying,
Didn't want all this hate.
And the alts, they got banned.
Then shit got out of hand.
As I kept attempting
to reprise.


I'm not even angry.
I'm being so sincere right now.
Even though, two years ago,
I was banned.
But I know I fucked up.
And when I fucked up, that I deserved it.
As time passed, I asked because
I just thought the site was cool!
Agent, your 'evidence'
shows it's been a long time.
And it's been some time since.
So then can I retry?
So I'm banned, but I learned,
What to do once I've returned.
Though that assumes I'll get
to reprise.


If this (post) goes poorly,
Just know that I'll be completely fine.
Maybe I'll find somewhere else
to go to.
Kick Open the Door...?
THAT WAS A JOKE. FAT CHANCE.
Anyway, TF2's great.
I've been teleporting bread.
Look at me still talking,
making myself a fool.
If y'all just don't care,
I'll just go back to OU.
I've got Stupid Teams to run.
There's outplaying to be done.
Just in case I don't get
to reprise.


PS: And believe me I'd like
to reprise.
PPS: But I'll be fine if I ain't
gon' reprise.
PPPS: Because REGARDLESS I'll be
still alive.

FINAL THOUGHT:
Been preparing this for 
a long time.

FINAL THOUGHT PS:
I just needed to get that
off my mind.

SO DECIDE
```
please respond

**Comment by ImaginaryNeon** [comment]
@snuffysasa @luphoria @0x2480 @Agent-11 Could someone just respond already? I've been waiting for over a week and nothing's happened.

(I assume that's how you ping people on GitHub but idk)
(Also I don't remember exactly who is and isn't a mod)

**Comment by luphoria** [comment]
I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>

**Comment by ImaginaryNeon** [comment]
> I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>

Where the fuck else was I supposed to put it then?
The Discord that I'm **_also_** banned from?
You see the conundrum here, right?

**Comment by ImaginaryNeon** [comment]
> Where the fuck else was I supposed to put it then? The Discord that I'm **_also_** banned from? You see the conundrum here, right?

Y'know what? I just might have to do exactly that...

_starts typing in my OneNote_

**Comment by ImaginaryNeon** [comment]
Assuming you remember all what stacked to my ban,
Guess I should stress that for the record, I'm sorry for that.
You see, even though it's been two years, that mute I remember,
Felt tethered to never forget, the problems I've had.

Though I've done a lot of learning since that day,
These jeers are always lurking, as if burned into my brain.
In retrospect, those remarks had been worse than rust in taste;
Never turned to think about the burdens I would gain.

I worry this community is keeping a hold,
Thinking I'm a fool, from what I did long ago.
Ever since then, I've been thinking 'bout the things I had wrote,
About the pitfalls that I know, and how I'd been a dope.

In every new victory,
And each low ladder defeat,
With each improvement,
My flukes, become much clearer to me.

But through something that unfolds,
Or through some screenshots of old,
Something always reminds me,
Of these faults I just can't solve.

This shame has burned in my mind,
And to appeal it, I've tried to;
To set the stage, make it clear I'm trying,
Ever since I did a bit of terrorizing.
Living in the aftermath of my errors, trying...

**Comment by uuphoria2** [comment]
> I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>

at this point you should just close the issue as completed lmao :trollface:

**Comment by ImaginaryNeon** [comment]
> > I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>
> 
> at this point you should just close the issue as completed lmao :trollface:

Could you not?

**Comment by uuphoria2** [comment]
> > I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>
> 
> Where the fuck else was I supposed to put it then? The Discord that I'm **_also_** banned from? You see the conundrum here, right?

You dont put it anywhere you keep your ban

**Comment by uuphoria2** [comment]
> > > I have not been a part of sm64js's team for a good year at least now. But given the request was made on the Github, i'm gonna say no for them :>
> > 
> > 
> > at this point you should just close the issue as completed lmao :trollface:
> 
> Could you not?

Could I?
