### ISSUE TITLE
WAIT WHAT THE FUCK

### ISSUE THREAD

**Issue by ImaginaryNeon** [sm64js/sm64js#781]
I just opened sm64js and saw this. Damn. Well shit now what am I gonna do with the vast majority of my OneNote?
![image](https://github.com/sm64js/sm64js/assets/92883596/904da7c2-9730-454a-8dec-485afc315a98)

**Comment by GavinGoGaming** [comment]
there are other online forks! or you can build it yourself using the instructions.

**Comment by ImaginaryNeon** [comment]
> there are other online forks! or you can build it yourself using the instructions.

I'm too much of an idiot as far as that kinda stuff goes.

**Comment by GavinGoGaming** [comment]
heres some links!
https://fishme.me/main/games/sm64
https://fox.klash.dev/main/games/sm64/
<https://fox.klash.dev/main/games/sm64/start.html>
https://sm64--js.glitch.me/start.html
(Click start game)

**Comment by drok28** [comment]
> I just opened sm64js and saw this. Damn. Well shit now what am I gonna do with the vast majority of my OneNote? ![image](https://user-images.githubusercontent.com/92883596/240737562-904da7c2-9730-454a-8dec-485afc315a98.png)
I'm just as shocked as you are, Neon. The saddest part is that the game shut down near the 3 year anniversary.

**Comment by luphoria** [comment]
This was a rogue moderator's decision. Fixed in https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580.

**Comment by GavinGoGaming** [comment]
Will the site go back up soon?

**Comment by luphoria** [comment]
Ideally. I don't have Docker access anymore, and snuffysasa is pretty hands-off, but Tarnadas can do it. ( @Tarnadas ) - i'll also be pinging you on discord.

**Comment by drok28** [comment]
Update: SM64JS is back online!

**Comment by uuphoria** [comment]
> This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).

what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?

**Comment by ImaginaryNeon** [comment]
> > This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).
> 
> what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?

...You do realize there are (probably) other moderators, right?

**Comment by luphoria** [comment]
> > > This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).
> > 
> > 
> > what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?
> 
> ...You do realize there are (probably) other moderators, right?

The rogue moderator was Agent-11. It was his own decision. I'm sure he will give you a reason if you ask him, but the reality is that he is not the owner of the project, and the owner of the project (snuffysasa) did not want to shut down sm64js.

**Comment by uuphoria** [comment]
> > > > This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).
> > > 
> > > 
> > > what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?
> > 
> > 
> > ...You do realize there are (probably) other moderators, right?
> 
> The rogue moderator was Agent-11. It was his own decision. I'm sure he will give you a reason if you ask him, but the reality is that he is not the owner of the project, and the owner of the project (snuffysasa) did not want to shut down sm64js.

alright

**Comment by ImaginaryNeon** [comment]
> > > > This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).
> > > 
> > > 
> > > what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?
> > 
> > 
> > ...You do realize there are (probably) other moderators, right?
> 
> The rogue moderator was Agent-11. It was his own decision. I'm sure he will give you a reason if you ask him, but the reality is that he is not the owner of the project, and the owner of the project (snuffysasa) did not want to shut down sm64js.

oh shit new lore just dropped

**Comment by Bloxxel64** [comment]
> > > > This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).
> > > 
> > > 
> > > what was the reason for agent-11 to change the website like that? was he hacked? was it by choice?
> > 
> > 
> > ...You do realize there are (probably) other moderators, right?
> 
> The rogue moderator was Agent-11. It was his own decision. I'm sure he will give you a reason if you ask him, but the reality is that he is not the owner of the project, and the owner of the project (snuffysasa) did not want to shut down sm64js.

Ah man, what a rouge decision to close an unmaintained cesspool of immature children that no one cares to moderate anymore. How dare the person who basically took over the project do such a thing.

**Comment by luphoria** [comment]
@Bloxxel64 
> Ah man, what a rouge decision to close an unmaintained cesspool of immature children that no one cares to moderate anymore. How dare the person who basically took over the project do such a thing.

I didn't comment on, nor insult, Agent-11. You are turning this into an insult of me because of your presumptions on my character. The _reality_ is that Agent-11 took action, and the owner of the project did not want that action to be taken. By definition, that is a rogue decision. Your, my, or Agent-11's opinion is irrelevant. It's not our project.

**Comment by queenkoopa8500** [comment]
> This was a rogue moderator's decision. Fixed in [46edd5a](https://github.com/sm64js/sm64js/commit/46edd5af1137674a352aa46690a7e6c43439a580).

what happened to sm64js now?
