### ISSUE TITLE
(Feature) Add custom control presets/Customize controls

### ISSUE THREAD

**Issue by Cooliokid956** [sm64js/sm64js#8]
I used to play on the ex pc port where i could change the controls and now i wish i could do it here

**Comment by sm64js** [comment]
This feature has been added. It's quite limited and minimal for now. 
Let me know if you have suggestions.

**Comment by Cooliokid956** [comment]
wow
pretty cool
though along with this I made a discovery
the left long-jump giltch still happens with arrow keys
