### ISSUE TITLE
Pressing respawn while under water in dolphin town makes you go under the boat

### ISSUE THREAD

**Issue by uuphoria** [sm64js/sm64js#802]
![dolphinglitch](https://github.com/sm64js/sm64js/assets/123761856/ef66ba14-6a1d-4adf-a95b-1a7b721eaaa9)

**Comment by ImaginaryNeon** [comment]
Interesting.
If I had to guess, pressing 'Respawn' likely sends you to a fixed location, which, in this case, seems to be incorrectly located.

If the coordinates used for said transport are the same across maps, then the whole map would have to be moved to accommodate. But if not, then only the coordinates would need to be changed.

**Comment by ImaginaryNeon** [comment]
Oh wait, you specified while underwater.
Maybe the swimming state prevents the respawn button from functioning correctly.

(i.e. Maybe it won't let you teleport out of water whilst swimming)

**Comment by uuphoria** [comment]
Maybe, guess that's the problem
