### ISSUE TITLE
Why is the site unsafe?

### ISSUE THREAD

**Issue by ghost** [sm64js/sm64js#804]
google is yapping about the site not being secure

**Comment by queenkoopa8500** [comment]
someone at sm64js has to pay for the ssl basically (Security thing) that tells the site its safe

**Comment by ghost** [comment]
I figured that was the reason

**Comment by queenkoopa8500** [comment]
> I figured that was the reason

UPDATE: The website now goes back to old sm64js or it just doesnt load cuz of the most mmo files are gone now
