### ISSUE TITLE
what happened to sm64js? (PLEASE HELP)

### ISSUE THREAD

**Issue by queenkoopa8500** [sm64js/sm64js#805]
![image](https://github.com/sm64js/sm64js/assets/155935644/3749fe26-9424-4c86-95f8-bea837936544)

**Comment by queenkoopa8500** [comment]
or it just goes to old sm64js (normal 60fps)

**Comment by SLG64** [comment]
I think the certificate for the main website expired, and they probably forgot about this project. I don't know when it'll be back up, so the regular 60fps is all we can really use.

**Comment by queenkoopa8500** [comment]
> I think the certificate for the main website expired, and they probably forgot about this project. I don't know when it'll be back up, so the regular 60fps is all we can really use.

The certificate is back at https://sm64js.com at tho only 60fps can be used

**Comment by queenkoopa8500** [comment]
I'll close this as not planned this will be closed as completed once the website is back or its resolved

**Comment by SLG64** [comment]
They're rebuilding SM64JS, but it won't have online functionality because Agent X abandoned the project.

**Comment by Bloxxel64** [comment]
no they arent lol

**Comment by SLG64** [comment]
Check the discord if you don't believe me

**Comment by Bloxxel64** [comment]
I left that shithole a long time ago, just like a lot of the development team did, and for good reason.

**Comment by SLG64** [comment]
Ah. Fair enough.

**Comment by rWiiolU** [comment]
> I left that shithole a long time ago, just like a lot of the development team did, and for good reason.

what happened? im curious
