### ISSUE TITLE
MMO not working?

### ISSUE THREAD

**Issue by Jujumar123onGITHUB** [sm64js/sm64js#811]
I've tried to open sm64js MMO, but it puts me in the vanilla version? I don't know. It's confusing, but basically I can't use multiplayer, it only opens vanilla when I press the mmo button.

**Comment by queenkoopa8500** [comment]
The server for it isnt running aka its down

**Comment by Jujumar123onGITHUB** [comment]
oh ok

**Comment by Jujumar123onGITHUB** [comment]
so nvm yeah but tell me when it gets back up

**Comment by uuphoria2** [comment]
I have my own remake (basically reboot and rewrite) of sm64js on my website https://mmo.sm64jsarchive.com the steps to set it up and best browser to use (and a screenshot explaining everytihng and additional info txet) are on this: https://github.com/uuphoria2/sm64jsarchive/blob/MMO/README.md You might need to scroll down a little tho go where it says "Info for MMO on https://mmo.sm64jsarchive.com/:" also you do still need your legally obtained US SM64 ROM as normal sm64js would for legal reasons

> so nvm yeah but tell me when it gets back up

**Comment by uuphoria2** [comment]
> so nvm yeah but tell me when it gets back up

The README.md for sm64jsarchive also has some troubleshooting in the additional info within specifically the: "Info for MMO on https://mmo.sm64jsarchive.com/:" section.

**Comment by uuphoria2** [comment]
@Jujumar123onGITHUB Its not fully ready to be put on web yet

**Comment by uuphoria2** [comment]
@Jujumar123onGITHUB THE GAME IS NOW FULLY READY AND sm64jsarchive (the rewrite and remake) version of sm64js im making is now released!! come play: https://mmo.sm64jsarchive.com

**Comment by Jujumar123onGITHUB** [comment]
WOW!

**Comment by Jujumar123onGITHUB** [comment]
wait its not loading for some reason

**Comment by Jujumar123onGITHUB** [comment]
its like stuck on redirecting

**Comment by uuphoria2** [comment]
> its like stuck on redirecting

Redirects are actively being fixed by me

**Comment by uuphoria2** [comment]
> its like stuck on redirecting

Everyone and you can play now https://mmo.sm64jsarchive.com/ redirects fixed

**Comment by uuphoria2** [comment]
> its like stuck on redirecting

Only google signin works btw

**Comment by Jujumar123onGITHUB** [comment]
kk its working

**Comment by ImaginaryNeon** [comment]
"due to it being very late at night"
mfw 9:00 AM
(y'all european or smth?)

**Comment by uuphoria2** [comment]
> "due to it being very late at night" mfw 9:00 AM (y'all european or smth?)

Its up now I just forgot to change it

**Comment by uuphoria2** [comment]
> "due to it being very late at night" mfw 9:00 AM (y'all european or smth?)

https://mmo.sm64jsarchive.com I just put the website online you just have to wait for the offline screen to go to online which currently its now online :)

**Comment by uuphoria2** [comment]
> "due to it being very late at night" mfw 9:00 AM (y'all european or smth?)

Website may not work temporarily due to server changes right now before you go: site aint working

**Comment by queenkoopa8500** [comment]
> "due to it being very late at night" mfw 9:00 AM (y'all european or smth?)

i know this is kinda late but, sm64jsarchive now runs 24/7 lmao (not only when im online) go to https://sm64jsarchive.com if you want to play still
