### ISSUE TITLE
R.I.P Sm64js

### ISSUE THREAD

**Issue by SANTIQDCO** [sm64js/sm64js#814]
Only this page works...
https://web.archive.org/web/20210501110746/https://sm64js.com/
![Nueva pestaña - Google Chrome 26_05_2024 18_12_11](https://github.com/sm64js/sm64js/assets/164812142/f382c282-00b6-488f-8c1f-99e943fc8e63)

**Comment by SANTIQDCO** [comment]
Why that happend pls update and make it back plsss

**Comment by donaldscot** [comment]
rip indeed

**Comment by GreenieTheHedgehog** [comment]
For me the page doesn't even load, it just pulls up the connection refused error

**Comment by Bloxxel64** [comment]
Yippie!

**Comment by abnormalhare** [comment]
The website now loads
