### ISSUE TITLE
Suggestion: When in full screen mode make chat be able to pull down from top or a menu to change colors in full srceen

### ISSUE THREAD

**Issue by Retro-Wave** [sm64js/sm64js#84]

**Comment by Kevin-Is-Nice** [comment]
**### _y e s_**

**Comment by Whoblue579** [comment]
Professional game devs will always tell you gameplay first, then gui, asthetics, and other things

**Comment by Kevin-Is-Nice** [comment]
> Professional game devs will always tell you gameplay first, then gui, asthetics, and other things

oh ok so eventually they will do that

**Comment by luphoria** [comment]
Duplicate of #19, why did nobody close this previously
