### ISSUE TITLE
"Tornado Drill" Bug

### ISSUE THREAD

**Issue by naw9457** [sm64js/sm64js#88]
If you remember your school days or are still in school and do tornado drills, you probably know why I called it this.

After 5 minutes of horsing around in BoB, everyone just walks into the nearest wall, slope, or not. Now this gets frustrating as it always happens to me and it doesn't say anything in chat or that I had disconnected from the server. It acted as if I was still in the server, but no one was acting like normal. Chat just doesn't show up.

Please fix this "Tornado Drill" from happening after every five minutes! I would appreciate it!

**Comment by luphoria** [comment]
This means you've disconnected from the server. You need to refresh the page to reconnect.

**Comment by Cooliokid956** [comment]
no

**Comment by Cooliokid956** [comment]
sometimes it takes a long time to send all of the player's movements, just like chat, but when everything is received, it goes kinda back to normal

**Comment by sm64js** [comment]
Sounds like disconnected from the server... or the server is not performing adequately, I am working on server performance issues and will be continuing to make updates.
