### ISSUE TITLE
Racist People 

### ISSUE THREAD

**Issue by GlitchyFilling** [sm64js/sm64js#90]
I have a problem every now and then there are racist people on your server. It's illegal to treat people differently because of their race or culture. I think you need an anti-bypass filter to not let anyone say mean things.

Footage: https://www.youtube.com/watch?v=igUk84Uez2Y

**Comment by biomseed** [comment]
These people think it's funny, and some even legitimately think these things

**Comment by sm64js** [comment]
I added a filter to usernames and to chat messages also added the ability to block people.  Let me know if you have more ideas on how to handle the issue. I am all ears.
